-- Explicit server roles for candidate schema 055. Operator-only; no passwords.
-- Clients do not receive these roles. API/worker validate account scopes themselves.
-- Policies below authorize server jobs; client anon/authenticated policies remain intact.
begin;
do $$ begin
  if not exists (select 1 from public.evidrilo_schema_migrations where version='055_runtime_account_lock') then
    raise exception 'Apply and verify candidate migrations through 055 first';
  end if;
end $$;
do $$ begin
  if not exists (select 1 from pg_roles where rolname='evidrilo_api') then
    create role evidrilo_api nologin nosuperuser nocreatedb nocreaterole noinherit noreplication nobypassrls;
  end if;
  if exists (select 1 from pg_roles where rolname='evidrilo_api' and (rolsuper or rolcreatedb or rolcreaterole or rolreplication or rolbypassrls or rolinherit)) then
    raise exception 'Runtime role must have unprivileged attributes';
  end if;
  if exists (select 1 from pg_auth_members where member=(select oid from pg_roles where rolname='evidrilo_api')) then
    raise exception 'Runtime role must not inherit other roles';
  end if;
end $$;
grant usage on schema public, auth to evidrilo_api;
grant execute on function auth.uid() to evidrilo_api;
revoke all on all tables in schema public from evidrilo_api;
revoke all on all sequences in schema public from evidrilo_api;
grant select on table public.account_deletion_requests to evidrilo_api;
drop policy if exists evidrilo_api_select on public.account_deletion_requests;
create policy evidrilo_api_select on public.account_deletion_requests for select to evidrilo_api using (true);
grant select on table public.account_deletion_tombstones to evidrilo_api;
drop policy if exists evidrilo_api_select on public.account_deletion_tombstones;
create policy evidrilo_api_select on public.account_deletion_tombstones for select to evidrilo_api using (true);
grant delete, insert, select, update on table public.account_export_jobs to evidrilo_api;
drop policy if exists evidrilo_api_delete on public.account_export_jobs;
create policy evidrilo_api_delete on public.account_export_jobs for delete to evidrilo_api using (true);
drop policy if exists evidrilo_api_insert on public.account_export_jobs;
create policy evidrilo_api_insert on public.account_export_jobs for insert to evidrilo_api with check (true);
drop policy if exists evidrilo_api_select on public.account_export_jobs;
create policy evidrilo_api_select on public.account_export_jobs for select to evidrilo_api using (true);
drop policy if exists evidrilo_api_update on public.account_export_jobs;
create policy evidrilo_api_update on public.account_export_jobs for update to evidrilo_api using (true) with check (true);
grant select on table public.account_profiles to evidrilo_api;
drop policy if exists evidrilo_api_select on public.account_profiles;
create policy evidrilo_api_select on public.account_profiles for select to evidrilo_api using (true);
grant insert, select on table public.ai_audit_events to evidrilo_api;
drop policy if exists evidrilo_api_insert on public.ai_audit_events;
create policy evidrilo_api_insert on public.ai_audit_events for insert to evidrilo_api with check (true);
drop policy if exists evidrilo_api_select on public.ai_audit_events;
create policy evidrilo_api_select on public.ai_audit_events for select to evidrilo_api using (true);
grant delete, insert, select, update on table public.ai_conversation_sessions to evidrilo_api;
drop policy if exists evidrilo_api_delete on public.ai_conversation_sessions;
create policy evidrilo_api_delete on public.ai_conversation_sessions for delete to evidrilo_api using (true);
drop policy if exists evidrilo_api_insert on public.ai_conversation_sessions;
create policy evidrilo_api_insert on public.ai_conversation_sessions for insert to evidrilo_api with check (true);
drop policy if exists evidrilo_api_select on public.ai_conversation_sessions;
create policy evidrilo_api_select on public.ai_conversation_sessions for select to evidrilo_api using (true);
drop policy if exists evidrilo_api_update on public.ai_conversation_sessions;
create policy evidrilo_api_update on public.ai_conversation_sessions for update to evidrilo_api using (true) with check (true);
grant insert, select, update on table public.ai_conversation_turn_requests to evidrilo_api;
drop policy if exists evidrilo_api_insert on public.ai_conversation_turn_requests;
create policy evidrilo_api_insert on public.ai_conversation_turn_requests for insert to evidrilo_api with check (true);
drop policy if exists evidrilo_api_select on public.ai_conversation_turn_requests;
create policy evidrilo_api_select on public.ai_conversation_turn_requests for select to evidrilo_api using (true);
drop policy if exists evidrilo_api_update on public.ai_conversation_turn_requests;
create policy evidrilo_api_update on public.ai_conversation_turn_requests for update to evidrilo_api using (true) with check (true);
grant insert, select, update on table public.ai_credit_consents to evidrilo_api;
drop policy if exists evidrilo_api_insert on public.ai_credit_consents;
create policy evidrilo_api_insert on public.ai_credit_consents for insert to evidrilo_api with check (true);
drop policy if exists evidrilo_api_select on public.ai_credit_consents;
create policy evidrilo_api_select on public.ai_credit_consents for select to evidrilo_api using (true);
drop policy if exists evidrilo_api_update on public.ai_credit_consents;
create policy evidrilo_api_update on public.ai_credit_consents for update to evidrilo_api using (true) with check (true);
grant insert, select, update on table public.ai_credit_grants to evidrilo_api;
drop policy if exists evidrilo_api_insert on public.ai_credit_grants;
create policy evidrilo_api_insert on public.ai_credit_grants for insert to evidrilo_api with check (true);
drop policy if exists evidrilo_api_select on public.ai_credit_grants;
create policy evidrilo_api_select on public.ai_credit_grants for select to evidrilo_api using (true);
drop policy if exists evidrilo_api_update on public.ai_credit_grants;
create policy evidrilo_api_update on public.ai_credit_grants for update to evidrilo_api using (true) with check (true);
grant insert, select, update on table public.ai_credit_reservation_allocations to evidrilo_api;
drop policy if exists evidrilo_api_insert on public.ai_credit_reservation_allocations;
create policy evidrilo_api_insert on public.ai_credit_reservation_allocations for insert to evidrilo_api with check (true);
drop policy if exists evidrilo_api_select on public.ai_credit_reservation_allocations;
create policy evidrilo_api_select on public.ai_credit_reservation_allocations for select to evidrilo_api using (true);
drop policy if exists evidrilo_api_update on public.ai_credit_reservation_allocations;
create policy evidrilo_api_update on public.ai_credit_reservation_allocations for update to evidrilo_api using (true) with check (true);
grant insert, select, update on table public.ai_credit_reservations to evidrilo_api;
drop policy if exists evidrilo_api_insert on public.ai_credit_reservations;
create policy evidrilo_api_insert on public.ai_credit_reservations for insert to evidrilo_api with check (true);
drop policy if exists evidrilo_api_select on public.ai_credit_reservations;
create policy evidrilo_api_select on public.ai_credit_reservations for select to evidrilo_api using (true);
drop policy if exists evidrilo_api_update on public.ai_credit_reservations;
create policy evidrilo_api_update on public.ai_credit_reservations for update to evidrilo_api using (true) with check (true);
grant insert, select, update on table public.ai_provider_monthly_spend to evidrilo_api;
drop policy if exists evidrilo_api_insert on public.ai_provider_monthly_spend;
create policy evidrilo_api_insert on public.ai_provider_monthly_spend for insert to evidrilo_api with check (true);
drop policy if exists evidrilo_api_select on public.ai_provider_monthly_spend;
create policy evidrilo_api_select on public.ai_provider_monthly_spend for select to evidrilo_api using (true);
drop policy if exists evidrilo_api_update on public.ai_provider_monthly_spend;
create policy evidrilo_api_update on public.ai_provider_monthly_spend for update to evidrilo_api using (true) with check (true);
grant insert, select, update on table public.ai_provider_spend_reservations to evidrilo_api;
drop policy if exists evidrilo_api_insert on public.ai_provider_spend_reservations;
create policy evidrilo_api_insert on public.ai_provider_spend_reservations for insert to evidrilo_api with check (true);
drop policy if exists evidrilo_api_select on public.ai_provider_spend_reservations;
create policy evidrilo_api_select on public.ai_provider_spend_reservations for select to evidrilo_api using (true);
drop policy if exists evidrilo_api_update on public.ai_provider_spend_reservations;
create policy evidrilo_api_update on public.ai_provider_spend_reservations for update to evidrilo_api using (true) with check (true);
grant insert, select on table public.analytics_events to evidrilo_api;
drop policy if exists evidrilo_api_insert on public.analytics_events;
create policy evidrilo_api_insert on public.analytics_events for insert to evidrilo_api with check (true);
drop policy if exists evidrilo_api_select on public.analytics_events;
create policy evidrilo_api_select on public.analytics_events for select to evidrilo_api using (true);
grant insert, select on table public.attempt_commands to evidrilo_api;
drop policy if exists evidrilo_api_insert on public.attempt_commands;
create policy evidrilo_api_insert on public.attempt_commands for insert to evidrilo_api with check (true);
drop policy if exists evidrilo_api_select on public.attempt_commands;
create policy evidrilo_api_select on public.attempt_commands for select to evidrilo_api using (true);
grant select on table public.case_lifecycle_audit_events to evidrilo_api;
drop policy if exists evidrilo_api_select on public.case_lifecycle_audit_events;
create policy evidrilo_api_select on public.case_lifecycle_audit_events for select to evidrilo_api using (true);
grant insert, select on table public.case_review_decisions to evidrilo_api;
drop policy if exists evidrilo_api_insert on public.case_review_decisions;
create policy evidrilo_api_insert on public.case_review_decisions for insert to evidrilo_api with check (true);
drop policy if exists evidrilo_api_select on public.case_review_decisions;
create policy evidrilo_api_select on public.case_review_decisions for select to evidrilo_api using (true);
grant insert, select, update on table public.case_versions to evidrilo_api;
drop policy if exists evidrilo_api_insert on public.case_versions;
create policy evidrilo_api_insert on public.case_versions for insert to evidrilo_api with check (true);
drop policy if exists evidrilo_api_select on public.case_versions;
create policy evidrilo_api_select on public.case_versions for select to evidrilo_api using (true);
drop policy if exists evidrilo_api_update on public.case_versions;
create policy evidrilo_api_update on public.case_versions for update to evidrilo_api using (true) with check (true);
grant insert, select, update on table public.entitlement_events to evidrilo_api;
drop policy if exists evidrilo_api_insert on public.entitlement_events;
create policy evidrilo_api_insert on public.entitlement_events for insert to evidrilo_api with check (true);
drop policy if exists evidrilo_api_select on public.entitlement_events;
create policy evidrilo_api_select on public.entitlement_events for select to evidrilo_api using (true);
drop policy if exists evidrilo_api_update on public.entitlement_events;
create policy evidrilo_api_update on public.entitlement_events for update to evidrilo_api using (true) with check (true);
grant insert, select on table public.entitlements to evidrilo_api;
drop policy if exists evidrilo_api_insert on public.entitlements;
create policy evidrilo_api_insert on public.entitlements for insert to evidrilo_api with check (true);
drop policy if exists evidrilo_api_select on public.entitlements;
create policy evidrilo_api_select on public.entitlements for select to evidrilo_api using (true);
grant select on table public.evidrilo_schema_migrations to evidrilo_api;
grant insert, select on table public.membership_audit_events to evidrilo_api;
drop policy if exists evidrilo_api_insert on public.membership_audit_events;
create policy evidrilo_api_insert on public.membership_audit_events for insert to evidrilo_api with check (true);
drop policy if exists evidrilo_api_select on public.membership_audit_events;
create policy evidrilo_api_select on public.membership_audit_events for select to evidrilo_api using (true);
grant insert, select, update on table public.notification_preferences to evidrilo_api;
drop policy if exists evidrilo_api_insert on public.notification_preferences;
create policy evidrilo_api_insert on public.notification_preferences for insert to evidrilo_api with check (true);
drop policy if exists evidrilo_api_select on public.notification_preferences;
create policy evidrilo_api_select on public.notification_preferences for select to evidrilo_api using (true);
drop policy if exists evidrilo_api_update on public.notification_preferences;
create policy evidrilo_api_update on public.notification_preferences for update to evidrilo_api using (true) with check (true);
grant insert, select, update on table public.organization_memberships to evidrilo_api;
drop policy if exists evidrilo_api_insert on public.organization_memberships;
create policy evidrilo_api_insert on public.organization_memberships for insert to evidrilo_api with check (true);
drop policy if exists evidrilo_api_select on public.organization_memberships;
create policy evidrilo_api_select on public.organization_memberships for select to evidrilo_api using (true);
drop policy if exists evidrilo_api_update on public.organization_memberships;
create policy evidrilo_api_update on public.organization_memberships for update to evidrilo_api using (true) with check (true);
grant select on table public.organizations to evidrilo_api;
drop policy if exists evidrilo_api_select on public.organizations;
create policy evidrilo_api_select on public.organizations for select to evidrilo_api using (true);
grant select on table public.progress_daily_projections to evidrilo_api;
drop policy if exists evidrilo_api_select on public.progress_daily_projections;
create policy evidrilo_api_select on public.progress_daily_projections for select to evidrilo_api using (true);
grant select on table public.progress_projections to evidrilo_api;
drop policy if exists evidrilo_api_select on public.progress_projections;
create policy evidrilo_api_select on public.progress_projections for select to evidrilo_api using (true);
grant delete, insert, select, update on table public.project_ai_activity to evidrilo_api;
drop policy if exists evidrilo_api_delete on public.project_ai_activity;
create policy evidrilo_api_delete on public.project_ai_activity for delete to evidrilo_api using (true);
drop policy if exists evidrilo_api_insert on public.project_ai_activity;
create policy evidrilo_api_insert on public.project_ai_activity for insert to evidrilo_api with check (true);
drop policy if exists evidrilo_api_select on public.project_ai_activity;
create policy evidrilo_api_select on public.project_ai_activity for select to evidrilo_api using (true);
drop policy if exists evidrilo_api_update on public.project_ai_activity;
create policy evidrilo_api_update on public.project_ai_activity for update to evidrilo_api using (true) with check (true);
grant insert, select on table public.project_ai_consent_events to evidrilo_api;
drop policy if exists evidrilo_api_insert on public.project_ai_consent_events;
create policy evidrilo_api_insert on public.project_ai_consent_events for insert to evidrilo_api with check (true);
drop policy if exists evidrilo_api_select on public.project_ai_consent_events;
create policy evidrilo_api_select on public.project_ai_consent_events for select to evidrilo_api using (true);
grant insert, select, update on table public.project_ai_consents to evidrilo_api;
drop policy if exists evidrilo_api_insert on public.project_ai_consents;
create policy evidrilo_api_insert on public.project_ai_consents for insert to evidrilo_api with check (true);
drop policy if exists evidrilo_api_select on public.project_ai_consents;
create policy evidrilo_api_select on public.project_ai_consents for select to evidrilo_api using (true);
drop policy if exists evidrilo_api_update on public.project_ai_consents;
create policy evidrilo_api_update on public.project_ai_consents for update to evidrilo_api using (true) with check (true);
grant delete, insert, select, update on table public.project_ai_local_contexts to evidrilo_api;
drop policy if exists evidrilo_api_delete on public.project_ai_local_contexts;
create policy evidrilo_api_delete on public.project_ai_local_contexts for delete to evidrilo_api using (true);
drop policy if exists evidrilo_api_insert on public.project_ai_local_contexts;
create policy evidrilo_api_insert on public.project_ai_local_contexts for insert to evidrilo_api with check (true);
drop policy if exists evidrilo_api_select on public.project_ai_local_contexts;
create policy evidrilo_api_select on public.project_ai_local_contexts for select to evidrilo_api using (true);
drop policy if exists evidrilo_api_update on public.project_ai_local_contexts;
create policy evidrilo_api_update on public.project_ai_local_contexts for update to evidrilo_api using (true) with check (true);
grant insert, select on table public.project_template_review_decisions to evidrilo_api;
drop policy if exists evidrilo_api_insert on public.project_template_review_decisions;
create policy evidrilo_api_insert on public.project_template_review_decisions for insert to evidrilo_api with check (true);
drop policy if exists evidrilo_api_select on public.project_template_review_decisions;
create policy evidrilo_api_select on public.project_template_review_decisions for select to evidrilo_api using (true);
grant insert, select, update on table public.project_template_versions to evidrilo_api;
drop policy if exists evidrilo_api_insert on public.project_template_versions;
create policy evidrilo_api_insert on public.project_template_versions for insert to evidrilo_api with check (true);
drop policy if exists evidrilo_api_select on public.project_template_versions;
create policy evidrilo_api_select on public.project_template_versions for select to evidrilo_api using (true);
drop policy if exists evidrilo_api_update on public.project_template_versions;
create policy evidrilo_api_update on public.project_template_versions for update to evidrilo_api using (true) with check (true);
grant insert, select on table public.recommendation_events to evidrilo_api;
drop policy if exists evidrilo_api_insert on public.recommendation_events;
create policy evidrilo_api_insert on public.recommendation_events for insert to evidrilo_api with check (true);
drop policy if exists evidrilo_api_select on public.recommendation_events;
create policy evidrilo_api_select on public.recommendation_events for select to evidrilo_api using (true);
grant insert, select on table public.student_project_cloud_consent_events to evidrilo_api;
drop policy if exists evidrilo_api_insert on public.student_project_cloud_consent_events;
create policy evidrilo_api_insert on public.student_project_cloud_consent_events for insert to evidrilo_api with check (true);
drop policy if exists evidrilo_api_select on public.student_project_cloud_consent_events;
create policy evidrilo_api_select on public.student_project_cloud_consent_events for select to evidrilo_api using (true);
grant insert, select, update on table public.student_project_cloud_consents to evidrilo_api;
drop policy if exists evidrilo_api_insert on public.student_project_cloud_consents;
create policy evidrilo_api_insert on public.student_project_cloud_consents for insert to evidrilo_api with check (true);
drop policy if exists evidrilo_api_select on public.student_project_cloud_consents;
create policy evidrilo_api_select on public.student_project_cloud_consents for select to evidrilo_api using (true);
drop policy if exists evidrilo_api_update on public.student_project_cloud_consents;
create policy evidrilo_api_update on public.student_project_cloud_consents for update to evidrilo_api using (true) with check (true);
grant insert, select, update on table public.student_project_commands to evidrilo_api;
drop policy if exists evidrilo_api_insert on public.student_project_commands;
create policy evidrilo_api_insert on public.student_project_commands for insert to evidrilo_api with check (true);
drop policy if exists evidrilo_api_select on public.student_project_commands;
create policy evidrilo_api_select on public.student_project_commands for select to evidrilo_api using (true);
drop policy if exists evidrilo_api_update on public.student_project_commands;
create policy evidrilo_api_update on public.student_project_commands for update to evidrilo_api using (true) with check (true);
grant insert, select on table public.student_project_revisions to evidrilo_api;
drop policy if exists evidrilo_api_insert on public.student_project_revisions;
create policy evidrilo_api_insert on public.student_project_revisions for insert to evidrilo_api with check (true);
drop policy if exists evidrilo_api_select on public.student_project_revisions;
create policy evidrilo_api_select on public.student_project_revisions for select to evidrilo_api using (true);
grant delete, insert, select, update on table public.student_projects to evidrilo_api;
drop policy if exists evidrilo_api_delete on public.student_projects;
create policy evidrilo_api_delete on public.student_projects for delete to evidrilo_api using (true);
drop policy if exists evidrilo_api_insert on public.student_projects;
create policy evidrilo_api_insert on public.student_projects for insert to evidrilo_api with check (true);
drop policy if exists evidrilo_api_select on public.student_projects;
create policy evidrilo_api_select on public.student_projects for select to evidrilo_api using (true);
drop policy if exists evidrilo_api_update on public.student_projects;
create policy evidrilo_api_update on public.student_projects for update to evidrilo_api using (true) with check (true);
grant select on table public.sync_changes to evidrilo_api;
drop policy if exists evidrilo_api_select on public.sync_changes;
create policy evidrilo_api_select on public.sync_changes for select to evidrilo_api using (true);
do $$ begin
  if not exists (select 1 from pg_roles where rolname='evidrilo_worker') then
    create role evidrilo_worker nologin nosuperuser nocreatedb nocreaterole noinherit noreplication nobypassrls;
  end if;
  if exists (select 1 from pg_roles where rolname='evidrilo_worker' and (rolsuper or rolcreatedb or rolcreaterole or rolreplication or rolbypassrls or rolinherit)) then
    raise exception 'Runtime role must have unprivileged attributes';
  end if;
  if exists (select 1 from pg_auth_members where member=(select oid from pg_roles where rolname='evidrilo_worker')) then
    raise exception 'Runtime role must not inherit other roles';
  end if;
end $$;
grant usage on schema public, auth to evidrilo_worker;
grant execute on function auth.uid() to evidrilo_worker;
revoke all on all tables in schema public from evidrilo_worker;
revoke all on all sequences in schema public from evidrilo_worker;
grant select, update on table public.account_auth_deletion_outbox to evidrilo_worker;
drop policy if exists evidrilo_worker_select on public.account_auth_deletion_outbox;
create policy evidrilo_worker_select on public.account_auth_deletion_outbox for select to evidrilo_worker using (true);
drop policy if exists evidrilo_worker_update on public.account_auth_deletion_outbox;
create policy evidrilo_worker_update on public.account_auth_deletion_outbox for update to evidrilo_worker using (true) with check (true);
grant select on table public.account_deletion_requests to evidrilo_worker;
drop policy if exists evidrilo_worker_select on public.account_deletion_requests;
create policy evidrilo_worker_select on public.account_deletion_requests for select to evidrilo_worker using (true);
grant select on table public.account_deletion_tombstones to evidrilo_worker;
drop policy if exists evidrilo_worker_select on public.account_deletion_tombstones;
create policy evidrilo_worker_select on public.account_deletion_tombstones for select to evidrilo_worker using (true);
grant delete, select, update on table public.account_export_jobs to evidrilo_worker;
drop policy if exists evidrilo_worker_delete on public.account_export_jobs;
create policy evidrilo_worker_delete on public.account_export_jobs for delete to evidrilo_worker using (true);
drop policy if exists evidrilo_worker_select on public.account_export_jobs;
create policy evidrilo_worker_select on public.account_export_jobs for select to evidrilo_worker using (true);
drop policy if exists evidrilo_worker_update on public.account_export_jobs;
create policy evidrilo_worker_update on public.account_export_jobs for update to evidrilo_worker using (true) with check (true);
grant select on table public.account_profiles to evidrilo_worker;
drop policy if exists evidrilo_worker_select on public.account_profiles;
create policy evidrilo_worker_select on public.account_profiles for select to evidrilo_worker using (true);
grant select on table public.ai_audit_events to evidrilo_worker;
drop policy if exists evidrilo_worker_select on public.ai_audit_events;
create policy evidrilo_worker_select on public.ai_audit_events for select to evidrilo_worker using (true);
grant select on table public.ai_conversation_sessions to evidrilo_worker;
drop policy if exists evidrilo_worker_select on public.ai_conversation_sessions;
create policy evidrilo_worker_select on public.ai_conversation_sessions for select to evidrilo_worker using (true);
grant select on table public.ai_conversation_turn_requests to evidrilo_worker;
drop policy if exists evidrilo_worker_select on public.ai_conversation_turn_requests;
create policy evidrilo_worker_select on public.ai_conversation_turn_requests for select to evidrilo_worker using (true);
grant select on table public.ai_credit_consents to evidrilo_worker;
drop policy if exists evidrilo_worker_select on public.ai_credit_consents;
create policy evidrilo_worker_select on public.ai_credit_consents for select to evidrilo_worker using (true);
grant select on table public.ai_credit_grants to evidrilo_worker;
drop policy if exists evidrilo_worker_select on public.ai_credit_grants;
create policy evidrilo_worker_select on public.ai_credit_grants for select to evidrilo_worker using (true);
grant select on table public.ai_credit_reservations to evidrilo_worker;
drop policy if exists evidrilo_worker_select on public.ai_credit_reservations;
create policy evidrilo_worker_select on public.ai_credit_reservations for select to evidrilo_worker using (true);
grant select on table public.analytics_events to evidrilo_worker;
drop policy if exists evidrilo_worker_select on public.analytics_events;
create policy evidrilo_worker_select on public.analytics_events for select to evidrilo_worker using (true);
grant select on table public.attempt_commands to evidrilo_worker;
drop policy if exists evidrilo_worker_select on public.attempt_commands;
create policy evidrilo_worker_select on public.attempt_commands for select to evidrilo_worker using (true);
grant select on table public.entitlement_events to evidrilo_worker;
drop policy if exists evidrilo_worker_select on public.entitlement_events;
create policy evidrilo_worker_select on public.entitlement_events for select to evidrilo_worker using (true);
grant select on table public.entitlements to evidrilo_worker;
drop policy if exists evidrilo_worker_select on public.entitlements;
create policy evidrilo_worker_select on public.entitlements for select to evidrilo_worker using (true);
grant select on table public.notification_preferences to evidrilo_worker;
drop policy if exists evidrilo_worker_select on public.notification_preferences;
create policy evidrilo_worker_select on public.notification_preferences for select to evidrilo_worker using (true);
grant delete, insert, select on table public.progress_daily_projections to evidrilo_worker;
drop policy if exists evidrilo_worker_delete on public.progress_daily_projections;
create policy evidrilo_worker_delete on public.progress_daily_projections for delete to evidrilo_worker using (true);
drop policy if exists evidrilo_worker_insert on public.progress_daily_projections;
create policy evidrilo_worker_insert on public.progress_daily_projections for insert to evidrilo_worker with check (true);
drop policy if exists evidrilo_worker_select on public.progress_daily_projections;
create policy evidrilo_worker_select on public.progress_daily_projections for select to evidrilo_worker using (true);
grant insert, select, update on table public.progress_projections to evidrilo_worker;
drop policy if exists evidrilo_worker_insert on public.progress_projections;
create policy evidrilo_worker_insert on public.progress_projections for insert to evidrilo_worker with check (true);
drop policy if exists evidrilo_worker_select on public.progress_projections;
create policy evidrilo_worker_select on public.progress_projections for select to evidrilo_worker using (true);
drop policy if exists evidrilo_worker_update on public.progress_projections;
create policy evidrilo_worker_update on public.progress_projections for update to evidrilo_worker using (true) with check (true);
grant select on table public.project_ai_activity to evidrilo_worker;
drop policy if exists evidrilo_worker_select on public.project_ai_activity;
create policy evidrilo_worker_select on public.project_ai_activity for select to evidrilo_worker using (true);
grant select on table public.project_ai_consent_events to evidrilo_worker;
drop policy if exists evidrilo_worker_select on public.project_ai_consent_events;
create policy evidrilo_worker_select on public.project_ai_consent_events for select to evidrilo_worker using (true);
grant select on table public.project_ai_consents to evidrilo_worker;
drop policy if exists evidrilo_worker_select on public.project_ai_consents;
create policy evidrilo_worker_select on public.project_ai_consents for select to evidrilo_worker using (true);
grant select on table public.recommendation_events to evidrilo_worker;
drop policy if exists evidrilo_worker_select on public.recommendation_events;
create policy evidrilo_worker_select on public.recommendation_events for select to evidrilo_worker using (true);
grant select on table public.student_project_cloud_consent_events to evidrilo_worker;
drop policy if exists evidrilo_worker_select on public.student_project_cloud_consent_events;
create policy evidrilo_worker_select on public.student_project_cloud_consent_events for select to evidrilo_worker using (true);
grant select on table public.student_project_cloud_consents to evidrilo_worker;
drop policy if exists evidrilo_worker_select on public.student_project_cloud_consents;
create policy evidrilo_worker_select on public.student_project_cloud_consents for select to evidrilo_worker using (true);
grant select on table public.student_project_revisions to evidrilo_worker;
drop policy if exists evidrilo_worker_select on public.student_project_revisions;
create policy evidrilo_worker_select on public.student_project_revisions for select to evidrilo_worker using (true);
grant select on table public.student_projects to evidrilo_worker;
drop policy if exists evidrilo_worker_select on public.student_projects;
create policy evidrilo_worker_select on public.student_projects for select to evidrilo_worker using (true);
grant select on table public.sync_changes to evidrilo_worker;
drop policy if exists evidrilo_worker_select on public.sync_changes;
create policy evidrilo_worker_select on public.sync_changes for select to evidrilo_worker using (true);
grant select, update on table public.worker_jobs to evidrilo_worker;
drop policy if exists evidrilo_worker_select on public.worker_jobs;
create policy evidrilo_worker_select on public.worker_jobs for select to evidrilo_worker using (true);
drop policy if exists evidrilo_worker_update on public.worker_jobs;
create policy evidrilo_worker_update on public.worker_jobs for update to evidrilo_worker using (true) with check (true);
grant execute on function public.prepare_account_deletion(uuid), public.read_cohort_aggregate(uuid) to evidrilo_api;
revoke create on schema public from public;
grant update on table public.entitlements to evidrilo_api;
drop policy if exists evidrilo_api_update on public.entitlements;
create policy evidrilo_api_update on public.entitlements for update to evidrilo_api using (true) with check (true);
grant execute on function public.lock_runtime_account(uuid) to evidrilo_api;
commit;
