kotlin.code.style=official

org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=1g -Dfile.encoding=UTF-8
org.gradle.workers.max=2

# Separate compiler processes used by Kotlin Multiplatform.
kotlin.daemon.jvmargs=-Xmx4g
kotlin.native.jvmArgs=-Xmx4g

org.gradle.configuration-cache=true
android.useAndroidX=true
