package dev.nextgen.mobile

// App-owned presentation copy. Record IDs and learner content are never changed.
internal fun indonesianCopy5(): Map<String, String> = mapOf(
    "Build your comparison." to "Susun perbandingan Anda.",
    "Say what the records support." to "Nyatakan apa yang didukung catatan.",
    "How far can it reach?" to "Sejauh apa berlaku?",
    "Keep the uncertainty visible." to "Perlihatkan ketidakpastian.",
    "Choose a useful next move." to "Pilih langkah berikutnya yang berguna.",
    "Follow the evidence." to "Ikuti buktinya.",
    "A fourth card enters." to "Kartu keempat hadir.",
    "One row was counted twice." to "Satu jawaban terhitung dua kali.",
    "Review the changed evidence." to "Tinjau bukti yang berubah.",
    "Revise in your own words." to "Revisi dengan kata-kata sendiri.",
    "Reconsider the scope." to "Tinjau ulang cakupan.",
    "Revisit the limitation." to "Tinjau ulang batasan.",
    "Review your next move." to "Tinjau langkah berikutnya.",
    "Compare your reasoning." to "Bandingkan penalaran Anda.",
    "Carry the move forward." to "Bawa langkah ini ke proyek.",
    "This is a prediction, not a scored answer. You can skip it." to "Ini prediksi, bukan jawaban bernilai. Anda dapat melewatinya.",
    "Tap records to connect them to your claim. Open details when you need them." to "Sentuh catatan untuk menghubungkan dengan klaim. Buka rincian jika diperlukan.",
    "Separate a similar recall direction, a different finding, and a different outcome." to "Pisahkan arah hasil ingatan serupa, temuan berbeda, dan hasil ukur berbeda.",
    "Write one short sentence using the evidence you selected." to "Tulis satu kalimat pendek berdasarkan bukti pilihan Anda.",
    "Declare the reach of your own sentence." to "Nyatakan cakupan kalimat Anda sendiri.",
    "Choose a supplied limit and explain what remains uncertain." to "Pilih batasan tersedia dan jelaskan ketidakpastian yang tersisa.",
    "Connect your next action to the limitation you selected." to "Hubungkan langkah berikutnya dengan batasan pilihan Anda.",
    "These checks review your selected links and decisions." to "Pemeriksaan meninjau hubungan dan keputusan pilihan Anda.",
    "Commit to a decision before reading its consequence." to "Tentukan keputusan sebelum membaca akibatnya.",
    "Your initial response stays intact. You can submit this revision once." to "Jawaban awal tetap utuh. Anda dapat mengirim revisi ini sekali.",
    "Both versions and their evidence remain visible." to "Kedua versi dan buktinya tetap terlihat.",
    "Use the reasoning pattern in your own work, with your own evidence." to "Gunakan pola penalaran pada pekerjaan sendiri, dengan bukti sendiri.",
    "Start investigating" to "Mulai menyelidiki",
    "Inspect the evidence" to "Periksa bukti",
    "Review my reasoning" to "Tinjau penalaran saya",
    "See the evidence change" to "Lihat perubahan bukti",
    "Review this decision" to "Tinjau keputusan ini",
    "Review my one revision" to "Tinjau satu revisi saya",
    "Finish this attempt" to "Selesaikan percobaan ini",
    "One revision · synthetic case" to "Satu revisi · kasus rekaan",
    "Source comparison · synthetic case" to "Perbandingan sumber · kasus rekaan",
    "Survey investigation · synthetic case" to "Penyelidikan survei · kasus rekaan",
    "Tablet investigation · synthetic case" to "Penyelidikan tablet · kasus rekaan",
    "Retry saving" to "Coba simpan lagi",
    "Previous practice decision" to "Keputusan latihan sebelumnya",
    "Inspect the supplied records" to "Periksa catatan tersedia",
    "Build a bounded claim" to "Susun klaim terbatas",
    "Reconsider when evidence changes" to "Tinjau ulang saat bukti berubah",
    "Your mission" to "Misi Anda",
    "Synthetic practice material · work at your own pace" to "Materi latihan rekaan · ikuti dengan ritme sendiri",
    "You'll keep your first response, inspect one evidence change, and revise once. No case material is added to Projects." to "Pertahankan jawaban pertama, periksa satu perubahan bukti, lalu revisi sekali. Materi kasus tidak ditambahkan ke Proyek.",
    "Start a fresh attempt" to "Mulai percobaan baru",
    "Choose what you expect, or continue without choosing." to "Pilih perkiraan Anda, atau lanjutkan tanpa memilih.",
    "What do the selected records support?" to "Apa yang didukung catatan terpilih?",
    "The sentence is yours. The checks cannot assess every meaning in free text." to "Kalimat adalah tulisan Anda sendiri. Pemeriksaan tidak menilai semua makna dalam teks bebas.",
    "Your initial claim · retained" to "Klaim awal Anda · dipertahankan",
    "Next, inspect new evidence before making your one revision." to "Berikutnya, periksa bukti baru sebelum membuat satu revisi.",
    "A and B still exist. C still measures preference. This new card changes the set you need to consider." to "A dan B tetap ada. C tetap mengukur preferensi. Kartu baru ini mengubah bukti yang perlu Anda pertimbangkan.",
    "Duplicate found" to "Duplikat ditemukan",
    "R07 repeats respondent C's R03 submission. These anonymous IDs are fictional." to "R07 mengulang jawaban responden C pada R03. ID anonim ini rekaan.",
    "Compare the new finding with earlier records." to "Bandingkan temuan baru dengan catatan sebelumnya.",
    "Set aside the earlier recall findings." to "Abaikan temuan ingatan sebelumnya.",
    "Extend the result beyond these studies." to "Perluas hasil di luar studi ini.",
    "Count respondent C once." to "Hitung responden C sekali.",
    "Count one participant twice." to "Hitung satu peserta dua kali.",
    "Exclude respondent C entirely." to "Keluarkan responden C sepenuhnya.",
    "Reconsider this decision" to "Tinjau ulang keputusan ini",
    "Use this changed evidence set" to "Gunakan bukti yang berubah ini",
    "The first response keeps its original evidence version." to "Jawaban pertama mempertahankan versi bukti awalnya.",
    "Reconsider your own wording…" to "Tinjau ulang kalimat sendiri…",
    "Use this in Projects" to "Gunakan dalam Proyek",
    "Add your own sources and notes, compare outcomes and methods, then link a synthesis claim to the material that supports it." to "Tambahkan sumber dan catatan sendiri, bandingkan hasil serta metode, lalu hubungkan klaim sintesis dengan materi pendukungnya.",
    "Keep the denominator and corrected records alongside your own findings. When data changes, inspect the claims that rely on it." to "Simpan penyebut dan catatan terkoreksi bersama temuan sendiri. Saat data berubah, periksa klaim yang bergantung padanya.",
    "Try the corrected-survey case" to "Coba kasus survei terkoreksi",
    "No synthetic facts or practice wording will be copied. Completion records your attempt; it does not certify mastery." to "Fakta rekaan atau tulisan latihan tidak disalin. Penyelesaian mencatat percobaan, bukan membuktikan penguasaan.",
    "These supplied records" to "Catatan yang disediakan ini",
    "Keep the claim within these contexts and measures." to "Batasi klaim pada konteks dan pengukuran ini.",
    "All students" to "Semua pelajar",
    "Extend the claim to people outside this material." to "Perluas klaim ke orang di luar materi ini.",
    "A general causal rule" to "Aturan sebab akibat umum",
    "Declare that a cause applies beyond these records." to "Nyatakan suatu sebab berlaku di luar catatan ini.",
    "Small samples" to "Sampel kecil",
    "Different methods and outcomes" to "Metode dan hasil ukur berbeda",
    "Self-selected participation" to "Partisipasi sukarela",
    "What remains uncertain?" to "Apa yang masih belum pasti?",
    "Respond to sampling limits without promising a universal result." to "Tanggapi batas sampel tanpa menjanjikan hasil universal.",
    "Compare like outcomes and follow-up conditions." to "Bandingkan hasil ukur dan kondisi pengamatan lanjutan yang sejenis.",
    "End the inquiry without addressing its limits." to "Akhiri penyelidikan tanpa menjawab batasannya.",
    "Connect it to your selected limitation…" to "Hubungkan dengan batasan pilihan Anda…",
    "Your selected decisions fit these checks" to "Keputusan Anda sesuai pemeriksaan ini",
    "Your evidence links, declared scope, and next action fit this synthetic case's checks. Your sentence still needs your own review." to "Hubungan bukti, cakupan dinyatakan, dan langkah berikutnya sesuai pemeriksaan kasus rekaan ini. Kalimat Anda tetap perlu ditinjau sendiri.",
    "Hide the case checks" to "Sembunyikan pemeriksaan kasus",
    "Fits this check" to "Sesuai pemeriksaan ini",
    "Needs review" to "Perlu ditinjau",
    "Checks assess supplied links and choices, not the scientific truth of every word, real-world effectiveness, or academic quality." to "Pemeriksaan menilai hubungan dan pilihan tersedia, bukan kebenaran ilmiah setiap kata, efektivitas nyata, atau kualitas akademis.",
    "Before the evidence change · retained" to "Sebelum bukti berubah · dipertahankan",
    "Evidence changed" to "Bukti berubah",
    "You kept the wording. Inspect whether the changed evidence still supports it." to "Kalimat dipertahankan. Periksa apakah bukti yang berubah masih mendukungnya.",
    "You changed the wording. The first sentence remains above." to "Kalimat berubah. Kalimat pertama tetap di atas.",
    "Hide the retained records" to "Sembunyikan catatan sebelumnya",
    "Compare evidence and reasoning records" to "Bandingkan catatan bukti dan penalaran",
    "Before · retained" to "Sebelum · dipertahankan",
    "After · one revision" to "Sesudah · satu revisi",
    "No scope selected" to "Belum memilih cakupan",
    "context only" to "hanya konteks",
    "No limit selected" to "Belum memilih batasan",
    "No action selected" to "Belum memilih langkah",
    "Hide the small example" to "Sembunyikan contoh singkat",
    "Show a small worked example" to "Lihat contoh singkat",
    "Another synthetic comparison" to "Perbandingan rekaan lainnya",
    "If sample X records 12 s and sample Y 18 s, you can describe the shorter recorded time in X. Those two records alone do not establish what caused the difference." to "Jika sampel X tercatat 12 dtk dan Y 18 dtk, Anda dapat menyatakan waktu tercatat X lebih singkat. Dua catatan itu saja belum membuktikan penyebab perbedaan.",
    "A nudge, when you need it." to "Petunjuk saat diperlukan.",
    "Ask what each card measured before comparing its result." to "Periksa apa yang diukur setiap kartu sebelum membandingkan hasil.",
    "A and B measure recall at different times. C measures preference. D adds another recall finding." to "A dan B mengukur ingatan pada waktu berbeda. C mengukur preferensi. D menambahkan temuan ingatan lainnya.",
    "A and B measure recall at different times. C measures preference." to "A dan B mengukur ingatan pada waktu berbeda. C mengukur preferensi.",
    "A preference result is not a recall contradiction. A synthesis can name an observed pattern while keeping different outcomes and contexts visible." to "Hasil preferensi tidak bertentangan langsung dengan hasil ingatan. Sintesis dapat menyebut pola teramati sambil memperlihatkan perbedaan hasil ukur dan konteks.",
    "Check the count and denominator, then ask who the sample includes." to "Periksa jumlah dan penyebut, lalu siapa yang termasuk sampel.",
    "R07 repeats R03. Remove only the duplicate submission, so respondent C is counted once." to "R07 mengulang R03. Hapus hanya jawaban duplikat agar responden C dihitung sekali.",
    "The eight submissions contain five quiet-space choices and three group-space choices. Keep the denominator beside the count." to "Delapan jawaban berisi lima pilihan ruang tenang dan tiga ruang kelompok. Sertakan penyebut bersama jumlahnya.",
    "Five of eight rows becomes four of seven unique respondents. The direction remains a slight majority, but counts and strength must be reconsidered; the sample is still self-selected." to "Lima dari delapan baris menjadi empat dari tujuh responden unik. Arahnya tetap mayoritas tipis, tetapi jumlah dan kekuatan hasil perlu ditinjau; sampel tetap sukarela.",
    "A majority in these supplied submissions is not a claim about every student. The sample was small and self-selected." to "Mayoritas pada jawaban ini bukan klaim tentang semua pelajar. Sampel kecil dan sukarela.",
    "Choose measured observations, write your own bounded claim, and connect the next action to a limitation." to "Pilih pengamatan terukur, tulis klaim terbatas sendiri, dan hubungkan langkah berikutnya dengan batasan.",
    "These three cases practice observations, source comparison, and evidence correction. Open any case, pause, and return. They do not need AI or a network connection." to "Tiga kasus melatih pengamatan, perbandingan sumber, dan koreksi bukti. Buka kasus, jeda, lalu lanjutkan. AI dan internet tidak diperlukan.",
    "Show a fuller hint" to "Lihat petunjuk lengkap",
    "Try it myself" to "Coba sendiri",
    "Authored local guidance for synthetic material. This is not a response from an AI provider." to "Panduan lokal tertulis untuk materi rekaan. Ini bukan jawaban penyedia AI.",
    "Opening your workspace…" to "Membuka ruang kerja Anda…",
    "Let's recover your projects" to "Mari pulihkan proyek Anda",
    "Your next chapter starts here." to "Bab berikutnya dimulai di sini.",
    "Bring a question. Build the rest as you go." to "Bawa pertanyaan. Susun sisanya sambil berjalan.",
    "View projects" to "Lihat proyek",
    "Find your starting point" to "Temukan titik awal Anda",
    "Your current project" to "Proyek Anda saat ini",
    "Qualitative" to "Kualitatif",
    "Design" to "Desain",
    "Preview selection" to "Pilihan pratinjau",
    "Export cancelled. Your project snapshot remains saved locally; the file export did not complete." to "Ekspor dibatalkan. Keadaan proyek tetap tersimpan lokal; ekspor berkas belum selesai.",
    "The shared balance has not been loaded yet." to "Saldo bersama belum dimuat.",
    "Sign in with a verified account to view your shared AI credits." to "Masuk dengan akun terverifikasi untuk melihat kredit AI bersama.",
    "Refreshing your shared balance from Evidrilo…" to "Memuat ulang saldo bersama dari Evidrilo…",
    "Meet Evidrilo" to "Kenali Evidrilo",
    "Big ideas.\nClear next steps." to "Gagasan besar.\nLangkah jelas.",
    "Start with an assignment, a question or a hypothesis. Evidrilo helps you organize your own sources, observations and claims, then explain what your material supports and what remains uncertain. Explore the workflow with temporary examples." to "Mulai dari tugas, pertanyaan, atau hipotesis. Evidrilo membantu menata sumber, pengamatan, dan klaim sendiri, lalu menjelaskan apa yang didukung materi Anda dan apa yang belum pasti. Jelajahi alurnya dengan contoh sementara.",
    "Let's explore" to "Mari jelajahi",
    "Choose a structure" to "Pilih struktur",
    "A starting point\nthat fits your work." to "Titik awal\nyang cocok.",
    "Choose from five project structures: experiment, survey, literature, qualitative study or design. Each provides places for your own material. Browse the sections before choosing; you can also start without a template. Swipe to compare them." to "Pilih lima struktur proyek: eksperimen, survei, literatur, studi kualitatif, atau desain. Masing-masing memberi tempat untuk materi sendiri. Jelajahi bagian sebelum memilih; Anda juga dapat mulai tanpa template. Geser untuk membandingkan.",
    "One project.\nClear next steps." to "Satu proyek.\nLangkah jelas.",
    "Move between sections using the Sections panel. Add source details and files, turn useful passages into notes, and develop your claims. Your work saves locally. A suggested next task helps you find a manageable place to continue." to "Berpindah bagian lewat panel Bagian. Tambahkan rincian sumber dan berkas, ubah kutipan berguna menjadi catatan, lalu kembangkan klaim. Pekerjaan disimpan lokal. Saran tugas berikutnya membantu memilih titik lanjut yang realistis.",
    "Connect your reasoning" to "Hubungkan penalaran Anda",
    "Make the\nconnection." to "Buat\nhubungannya.",
    "A note and a claim do different jobs. Record whether the note supports, challenges or gives context to the claim, and explain why. Keep the claim within the material's scope. Try connecting the two temporary cards below." to "Catatan dan klaim memiliki peran berbeda. Catat apakah catatan mendukung, menantang, atau memberi konteks pada klaim, lalu jelaskan alasannya. Batasi klaim sesuai cakupan materi. Coba hubungkan dua kartu sementara di bawah.",
    "The project map" to "Peta proyek",
    "Your reasoning,\nvisible." to "Penalaran Anda,\nterlihat.",
    "Explore the relationships you recorded, from sources through notes to claims and next actions. Tap a record to follow its connections. Unlinked records stay visible too. The map helps you inspect your reasoning; it does not decide whether a claim is true." to "Jelajahi hubungan yang Anda catat, dari sumber, catatan, hingga klaim dan langkah berikutnya. Sentuh catatan untuk mengikuti hubungan. Catatan belum terhubung juga terlihat. Peta membantu memeriksa penalaran; tidak memutuskan kebenaran klaim.",
    "Practice before your project" to "Berlatih sebelum proyek",
    "Learn the move.\nMake it your own." to "Pelajari langkahnya.\nGunakan sendiri.",
    "Three guided cases let you inspect observations, compare studies and reconsider changed data. Make a first response, read specific feedback, then revise. The first case is Free; Pro opens the other two. Practice examples stay separate from your project." to "Tiga kasus terpandu melatih pengamatan, perbandingan studi, dan peninjauan data berubah. Buat jawaban pertama, baca umpan balik spesifik, lalu revisi. Kasus pertama Free; Pro membuka dua lainnya. Contoh latihan tetap terpisah dari proyek.",
    "Optional AI" to "AI opsional",
    "A nudge when\nyou need one." to "Bantuan saat\ndiperlukan.",
    "Sign in for optional online AI. Review the text you choose to share and its credit conditions before sending. Ask for ideas, a plan or an opinion on a saved project excerpt. You decide what to keep and check the answer yourself." to "Masuk untuk AI daring opsional. Tinjau teks pilihan yang dibagikan dan ketentuan kredit sebelum mengirim. Minta gagasan, rencana, atau pendapat tentang cuplikan proyek tersimpan. Anda menentukan yang dipakai dan memeriksa jawaban sendiri.",
    "Review and take your work" to "Tinjau dan bawa pekerjaan Anda",
    "Keep it.\nShape it. Share it." to "Simpan.\nSusun. Bagikan.",
    "Review checks show recorded responses and links, with a practical next action. They are not an academic grade. Preview a report before export, or keep an .evproj backup for recovery. The project menu also lets you complete or permanently delete work with confirmation." to "Pemeriksaan tinjauan menunjukkan jawaban dan hubungan tercatat, disertai langkah praktis. Ini bukan nilai akademis. Pratinjau laporan sebelum ekspor, atau simpan cadangan .evproj. Menu proyek juga memungkinkan menandai selesai atau menghapus permanen dengan konfirmasi.",
    "Your next step" to "Langkah berikutnya",
    "Your question.\nYour next chapter." to "Pertanyaan Anda.\nBab berikutnya.",
    "Choose a structure and begin with your own assignment. Free keeps five projects total; Pro keeps fifty and adds 200 AI credits each active month. A verified Free account receives 20 credits once. You can keep working locally and revisit this introduction from Settings." to "Pilih struktur dan mulai dengan tugas sendiri. Free menyimpan total lima proyek; Pro lima puluh dan menambah 200 kredit AI setiap bulan aktif. Akun Free terverifikasi mendapat 20 kredit sekali. Tetap bekerja lokal dan ulangi pengantar dari Pengaturan.",
    "Choose project structure" to "Pilih struktur proyek",
    "Literature synthesis" to "Sintesis literatur",
    "Research question" to "Pertanyaan penelitian",
    "Reading notes" to "Catatan bacaan",
    "Themes & claims" to "Tema dan klaim",
    "Observation / survey" to "Pengamatan / survei",
    "Question & scope" to "Pertanyaan dan cakupan",
    "Observations" to "Pengamatan",
    "Findings & limits" to "Temuan dan batasan",
    "Lab experiment" to "Eksperimen laboratorium",
    "Question & variables" to "Pertanyaan dan variabel",
    "Trial records" to "Catatan percobaan",
    "Interpretation & limits" to "Interpretasi dan batasan",
    "Qualitative inquiry" to "Penyelidikan kualitatif",
    "Study focus" to "Fokus studi",
    "Coded notes" to "Catatan berkode",
    "Themes & boundaries" to "Tema dan batasan",
    "Design / engineering" to "Desain / rekayasa",
)
