package dev.nextgen.mobile

// App-owned presentation copy. Record IDs and learner content are never changed.
internal fun indonesianCopy10(): Map<String, String> = mapOf(
    "This legacy template can still be inspected, but its examples are not classified and reviewed for both normal and edge scenarios. It cannot start a new project or an AI scaffold." to "Template lama dapat diperiksa, tetapi contohnya belum diklasifikasi dan ditinjau untuk skenario normal serta batas. Tidak dapat memulai proyek atau draf AI.",
    "Create a blank project instead" to "Buat proyek kosong saja",
    "Intended output" to "Hasil yang dituju",
    "Publication indicates the server's release checks passed; it does not establish that this method fits your assignment. Confirm uncertain choices with your instructor or a relevant reviewer." to "Publikasi menandakan pemeriksaan rilis server terpenuhi; tidak membuktikan metode cocok untuk tugas. Konfirmasikan pilihan tidak pasti dengan pengajar atau peninjau.",
    "Inputs" to "Masukan",
    "Steps" to "Langkah",
    "Method-specific limitations" to "Batasan khusus metode",
    "Provenance to record" to "Asal sumber yang dicatat",
    "Accessibility expectations" to "Kebutuhan aksesibilitas",
    "Example review metadata" to "Metadata tinjauan contoh",
    "Starting a project" to "Memulai proyek",
    "Inspecting a legacy template" to "Memeriksa template lama",
    "Manual start creates a local draft from this exact template version. Your draft stays on this device; it is not uploaded, synced, or graded." to "Mulai manual membuat draf lokal dari versi template ini. Draf tetap di perangkat; tidak diunggah, disinkronkan, atau dinilai.",
    "This published version is preserved for reading existing work. Its scenario-review metadata is incomplete for creating new work." to "Versi terbit ini dipertahankan untuk membaca pekerjaan lama. Metadata tinjauan skenario belum lengkap untuk pekerjaan baru.",
    "Scenario type not recorded in this legacy template" to "Jenis skenario belum dicatat pada template lama ini",
    "Normal workflow (not a correctness label)" to "Alur normal (bukan label kebenaran)",
    "Edge or conflicting scenario" to "Skenario batas atau berkonflik",
    "Checking published templates…" to "Memeriksa template terbit…",
    "Published templates unavailable" to "Template terbit tidak tersedia",
    "Published templates could not be verified" to "Template terbit gagal diverifikasi",
    "The overview above remains available. No template has been assumed available." to "Ringkasan di atas tetap tersedia. Ketersediaan template tidak diasumsikan.",
    "No published templates yet" to "Belum ada template terbit",
    "The offline starter above can create a local project. No remote published template is available to inspect yet." to "Panduan luring di atas dapat membuat proyek lokal. Belum ada template daring untuk diperiksa.",
    "Published templates" to "Template terbit",
    "Inspect template details  ›" to "Periksa rincian template  ›",
    "Offline · five starters available" to "Luring · lima panduan tersedia",
    "Five offline starters available" to "Lima panduan luring tersedia",
    "Couldn’t check templates" to "Template gagal diperiksa",
    "Offline family starters and overviews remain available. No remote template has been assumed available." to "Panduan jenis proyek luring tetap tersedia. Template daring tidak diasumsikan tersedia.",
    "Each family has an offline project starter. Start blank if you prefer." to "Setiap jenis memiliki panduan proyek luring. Mulai kosong jika diinginkan.",
    "Select a type to view them." to "Pilih jenis untuk melihatnya.",
    "Online templates are not configured in this build. The project-type guidance remains available offline." to "Template daring belum dikonfigurasi. Panduan jenis proyek tetap tersedia luring.",
    "You are offline. The project-type guidance remains available; retry when connected." to "Anda luring. Panduan jenis proyek tetap tersedia; coba lagi setelah terhubung.",
    "Not sure which type?" to "Belum yakin jenisnya?",
    "Hide" to "Sembunyikan",
    "Help me choose" to "Bantu saya memilih",
    "monthly" to "bulanan",
    "yearly" to "tahunan",
    "Checking premium access" to "Memeriksa akses Pro",
    "Explore Evidrilo Pro" to "Jelajahi Evidrilo Pro",
    "Choose Monthly or Annually" to "Pilih Bulanan atau Tahunan",
    "Premium plans are unavailable" to "Paket Pro tidak tersedia",
    "Purchase needs attention" to "Pembelian perlu diperiksa",
    "Purchase is being reconciled" to "Pembelian sedang diselaraskan",
    "Purchase state needs reconciliation" to "Status pembelian perlu diselaraskan",
    "Premium evidence cases are unlocked" to "Kasus bukti Pro terbuka",
    "The signed-in Free evidence workflow remains available offline without a subscription." to "Alur bukti Free yang masuk tetap tersedia luring tanpa langganan.",
    "USD 1.99" to "USD 1.99",
    "per month" to "per bulan",
    "month" to "bulan",
    "USD 19.99" to "USD 19.99",
    "per year" to "per tahun",
    "year" to "tahun",
    "Billing is not configured on this build." to "Pembayaran belum dikonfigurasi dalam versi ini.",
    "Evidrilo Pro is disabled in this build." to "Evidrilo Pro dinonaktifkan dalam versi ini.",
    "Checking premium access…" to "Memeriksa akses Pro…",
    "Premium offers are unavailable right now." to "Penawaran Pro belum tersedia saat ini.",
    "Premium evidence cases are available." to "Kasus bukti Pro tersedia.",
    "Premium evidence cases unlocked." to "Kasus bukti Pro terbuka.",
    "Premium access is not active on this customer." to "Akses Pro belum aktif untuk pelanggan ini.",
    "Premium access is unavailable right now." to "Akses Pro belum tersedia saat ini.",
    "Purchase cancelled; the free workflow remains available." to "Pembelian dibatalkan; alur gratis tetap tersedia.",
    "Purchase is still being reconciled." to "Pembelian masih diselaraskan.",
    "Purchase state needs reconciliation." to "Status pembelian perlu diselaraskan.",
    "Subscription status" to "Status langganan",
    "Checking provider access…" to "Memeriksa akses penyedia…",
    "Processing purchase…" to "Memproses pembelian…",
    "Your store confirms the price before purchase. Subscriptions renew automatically each month or year unless cancelled through your store. Both plans add 200 AI credits per active month." to "Toko mengonfirmasi harga sebelum membeli. Langganan diperpanjang otomatis bulanan/tahunan kecuali dibatalkan melalui toko. Kedua paket menambah 200 kredit AI setiap bulan aktif.",
    "Restoring purchase…" to "Memulihkan pembelian…",
    "Restore purchase" to "Pulihkan pembelian",
    "Choose another plan" to "Pilih paket lain",
    "View subscription plans" to "Lihat paket langganan",
    "The first synthetic Practice case is Free. Pro opens all three. Purchases and access follow your account's subscription status." to "Kasus latihan rekaan pertama Free. Pro membuka ketiganya. Pembelian dan akses mengikuti status langganan akun.",
    "Selected subscription" to "Langganan terpilih",
    "Select this subscription" to "Pilih langganan ini",
    "Plans available" to "Paket tersedia",
    "Plans unavailable" to "Paket tidak tersedia",
    "Needs reconciliation" to "Perlu diselaraskan",
    "Listen" to "Dengarkan",
    "Listen to this content" to "Dengarkan materi ini",
    "Audio ready" to "Audio siap",
    "Loading audio…" to "Memuat audio…",
    "Audio is loading" to "Audio sedang dimuat",
    "Pause" to "Jeda",
    "Pause audio" to "Jeda audio",
    "Playing" to "Sedang diputar",
    "Resume" to "Lanjutkan",
    "Resume audio" to "Lanjutkan audio",
    "Paused" to "Dijeda",
    "Replay" to "Ulangi",
    "Replay audio" to "Putar ulang audio",
    "Audio is unavailable; read the visible text" to "Audio tidak tersedia; baca teks di layar",
    "Audio unavailable; visible text remains available" to "Audio tidak tersedia; teks tetap tersedia",
    "Try audio again" to "Coba audio lagi",
    "Try audio again; read the visible text if it remains unavailable" to "Coba audio lagi; baca teks jika tetap tidak tersedia",
    "Audio failed; visible text remains available" to "Audio gagal; teks tetap tersedia",
    "Stop audio" to "Hentikan audio",
    "Audio can be stopped" to "Audio dapat dihentikan",
    "Stop" to "Hentikan",
    "Evidence guide." to "Panduan bukti.",
    "See what the case supports." to "Lihat yang didukung kasus.",
    "These checks are bounded to the supplied facts." to "Pemeriksaan terbatas pada fakta tersedia.",
    "They are not a grade or a claim that the real-world experiment is scientifically complete." to "Ini bukan nilai atau klaim bahwa eksperimen nyata lengkap secara ilmiah.",
    "Review the feedback and its fact anchors before making your one revision." to "Tinjau umpan balik dan rujukan fakta sebelum membuat satu revisi.",
    "Revise once with the feedback." to "Revisi sekali dengan umpan balik.",
    "Use the feedback reason to make one learner-authored revision." to "Gunakan alasan umpan balik untuk satu revisi tulisan sendiri.",
    "The original draft remains available for comparison." to "Draf awal tetap tersedia untuk dibandingkan.",
    "Evidence-change challenge." to "Tantangan perubahan bukti.",
    "The cold-water observation is unavailable in this round." to "Pengamatan air dingin tidak tersedia pada tahap ini.",
    "Re-evaluate the conclusion using only the observations still supplied." to "Nilai ulang kesimpulan memakai hanya pengamatan yang masih tersedia.",
    "There is no second revision in this round." to "Tidak ada revisi kedua pada tahap ini.",
    "Support and billing." to "Dukungan dan pembayaran.",
    "Restore a purchase from Premium; the store account is the source of truth for a completed transaction." to "Pulihkan pembelian dari Pro; akun toko menjadi acuan transaksi selesai.",
    "Manage or cancel a subscription through the relevant app store or Customer Center when available." to "Kelola atau batalkan langganan melalui toko aplikasi terkait atau Pusat Pelanggan jika tersedia.",
    "Refund requests must be made through the store that processed the purchase." to "Ajukan pengembalian dana melalui toko pemroses pembelian.",
    "Free drafts remain local, and account deletion is separate from clearing local workflow history." to "Draf Free tetap lokal; penghapusan akun terpisah dari penghapusan riwayat alur lokal.",
    "This feature is paused" to "Fitur ini dijeda",
    "Continue to local projects" to "Lanjutkan ke proyek lokal",
    "Sign-in unavailable" to "Masuk tidak tersedia",
    "Sign in to access Evidrilo Pro" to "Masuk untuk mengakses Evidrilo Pro",
    "Sign in for this feature" to "Masuk untuk fitur ini",
    "Pro requires an account and a confirmed RevenueCat entitlement. Your free projects and case work remain available locally without signing in." to "Pro membutuhkan akun dan akses RevenueCat terkonfirmasi. Proyek gratis serta kasus tetap tersedia lokal tanpa masuk.",
    "Online AI and account-linked Pro need an account. Local projects, evidence work and Free practice remain available without signing in." to "AI daring dan Pro terkait akun memerlukan akun. Proyek lokal, pekerjaan bukti, dan latihan Free tersedia tanpa masuk.",
    "Account access is not available in this build. You can keep working with local projects or contact support." to "Akses akun tidak tersedia dalam versi ini. Lanjutkan dengan proyek lokal atau hubungi dukungan.",
    "Sign in to continue" to "Masuk untuk melanjutkan",
    "Sign in or create a free account" to "Masuk atau buat akun gratis",
    "Signing in does not upload projects or turn on cloud sync." to "Masuk tidak mengunggah proyek atau mengaktifkan sinkronisasi awan.",
    "Back" to "Kembali",
    "Checking saved account" to "Memeriksa akun tersimpan",
    "Your local projects remain available. We are securely checking whether this device already has an account session." to "Proyek lokal tetap tersedia. Kami memeriksa aman apakah perangkat sudah memiliki sesi akun.",
    "Sign in for AI & Pro." to "Masuk untuk AI dan Pro.",
    "Browser sign-in is waiting" to "Menunggu masuk lewat browser",
    "Finish sign-in in your browser, then return to Evidrilo." to "Selesaikan masuk di browser, lalu kembali ke Evidrilo.",
    "Use email sign-in instead" to "Gunakan email saja",
    "Continue with Apple" to "Lanjutkan dengan Apple",
    "Or use email" to "Atau gunakan email",
    "Sign-in methods" to "Metode masuk",
    "Have an account already? Sign in with that method, then link Google or Apple from Account. Accounts are never merged." to "Sudah punya akun? Masuk dengan metode tersebut, lalu hubungkan Google atau Apple dari Akun. Akun tidak digabungkan.",
    "Online features" to "Fitur daring",
    "AI needs internet, a verified account, consent, credits and an available service. Pro requires confirmed access. Signing in never uploads your projects. Local projects and Free practice work without an account." to "AI membutuhkan internet, akun terverifikasi, persetujuan, kredit, dan layanan tersedia. Pro memerlukan akses terkonfirmasi. Masuk tidak mengunggah proyek. Proyek lokal dan latihan Free berfungsi tanpa akun.",
    "Keep working locally" to "Tetap bekerja lokal",
    "Delete account data?" to "Hapus data akun?",
    "This removes or anonymizes data stored by Evidrilo and signs you out. It does not delete local projects or your Google/email account; those must be removed separately." to "Data Evidrilo dihapus atau dianonimkan, lalu Anda keluar. Proyek lokal dan akun Google/email tidak dihapus; hapus terpisah jika diperlukan.",
    "Link Apple to this account?" to "Hubungkan Apple ke akun ini?",
    "Confirm you are signed into the Evidrilo account you want to keep." to "Pastikan Anda masuk ke akun Evidrilo yang ingin dipertahankan.",
    "The saved session does not include an email address. Apple will be linked to the currently signed-in Evidrilo account." to "Sesi tersimpan tidak memiliki alamat email. Apple dihubungkan ke akun Evidrilo saat ini.",
    "Apple may provide a private relay address. It will not be used to choose or switch Evidrilo accounts." to "Apple mungkin memberi alamat relay privat. Tidak dipakai memilih atau mengganti akun Evidrilo.",
    "Continue to Apple" to "Lanjutkan ke Apple",
    "Select and copy this JSON if you need a portable record. Local drafts are not included because they remain on this device." to "Pilih dan salin JSON untuk catatan portabel. Draf lokal tidak disertakan karena tetap di perangkat.",
    "Email address" to "Alamat email",
    "Confirm password" to "Konfirmasi kata sandi",
    "I already have an account" to "Saya sudah punya akun",
    "We will show the same confirmation whether or not the address belongs to an account." to "Konfirmasi yang sama ditampilkan baik alamat terdaftar maupun tidak.",
    "Send reset link" to "Kirim tautan reset",
    "Sign in instead" to "Masuk saja",
    "New password" to "Kata sandi baru",
    "Confirm new password" to "Konfirmasi kata sandi baru",
    "Save new password" to "Simpan kata sandi baru",
    "Show" to "Tampilkan",
    "You are signed in" to "Anda sudah masuk",
    "Your account can be used for online AI and Pro, subject to service and access checks. Projects stay on this device; signing in does not upload them." to "Akun dapat dipakai untuk AI daring dan Pro sesuai pemeriksaan layanan serta akses. Proyek tetap di perangkat; masuk tidak mengunggahnya.",
    "Google sign-in" to "Masuk dengan Google",
    "Google is linked to this account. Your Evidrilo account and data stay under the same account ID." to "Google terhubung dengan akun ini. Akun dan data Evidrilo tetap memakai ID yang sama.",
    "Finish linking in your browser, then return here. This account remains active while you do that." to "Selesaikan penghubungan di browser, lalu kembali. Akun tetap aktif selama proses.",
    "Google linking did not complete. Your current session remains active; if you approved Google, try again to refresh the link status." to "Google gagal dihubungkan. Sesi tetap aktif; jika sudah menyetujui Google, coba lagi untuk memuat ulang status.",
    "This Google identity is already associated with an account. No accounts were merged or switched." to "Identitas Google sudah terkait akun lain. Akun tidak digabungkan atau diganti.",
    "Google identity linking is not enabled for this Supabase project. Your current account remains unchanged." to "Penghubungan Google belum aktif untuk proyek autentikasi ini. Akun saat ini tidak berubah.",
    "We could not verify the link result. Your existing session was preserved; try again to check the Google status." to "Hasil penghubungan belum terverifikasi. Sesi dipertahankan; coba periksa status Google lagi.",
    "Google is not linked yet. Linking adds Google sign-in to this account without creating or merging accounts." to "Google belum terhubung. Penghubungan menambah metode masuk pada akun ini tanpa membuat atau menggabungkan akun.",
    "The Google link status will be checked before linking. This will not replace your current account." to "Status Google diperiksa sebelum penghubungan. Akun saat ini tidak diganti.",
    "Cancel Google linking" to "Batalkan penghubungan Google",
    "Link Google to this account" to "Hubungkan Google ke akun ini",
    "Apple sign-in" to "Masuk dengan Apple",
    "Apple is linked to this same Evidrilo account. Its relay email, if used, does not replace the verified account email above." to "Apple terhubung pada akun Evidrilo yang sama. Email relay tidak mengganti email akun terverifikasi di atas.",
    "Finish linking in your browser, then return here. Your current Evidrilo account stays active." to "Selesaikan penghubungan di browser, lalu kembali. Akun Evidrilo tetap aktif.",
    "Apple linking did not complete. Your current account remains active; you can retry when ready." to "Apple gagal dihubungkan. Akun tetap aktif; coba lagi saat siap.",
    "This Apple identity is already associated with an account. No accounts were merged or switched. Sign in to that account before linking." to "Identitas Apple sudah terkait akun lain. Akun tidak digabungkan atau diganti. Masuk ke akun tersebut sebelum menghubungkan.",
    "Apple identity linking is not enabled for this auth project. Your current account remains unchanged." to "Penghubungan Apple belum aktif untuk proyek autentikasi ini. Akun tidak berubah.",
    "We could not verify the Apple link. Your existing account and email were preserved." to "Hubungan Apple belum terverifikasi. Akun dan email dipertahankan.",
    "Link Apple as another sign-in method for this same Evidrilo account. Linking never merges accounts." to "Hubungkan Apple sebagai metode masuk lain untuk akun Evidrilo yang sama. Akun tidak digabungkan.",
)
