package dev.nextgen.mobile

// App-owned presentation copy. Record IDs and learner content are never changed.
internal fun indonesianCopy3(): Map<String, String> = mapOf(
    "Student canceled file addition" to "Penambahan berkas dibatalkan pengguna",
    "Adding project file" to "Menambahkan berkas proyek",
    "Saving this file privately. Canceling before the local revision is committed leaves the saved project unchanged." to "Menyimpan berkas secara privat. Pembatalan sebelum revisi lokal ditetapkan mempertahankan proyek tersimpan.",
    "Cancel file addition" to "Batalkan penambahan berkas",
    "Unsaved project changes" to "Perubahan proyek belum tersimpan",
    "Save your changes before leaving, or discard them? The last saved local draft will remain available." to "Simpan atau buang perubahan sebelum keluar? Draf lokal terakhir tetap tersedia.",
    "Save and leave" to "Simpan dan keluar",
    "Discard" to "Buang perubahan",
    "Stay" to "Tetap di sini",
    "Choose a non-empty supported file no larger than 20 MB. No file was attached." to "Pilih berkas didukung yang tidak kosong, maksimal 20 MB. Berkas belum dilampirkan.",
    "Choose a PDF, DOCX, CSV, TXT, Markdown, PNG, or JPEG file. No file was attached." to "Pilih berkas PDF, DOCX, CSV, TXT, Markdown, PNG, atau JPEG. Berkas belum dilampirkan.",
    "The file content did not match its supported file type. No file was attached." to "Isi berkas tidak sesuai jenisnya. Berkas belum dilampirkan.",
    "The file name or metadata is not safe to store. Rename it and try again." to "Nama atau metadata berkas tidak aman disimpan. Ubah nama lalu coba lagi.",
    "This project already has 50 attachments. No file was attached." to "Proyek sudah memiliki 50 lampiran. Berkas belum dilampirkan.",
    "Project metadata was not updated, but file cleanup could not be confirmed. Check this device's storage before retrying." to "Metadata proyek belum diperbarui, tetapi pembersihan berkas belum terkonfirmasi. Periksa penyimpanan sebelum mencoba lagi.",
    "This file is no longer attached to the current project. Earlier revisions, if any, were not changed." to "Berkas tidak lagi dilampirkan pada proyek saat ini. Revisi terdahulu tidak berubah.",
    "The file could not be safely removed. It remains protected while storage recovery is retried." to "Berkas gagal dihapus aman dan tetap dilindungi sambil pemulihan penyimpanan dicoba kembali.",
    "Project storage is full. The file is still attached because its removal was not saved." to "Penyimpanan proyek penuh. Berkas masih dilampirkan karena penghapusan belum disimpan.",
    "The selected file could not be added. Existing project data was left unchanged." to "Berkas terpilih gagal ditambahkan. Data proyek saat ini tidak berubah.",
    "The file could not be safely removed. The current project and saved revisions were left unchanged." to "Berkas gagal dihapus aman. Proyek dan revisi tersimpan tidak berubah.",
    "Add your own notes." to "Tambahkan catatan sendiri.",
    "Required response" to "Jawaban wajib",
    "Optional response" to "Jawaban opsional",
    "Writing hint" to "Petunjuk menulis",
    "New source" to "Sumber baru",
    "DOI or URL (entered by you)" to "DOI atau URL (Anda masukkan sendiri)",
    "Selection decision" to "Keputusan pemilihan",
    "Why was it excluded?" to "Mengapa tidak disertakan?",
    "Extraction notes · record only what the source reports" to "Catatan ekstraksi · catat hanya yang dilaporkan sumber",
    "Aim or purpose" to "Tujuan",
    "Context or population" to "Konteks atau populasi",
    "Reported findings" to "Temuan dilaporkan",
    "Reported limitations" to "Batasan dilaporkan",
    "I checked this source myself; Evidrilo has not verified it." to "Saya memeriksa sendiri sumber ini; Evidrilo belum memverifikasinya.",
    "Add evidence note from this source" to "Tambah catatan bukti dari sumber ini",
    "Remove source" to "Hapus sumber",
    "Remove this source?" to "Hapus sumber ini?",
    "Could not save this removal. The source and its links are unchanged; retry or keep it." to "Penghapusan gagal disimpan. Sumber dan hubungannya tidak berubah; coba lagi atau pertahankan.",
    "Keep source" to "Pertahankan sumber",
    "New evidence note" to "Catatan bukti baru",
    "Your excerpt or paraphrase" to "Kutipan atau parafrasa Anda",
    "Page, section, table, or location (optional)" to "Halaman, bagian, tabel, atau lokasi (opsional)",
    "I checked this note against the source." to "Saya mencocokkan catatan ini dengan sumber.",
    "Remove evidence note" to "Hapus catatan bukti",
    "Remove this evidence note?" to "Hapus catatan bukti ini?",
    "Could not save this removal. The evidence note and its links are unchanged; retry or keep it." to "Penghapusan gagal disimpan. Catatan dan hubungannya tidak berubah; coba lagi atau pertahankan.",
    "Remove note" to "Hapus catatan",
    "Keep note" to "Pertahankan catatan",
    "New finding" to "Temuan baru",
    "Finding · evidence links inside" to "Temuan · hubungan bukti di dalam",
    "Your finding or synthesis statement" to "Pernyataan temuan atau sintesis Anda",
    "Scope or context" to "Cakupan atau konteks",
    "Uncertainty or variation" to "Ketidakpastian atau variasi",
    "Evidence relationship to this finding" to "Hubungan bukti dengan temuan ini",
    "Remove finding" to "Hapus temuan",
    "New claim" to "Klaim baru",
    "Claim statement" to "Pernyataan klaim",
    "What bounded statement are you making?" to "Pernyataan terbatas apa yang Anda buat?",
    "Where, for whom, or under what conditions does it apply?" to "Di mana, untuk siapa, atau dalam kondisi apa pernyataan berlaku?",
    "Limitations for this claim" to "Batasan klaim ini",
    "What should a reader not infer from it?" to "Apa yang tidak boleh disimpulkan pembaca?",
    "Student review state" to "Status tinjauan pelajar",
    "This is your workflow marker, not a pass/fail or academic assessment." to "Ini penanda alur Anda, bukan lulus/gagal atau penilaian akademis.",
    "Evidence relationship to this claim" to "Hubungan bukti dengan klaim ini",
    "Remove claim" to "Hapus klaim",
    "New limitation or next action" to "Batasan atau langkah baru",
    "Boundary and next action" to "Batasan dan langkah berikutnya",
    "Boundary or limitation" to "Batasan",
    "What does this project not establish?" to "Apa yang belum dapat dibuktikan proyek ini?",
    "Why it matters" to "Mengapa penting",
    "What is the reason for this boundary?" to "Apa alasan batasan ini?",
    "What could you check or do next?" to "Apa yang dapat diperiksa atau dilakukan berikutnya?",
    "Affected findings · optional links" to "Temuan terdampak · hubungan opsional",
    "No findings are available to link yet." to "Belum ada temuan yang dapat dihubungkan.",
    "Untitled finding" to "Temuan tanpa judul",
    "Affected claims · optional links" to "Klaim terdampak · hubungan opsional",
    "No claims are available to link yet." to "Belum ada klaim yang dapat dihubungkan.",
    "Untitled claim" to "Klaim tanpa judul",
    "Remove limitation/action" to "Hapus batasan/langkah",
    "Choose a relationship for each note. These are your working links, not an automatic verification." to "Pilih hubungan untuk setiap catatan. Ini hubungan kerja Anda, bukan verifikasi otomatis.",
    "Add a source and an evidence note first." to "Tambahkan sumber dan catatan bukti terlebih dahulu.",
    "Draft" to "Draf",
    "Ready to review" to "Siap ditinjau",
    "New synthesis theme" to "Tema sintesis baru",
    "Theme label" to "Nama tema",
    "Your synthesis" to "Sintesis Anda",
    "Sources you used for this theme" to "Sumber yang digunakan untuk tema ini",
    "Differences, conflicts, or variation" to "Perbedaan, pertentangan, atau variasi",
    "Remove theme" to "Hapus tema",
    "Not added yet." to "Belum ditambahkan.",
    "Project overview" to "Ringkasan proyek",
    "Starting point" to "Titik awal",
    "Your own task" to "Tugas Anda sendiri",
    "Project status" to "Status proyek",
    "Optional deadline" to "Tenggat opsional",
    "Saved revision" to "Revisi tersimpan",
    "This review records what is in the local draft. It is not an academic grade or a verification of research quality." to "Tinjauan mencatat isi draf lokal. Ini bukan nilai akademis atau verifikasi kualitas penelitian.",
    "Project details" to "Rincian proyek",
    "No sources have been recorded." to "Belum ada sumber tercatat.",
    "DOI or URL" to "DOI atau URL",
    "Exclusion reason" to "Alasan tidak disertakan",
    "Reported aim or purpose" to "Tujuan dilaporkan",
    "Reported context or population" to "Konteks atau populasi dilaporkan",
    "Reported method" to "Metode dilaporkan",
    "No files are attached." to "Belum ada berkas dilampirkan.",
    "File" to "Berkas",
    "Size and type" to "Ukuran dan jenis",
    "These excerpts or notes were entered by you. Their presence does not mean Evidrilo has verified the source or interpretation." to "Kutipan atau catatan ini Anda masukkan sendiri. Keberadaannya tidak berarti Evidrilo memverifikasi sumber atau interpretasi.",
    "No evidence notes have been recorded." to "Belum ada catatan bukti tercatat.",
    "Source no longer in this project" to "Sumber tidak lagi dalam proyek ini",
    "Findings and synthesis" to "Temuan dan sintesis",
    "No findings have been recorded." to "Belum ada temuan tercatat.",
    "Evidence relationships recorded by you" to "Hubungan bukti yang Anda catat",
    "No evidence link recorded" to "Belum ada hubungan bukti tercatat",
    "Your reason for this relationship" to "Alasan hubungan ini",
    "Cross-source comparison notes" to "Catatan perbandingan antarsumber",
    "Note" to "Catatan",
    "Variation or disagreement you recorded" to "Variasi atau perbedaan pendapat yang Anda catat",
    "Sources linked by you" to "Sumber yang Anda hubungkan",
    "None" to "Tidak ada",
    "The relationships below are choices recorded by you. Evidrilo has not determined whether a claim is true or supported." to "Hubungan di bawah adalah pilihan yang Anda catat. Evidrilo belum menentukan apakah klaim benar atau didukung.",
    "Sources associated with the project" to "Sumber terkait proyek",
    "No claims have been recorded." to "Belum ada klaim tercatat.",
    "Limitations noted for this claim" to "Batasan tercatat untuk klaim ini",
    "Your workflow marker" to "Penanda alur Anda",
    "No structured limitation or next action has been recorded." to "Belum ada batasan atau langkah terstruktur tercatat.",
    "Findings linked by you" to "Temuan yang Anda hubungkan",
    "Claims linked by you" to "Klaim yang Anda hubungkan",
    "Revision history" to "Riwayat revisi",
    "Restoring a checkpoint creates a new revision and keeps later history. Checkpoints do not grade research quality." to "Memulihkan titik simpan membuat revisi baru dan mempertahankan riwayat setelahnya. Titik simpan tidak menilai kualitas penelitian.",
    "Revision history is bounded; the initial and recent checkpoints are retained." to "Riwayat revisi dibatasi; titik simpan awal dan terkini dipertahankan.",
    "No named checkpoints are available yet." to "Belum ada titik simpan bernama.",
    "A checkpoint saves the current project state. It does not validate a claim or establish research quality." to "Titik simpan menyimpan keadaan proyek. Ini tidak memvalidasi klaim atau kualitas penelitian.",
    "Structure check" to "Pemeriksaan struktur",
    "Some links or sections still need attention." to "Sebagian hubungan atau bagian perlu diperhatikan.",
    "The currently defined structure checks are clear." to "Pemeriksaan struktur yang ditentukan saat ini terpenuhi.",
    "This is not a grade and does not assess source quality, method quality, or whether a claim is true." to "Ini bukan nilai dan tidak menilai kualitas sumber, metode, atau kebenaran klaim.",
    "An untitled source" to "Sumber tanpa judul",
    "A comparison note" to "Catatan perbandingan",
    "• One or more project-level source links point to sources no longer in this project" to "• Ada hubungan sumber tingkat proyek yang merujuk sumber di luar proyek",
    "its recorded source" to "sumber yang dicatat",
    "An untitled finding" to "Temuan tanpa judul",
    "A claim" to "Klaim",
    "To review" to "Perlu ditinjau",
    "Excluded" to "Tidak disertakan",
    "What does the assignment ask?" to "Apa yang diminta dalam tugas?",
    "What question are you investigating?" to "Pertanyaan apa yang Anda selidiki?",
    "What do you predict, and why?" to "Apa prediksi Anda, dan mengapa?",
    "Which source and details matter?" to "Sumber dan rincian apa yang penting?",
    "What data or observations do you have?" to "Data atau pengamatan apa yang Anda miliki?",
    "How are you examining the information?" to "Bagaimana Anda memeriksa informasi?",
    "What can you currently say?" to "Apa yang dapat Anda nyatakan saat ini?",
    "What limits the interpretation?" to "Apa yang membatasi interpretasi?",
    "What should be checked or done next?" to "Apa yang perlu diperiksa atau dilakukan berikutnya?",
    "Paste or summarize the relevant instructions." to "Tempel atau ringkas instruksi yang relevan.",
    "Keep the question focused and aligned with the task." to "Jaga pertanyaan tetap terarah dan sesuai tugas.",
    "A hypothesis is a prediction to examine, not a guaranteed result." to "Hipotesis adalah prediksi untuk diperiksa, bukan hasil yang dijamin.",
    "Record provenance so you can find and assess the source again." to "Catat asal sumber agar dapat ditemukan dan diperiksa kembali.",
    "Record what was observed, including context and missing data." to "Catat apa yang diamati, termasuk konteks dan data yang tidak tersedia.",
    "Describe the method you actually used." to "Jelaskan metode yang benar-benar Anda pakai.",
    "Keep the statement within the scope of the information available." to "Batasi pernyataan sesuai informasi tersedia.",
    "Note uncertainty, method constraints, and alternative explanations." to "Catat ketidakpastian, batas metode, dan penjelasan alternatif.",
    "Choose a practical check that fits your task and constraints." to "Pilih pemeriksaan praktis sesuai tugas dan batasan.",
    "Incomplete" to "Belum lengkap",
    "Action needed" to "Perlu ditindaklanjuti",
    "Pass" to "Terpenuhi",
    "Cannot assess from the supplied information" to "Belum dapat dinilai dari informasi tersedia",
    "Checking access" to "Memeriksa akses",
    "Premium locked" to "Pro terkunci",
    "Offer available" to "Penawaran tersedia",
    "Premium unlocked" to "Pro terbuka",
    "Offer unavailable" to "Penawaran tidak tersedia",
    "Purchase cancelled" to "Pembelian dibatalkan",
    "Purchase failed" to "Pembelian gagal",
    "Purchase pending" to "Pembelian tertunda",
    "Purchase needs reconciliation" to "Pembelian perlu direkonsiliasi",
    "Goal connection" to "Kesesuaian tujuan",
    "Evidence anchoring" to "Rujukan bukti",
    "Scope and uncertainty" to "Cakupan dan ketidakpastian",
    "Actionable implication" to "Implikasi praktis",
)
