package dev.nextgen.mobile

// App-owned presentation copy. Record IDs and learner content are never changed.
internal fun indonesianCopy2(): Map<String, String> = mapOf(
    "Discard AI suggestion" to "Buang saran AI",
    "Editable suggestion" to "Saran dapat diedit",
    "Suggested next questions" to "Pertanyaan lanjutan yang disarankan",
    "Create project from selected suggestions" to "Buat proyek dari saran terpilih",
    "Apply selected suggestions" to "Terapkan saran terpilih",
    "Selected suggestions were saved locally; AI-credit confirmation is in progress." to "Saran terpilih disimpan lokal; konfirmasi kredit AI sedang diproses.",
    "Suggestions were not applied. Your project remains unchanged." to "Saran belum diterapkan. Proyek tidak berubah.",
    "Archive project" to "Arsipkan proyek",
    "Move to Trash" to "Pindahkan ke Sampah",
    "Restore to active" to "Pulihkan sebagai aktif",
    "Restore as archived" to "Pulihkan sebagai arsip",
    "Local project storage is unavailable." to "Penyimpanan proyek lokal tidak tersedia.",
    "Saved project data could not be read safely." to "Data proyek tersimpan belum dapat dibaca dengan aman.",
    "Evidrilo could not read your saved projects." to "Evidrilo belum dapat membaca proyek tersimpan.",
    "Your project spaces are full. Export and permanently remove a project to make room. Completed projects also use a space." to "Ruang proyek penuh. Ekspor dan hapus permanen proyek untuk menyediakan ruang. Proyek selesai juga memakai ruang.",
    "This template is not ready to start. Only a published, reviewed template can create a project." to "Template belum siap. Hanya template terbit yang sudah ditinjau dapat membuat proyek.",
    "Project assistance is unavailable until a compatible reviewed template is selected. You can continue manually." to "Bantuan proyek belum tersedia sebelum template sesuai yang sudah ditinjau dipilih. Anda dapat melanjutkan manual.",
    "This project is past its 30-day recovery period. Refresh the project list to remove expired Trash items." to "Masa pemulihan 30 hari proyek ini berakhir. Muat ulang daftar untuk menghapus isi Sampah yang kedaluwarsa.",
    "Only projects in Trash can be restored from Trash." to "Hanya proyek dalam Sampah dapat dipulihkan dari Sampah.",
    "Restore this project from Trash before changing its status." to "Pulihkan proyek ini dari Sampah sebelum mengubah statusnya.",
    "A claim link points to a source that is not in this project. No changes were saved." to "Hubungan klaim merujuk sumber di luar proyek. Perubahan belum disimpan.",
    "One source field exceeds the local size limit or contains unsupported content. Your edits remain on screen." to "Salah satu isian sumber melewati batas ukuran lokal atau berisi konten tidak didukung. Perubahan tetap di layar.",
    "This project reached its 100-checkpoint history limit. Earlier saved revisions were not removed. Your current changes remain on screen; export a project archive before deciding how to continue." to "Proyek mencapai batas 100 titik simpan. Revisi terdahulu tetap disimpan. Perubahan saat ini tetap di layar; ekspor cadangan sebelum menentukan langkah berikutnya.",
    "This project exceeds the local per-project storage limit. Earlier saved work was not replaced. Shorten or split the project content, then retry; your current edits remain on screen." to "Proyek melewati batas penyimpanan lokal per proyek. Pekerjaan tersimpan tidak ditimpa. Pendekkan atau pisahkan isi, lalu coba lagi; perubahan tetap di layar.",
    "A local project storage limit was reached. Nothing was overwritten. Export a project archive or permanently remove work you no longer need; your current edits remain on screen." to "Batas penyimpanan lokal tercapai. Tidak ada data ditimpa. Ekspor cadangan atau hapus permanen pekerjaan yang tidak diperlukan; perubahan tetap di layar.",
    "This project archive contains an invalid project record. No projects were changed." to "Cadangan berisi catatan proyek tidak valid. Tidak ada proyek diubah.",
    "A different local project uses this archive ID. The existing project was not changed; import the file as a copy instead." to "Proyek lokal lain memakai ID cadangan ini. Proyek tidak berubah; impor sebagai salinan.",
    "This exact project is already present on this device. Nothing was changed." to "Proyek yang sama sudah ada di perangkat ini. Tidak ada perubahan.",
    "A safe copy could not be created because new local IDs could not be generated. No projects were changed." to "Salinan aman belum dapat dibuat karena ID lokal baru gagal dibuat. Tidak ada proyek diubah.",
    "This project contains attachment references without their verified archive bytes. No project data was imported." to "Proyek berisi rujukan lampiran tanpa data arsip terverifikasi. Data belum diimpor.",
    "Attachments could not be published safely. No project metadata was imported; retry after checking device storage." to "Lampiran belum dapat disimpan aman. Metadata proyek belum diimpor; periksa penyimpanan perangkat lalu coba lagi.",
    "The archive changes this project's attachment set. Import it as a separate copy to preserve existing files." to "Cadangan mengubah kumpulan lampiran proyek. Impor sebagai salinan terpisah untuk mempertahankan berkas.",
    "The archive's attachment metadata did not match the project. No data was imported." to "Metadata lampiran cadangan tidak sesuai proyek. Data belum diimpor.",
    "Private attachment storage could not complete the import. No project metadata was imported." to "Penyimpanan lampiran privat gagal menyelesaikan impor. Metadata proyek belum diimpor.",
    "This archive does not contain a newer project revision. Existing work was not changed." to "Cadangan tidak berisi revisi lebih baru. Pekerjaan saat ini tidak berubah.",
    "The current project timestamp cannot safely accept another revision. Existing work was not changed." to "Waktu proyek saat ini tidak aman untuk menerima revisi baru. Pekerjaan tidak berubah.",
    "This project action could not be completed. No unsupported project state was created." to "Tindakan proyek gagal. Status proyek tidak didukung tidak dibuat.",
    "This project is no longer available in local storage. Refresh the list and try again." to "Proyek tidak lagi tersedia secara lokal. Muat ulang daftar dan coba lagi.",
    "Local project storage is unavailable in this build." to "Penyimpanan proyek lokal tidak tersedia dalam versi ini.",
    "Saved project data could not be read. It was not overwritten." to "Data proyek tersimpan gagal dibaca dan tidak ditimpa.",
    "Local project storage could not complete that action. Your current edits remain on screen." to "Penyimpanan lokal gagal menyelesaikan tindakan. Perubahan Anda tetap di layar.",
    "Untitled evidence note" to "Catatan bukti tanpa judul",
    "unavailable evidence note" to "catatan bukti tidak tersedia",
    "this source" to "sumber ini",
    "A source link is removed from a claim that could not be identified." to "Hubungan sumber dihapus dari klaim yang tidak dapat dikenali.",
    "No structured project item is linked to this source." to "Belum ada bagian proyek terstruktur terhubung dengan sumber ini.",
    "Findings, themes, claims, and free-text analysis/output are retained unless listed above; free-text analysis and output are not linked automatically, so review them manually." to "Temuan, tema, klaim, serta analisis/hasil teks bebas dipertahankan kecuali disebut di atas. Teks bebas tidak dihubungkan otomatis; tinjau manual.",
    "Confirm to remove these source links and save a new revision. Cancel leaves the project unchanged." to "Konfirmasikan untuk menghapus hubungan sumber dan menyimpan revisi baru. Batal mempertahankan proyek.",
    "No finding or claim currently links to this note." to "Belum ada temuan atau klaim terhubung dengan catatan ini.",
    "Findings and free-text analysis/output are retained; free-text analysis and output are not linked automatically, so review them manually." to "Temuan serta analisis/hasil teks bebas dipertahankan. Teks bebas tidak dihubungkan otomatis; tinjau manual.",
    "Confirm to remove this note and save a new revision. Cancel leaves the project unchanged." to "Konfirmasikan untuk menghapus catatan dan menyimpan revisi baru. Batal mempertahankan proyek.",
    "Untitled" to "Tanpa judul",
    "Other project details" to "Rincian proyek lainnya",
    "Method notes" to "Catatan metode",
    "Hide notes" to "Sembunyikan catatan",
    "View notes" to "Lihat catatan",
    "Limits" to "Batasan",
    "Record provenance" to "Catat asal sumber",
    "Accessibility" to "Aksesibilitas",
    "Validating archive contents…" to "Memeriksa isi cadangan…",
    "The project archive could not be validated. Your existing projects were not changed." to "Cadangan proyek gagal divalidasi. Proyek saat ini tidak berubah.",
    "Importing project and selected attachments…" to "Mengimpor proyek dan lampiran terpilih…",
    "The conflicting local project could not be loaded. No projects were changed." to "Proyek lokal yang berkonflik gagal dimuat. Tidak ada proyek diubah.",
    "The project archive was not imported. No projects were changed." to "Cadangan belum diimpor. Tidak ada proyek diubah.",
    "The project archive could not be imported. Existing project data was preserved." to "Cadangan gagal diimpor. Data proyek saat ini dipertahankan.",
    "The archive could not be restored as a new revision. Local work was not replaced." to "Cadangan gagal dipulihkan sebagai revisi baru. Pekerjaan lokal tidak ditimpa.",
    "Make room for your ideas." to "Beri ruang bagi gagasan Anda.",
    "Loading local projects…" to "Memuat proyek lokal…",
    "A place for your next question" to "Ruang untuk pertanyaan berikutnya",
    "Choose a project structure. Bring your own ideas and evidence." to "Pilih struktur proyek. Bawa gagasan dan bukti Anda sendiri.",
    "Your project spaces are full. Export and remove a project you no longer need." to "Ruang proyek penuh. Ekspor dan hapus proyek yang tidak lagi diperlukan.",
    "Local project storage is unavailable" to "Penyimpanan proyek lokal tidak tersedia",
    "This platform build cannot save project drafts. Your existing project-type guidance remains available." to "Versi platform ini tidak dapat menyimpan draf. Panduan jenis proyek tetap tersedia.",
    "Saved project data could not be read" to "Data proyek tersimpan gagal dibaca",
    "The app did not overwrite the unreadable data. Retry, or keep browsing the catalog without creating a draft." to "Data yang tidak terbaca tidak ditimpa. Coba lagi, atau jelajahi katalog tanpa membuat draf.",
    "Projects could not be loaded" to "Proyek gagal dimuat",
    "No project state was assumed. Check local storage and retry." to "Status proyek tidak diasumsikan. Periksa penyimpanan lokal lalu coba lagi.",
    "Move project to Trash?" to "Pindahkan proyek ke Sampah?",
    "Working with project archive" to "Memproses cadangan proyek",
    "Project archive operation progress" to "Progres pemrosesan cadangan proyek",
    "Cancel import" to "Batalkan impor",
    "Reading project archive" to "Membaca cadangan proyek",
    "Project archive import progress" to "Progres impor cadangan proyek",
    "Reading project archive; total size is unknown" to "Membaca cadangan; ukuran total belum diketahui",
    "Review project archive" to "Tinjau cadangan proyek",
    "This is student-entered project data. Import does not verify sources, methods, or claims. Attachments are restored only to private storage on this device." to "Ini data proyek yang ditulis pelajar. Impor tidak memverifikasi sumber, metode, atau klaim. Lampiran dipulihkan hanya ke penyimpanan privat perangkat ini.",
    "Existing projects will never be overwritten." to "Proyek saat ini tidak pernah ditimpa.",
    "Project already exists" to "Proyek sudah ada",
    "The same project and revision are already on this device. Nothing was imported." to "Proyek dan revisi yang sama sudah ada di perangkat. Tidak ada data diimpor.",
    "Review project revision conflict" to "Tinjau konflik revisi proyek",
    "The local project is never overwritten. Restore creates a new local revision; importing as a copy assigns fresh IDs and remaps links and attachments." to "Proyek lokal tidak ditimpa. Pemulihan membuat revisi lokal baru; impor salinan memberi ID baru dan memetakan ulang hubungan serta lampiran.",
    "The attachment set differs. To avoid replacing files already used by this project, import the archive as a separate copy." to "Kumpulan lampiran berbeda. Impor sebagai salinan terpisah agar berkas proyek saat ini tidak diganti.",
    "Restore as a new revision" to "Pulihkan sebagai revisi baru",
    "Import as a copy" to "Impor sebagai salinan",
    "Project spaces are full" to "Ruang proyek penuh",
    "Project was not imported" to "Proyek belum diimpor",
    "method template" to "template metode",
    "project title" to "judul proyek",
    "project deadline" to "tenggat proyek",
    "assignment and project fields" to "tugas dan isian proyek",
    "sources" to "sumber",
    "synthesis themes" to "tema sintesis",
    "claim-source links" to "hubungan klaim–sumber",
    "evidence notes" to "catatan bukti",
    "findings" to "temuan",
    "evidence relationships" to "hubungan bukti",
    "file attachments" to "lampiran berkas",
    "This platform cannot restore project file attachments in this build. Your original file and local projects were left unchanged." to "Platform ini belum dapat memulihkan lampiran proyek. Berkas asli dan proyek lokal tidak berubah.",
    "File attachments could not be staged safely. No project data was imported; retry after checking device storage." to "Lampiran gagal disiapkan aman. Data belum diimpor; periksa penyimpanan perangkat lalu coba lagi.",
    "The archive integrity check failed. The file may be damaged or edited; no project data was imported." to "Pemeriksaan integritas cadangan gagal. Berkas mungkin rusak atau diedit; data belum diimpor.",
    "The archive exceeds safe decompression limits. No project data was imported." to "Cadangan melewati batas aman dekompresi. Data belum diimpor.",
    "This archive uses an unsupported project format version. No project data was imported." to "Versi format proyek tidak didukung. Data belum diimpor.",
    "Your last section could not be restored. Your project is still available." to "Posisi bagian terakhir gagal dipulihkan. Proyek tetap tersedia.",
    "Your section position could not be remembered. Your project is still available." to "Posisi bagian gagal diingat. Proyek tetap tersedia.",
    "Changes will be saved locally shortly." to "Perubahan segera disimpan secara lokal.",
    "Removed claim links were detached from limitation/action records. Their boundary, reason, and next-action text were retained for review." to "Hubungan klaim yang dihapus dilepaskan dari catatan batasan/langkah. Batasan, alasan, dan langkah berikutnya dipertahankan untuk ditinjau.",
    "Removed finding links were detached from limitation/action records. Their boundary, reason, and next-action text were retained for review." to "Hubungan temuan yang dihapus dilepaskan dari catatan batasan/langkah. Batasan, alasan, dan langkah berikutnya dipertahankan untuk ditinjau.",
    "The local save did not complete. Your edits remain on this screen; retry before leaving." to "Penyimpanan lokal belum selesai. Perubahan tetap di layar; coba lagi sebelum keluar.",
    "Your changes could not be saved. They remain on this screen; retry before continuing." to "Perubahan gagal disimpan dan tetap di layar; coba lagi sebelum melanjutkan.",
    "Not saved — your edits are still on this screen." to "Belum disimpan — perubahan Anda tetap di layar.",
    "Your work is saved, but this section position could not be remembered." to "Pekerjaan tersimpan, tetapi posisi bagian gagal diingat.",
    "Save your current edits before attaching a file. Your project was not changed." to "Simpan perubahan sebelum melampirkan berkas. Proyek tidak berubah.",
    "This project is no longer available. No file was attached." to "Proyek tidak lagi tersedia. Berkas belum dilampirkan.",
    "Private project file storage is unavailable in this build. No file was attached." to "Penyimpanan berkas proyek privat tidak tersedia. Berkas belum dilampirkan.",
    "The file could not be saved with this project. Existing project data was left unchanged." to "Berkas gagal disimpan bersama proyek. Data proyek saat ini tidak berubah.",
    "File addition was canceled. The saved project revision and earlier revisions were left unchanged." to "Penambahan berkas dibatalkan. Revisi tersimpan dan sebelumnya tidak berubah.",
    "The saved attachment could not be read or its integrity check failed. The file and project remain unchanged; try attaching the source again." to "Lampiran gagal dibaca atau pemeriksaan integritas gagal. Berkas dan proyek tidak berubah; coba lampirkan sumber kembali.",
    "No readable text was found. The source file remains attached and unchanged." to "Tidak ada teks terbaca. Berkas sumber tetap dilampirkan dan tidak berubah.",
    "This file type cannot be previewed here. PDF and image attachments remain available for manual note-taking in a compatible viewer." to "Jenis berkas belum dapat dipratinjau. PDF dan gambar tetap tersedia untuk pencatatan manual melalui aplikasi yang sesuai.",
    "The document is malformed or could not be read safely. The source file remains attached and unchanged." to "Dokumen rusak atau gagal dibaca aman. Berkas sumber tetap dilampirkan dan tidak berubah.",
    "This document exceeds the on-device text preview limit. The source file remains attached and unchanged." to "Dokumen melewati batas pratinjau teks lokal. Berkas sumber tetap dilampirkan dan tidak berubah.",
    "Text preview cancelled. The attachment and project were not changed." to "Pratinjau dibatalkan. Lampiran dan proyek tidak berubah.",
    "Save your current edits before removing a file. The file and project were not changed." to "Simpan perubahan sebelum menghapus berkas. Berkas dan proyek tidak berubah.",
    "Removed from the current project. Earlier revisions remain preserved; private file cleanup or recovery is still pending. Reopen the project list to retry recovery." to "Dihapus dari proyek saat ini. Revisi terdahulu dipertahankan; pembersihan atau pemulihan berkas privat masih tertunda. Buka ulang daftar proyek untuk mencoba pemulihan.",
    "Removed from the current project. Earlier saved revisions still retain this file." to "Dihapus dari proyek saat ini. Revisi terdahulu masih menyimpan berkas ini.",
    "Removed from the current project. No earlier revision retained this file, so it was removed from private storage." to "Dihapus dari proyek saat ini. Berkas juga dihapus dari penyimpanan privat karena tidak ada revisi terdahulu yang menyimpannya.",
    "This project is no longer available. The file was not removed." to "Proyek tidak lagi tersedia. Berkas belum dihapus.",
    "Private project file storage is unavailable. The file and revision history were not changed." to "Penyimpanan berkas privat tidak tersedia. Berkas dan riwayat revisi tidak berubah.",
    "The file could not be safely removed. Existing project data and revision history were left unchanged." to "Berkas gagal dihapus aman. Data proyek dan riwayat revisi tidak berubah.",
    "Automatic save failed. Your edits are still on screen; retry or create a checkpoint before leaving." to "Penyimpanan otomatis gagal. Perubahan tetap di layar; coba lagi atau buat titik simpan sebelum keluar.",
    "Preparing a verified project archive on this device…" to "Menyiapkan cadangan proyek terverifikasi di perangkat ini…",
    "Nothing is prefilled. Add your own task, sources, and notes. Progress tracks structure, not quality or truth. This project stays on this device." to "Tidak ada isi bawaan. Tambahkan tugas, sumber, dan catatan sendiri. Progres menghitung struktur, bukan kualitas atau kebenaran. Proyek tetap di perangkat ini.",
    "This starter adds editable sections, not research content or a reviewed method. Confirm method and ethics requirements with your instructor. Structure progress is not a grade." to "Panduan ini menambahkan bagian yang dapat diedit, bukan isi penelitian atau metode terverifikasi. Konfirmasikan metode dan etika dengan pengajar. Progres struktur bukan nilai.",
    "Required-field progress tracks presence, not research quality. Your draft stays on this device." to "Progres isian wajib menghitung keberadaan isi, bukan kualitas penelitian. Draf tetap di perangkat ini.",
    "Enter source details yourself. Evidrilo does not search the web, verify DOI/URLs, or decide whether a source is credible." to "Masukkan rincian sumber sendiri. Evidrilo tidak mencari di web, memverifikasi DOI/URL, atau menentukan kredibilitas sumber.",
    "Project files" to "Berkas proyek",
    "Files stay private on this device. You can open a bounded local text preview for supported files, then manually record any excerpt as evidence. Preview text is not verified or sent to AI." to "Berkas tetap privat di perangkat. Buka pratinjau teks lokal terbatas untuk berkas didukung, lalu catat kutipan manual sebagai bukti. Teks tidak diverifikasi atau dikirim ke AI.",
    "Remove from current project" to "Hapus dari proyek saat ini",
    "Reading text…" to "Membaca teks…",
    "Review text" to "Tinjau teks",
    "In-app text preview is unavailable for this file type; keep it attached and record excerpts manually from a compatible viewer." to "Pratinjau teks belum tersedia untuk jenis berkas ini. Pertahankan lampiran dan catat kutipan manual melalui aplikasi yang sesuai.",
    "This project reached the 50-file attachment limit." to "Proyek mencapai batas 50 lampiran.",
    "Attach a file" to "Lampirkan berkas",
    "Selecting project files is not available in this platform build yet." to "Pemilihan berkas belum tersedia pada versi platform ini.",
    "Add only excerpts or notes you recorded from a source. Each note stays linked to that source; this does not verify the source or the interpretation." to "Tambahkan hanya kutipan atau catatan yang Anda ambil dari sumber. Catatan tetap terhubung dengan sumber; hubungan ini tidak memverifikasi sumber atau interpretasi.",
    "Student-written synthesis" to "Sintesis tulisan pelajar",
    "Findings are your interpretations. Connect each one to specific evidence and choose how the relationship reads to you; Evidrilo does not decide whether it is correct." to "Temuan adalah interpretasi Anda. Hubungkan dengan bukti tertentu dan pilih hubungannya; Evidrilo tidak menentukan kebenarannya.",
    "Earlier cross-source comparison notes" to "Catatan perbandingan antarsumber sebelumnya",
    "Add a comparison note" to "Tambah catatan perbandingan",
    "SOURCE" to "SUMBER",
    "Project source" to "Sumber proyek",
    "OBSERVATION" to "PENGAMATAN",
    "Write a bounded claim and connect it to evidence notes you selected. These are student-recorded relationships, not an automated quality verdict." to "Tulis klaim dengan cakupan terbatas dan hubungkan dengan catatan bukti terpilih. Hubungan ini dicatat pelajar, bukan putusan kualitas otomatis.",
    "Sources associated with this project" to "Sumber terkait proyek ini",
    "These project-level links do not mean a source supports a particular claim. Link evidence notes to a specific claim above." to "Hubungan pada tingkat proyek tidak berarti sumber mendukung klaim tertentu. Hubungkan catatan bukti dengan klaim di atas.",
    "Record a boundary, why it matters, and a next action. Optional links identify which findings or claims it affects; these are your recorded relationships, not an Evidrilo verdict." to "Catat batasan, alasan pentingnya, dan langkah berikutnya. Hubungan opsional menandai temuan atau klaim yang terdampak; ini catatan pilihan Anda, bukan putusan Evidrilo.",
    "No finding or claim has been added yet. These records can remain project-wide until you choose links." to "Belum ada temuan atau klaim. Catatan dapat berlaku untuk seluruh proyek sampai Anda memilih hubungan.",
    "Retry save and create checkpoint" to "Coba simpan dan buat titik simpan",
    "Create revision checkpoint" to "Buat titik simpan revisi",
    "Draft was not saved" to "Draf belum disimpan",
    "Choose a format. Review the file before saving or sharing." to "Pilih format. Tinjau berkas sebelum menyimpan atau membagikan.",
    "File export is not available in this build." to "Ekspor berkas tidak tersedia dalam versi ini.",
    "Reading source text" to "Membaca teks sumber",
    "Checking the saved file size and checksum, then preparing a local preview. Nothing is sent online." to "Memeriksa ukuran dan checksum berkas tersimpan, lalu menyiapkan pratinjau lokal. Tidak ada data dikirim daring.",
    "Local text preview only. Review the source yourself; Evidrilo has not verified or added this text as evidence." to "Hanya pratinjau lokal. Tinjau sumber sendiri; Evidrilo belum memverifikasi atau menambahkan teks sebagai bukti.",
    "Preview shortened at the local safety limit. Use the original document to check the full passage and its location." to "Pratinjau dipendekkan pada batas aman lokal. Periksa dokumen asli untuk kutipan lengkap dan lokasinya.",
    "Select and copy only a passage you have checked, then record it in the project’s source and evidence fields." to "Pilih dan salin hanya bagian yang sudah diperiksa, lalu catat pada isian sumber dan bukti proyek.",
    "Remove file from this project?" to "Hapus berkas dari proyek ini?",
    "Remove from project" to "Hapus dari proyek",
    "Keep file" to "Pertahankan berkas",
)
