package dev.nextgen.mobile

// App-owned presentation copy. Record IDs and learner content are never changed.
internal fun indonesianCopy7(): Map<String, String> = mapOf(
    "Cannot conclude from this case" to "Belum dapat disimpulkan dari kasus",
    "Unmapped relation" to "Hubungan belum terpetakan",
    "Missing evidence" to "Bukti belum tersedia",
    "Select the supplied observations that directly help answer the case requirement." to "Pilih pengamatan tersedia yang langsung membantu menjawab persyaratan kasus.",
    "Write one claim that stays inside the observations you selected." to "Tulis satu klaim terbatas pada pengamatan pilihan Anda.",
    "Define what the available evidence can and cannot support." to "Tentukan yang dapat dan tidak dapat didukung bukti tersedia.",
    "Complete the evidence workflow to connect a next action to the remaining gap." to "Selesaikan alur bukti untuk menghubungkan langkah berikutnya dengan celah tersisa.",
    "Action Plan" to "Rencana Langkah",
    "You know what\nmatters next." to "Tentukan yang\npenting berikutnya.",
    "Turn gaps into progress with a clear,\nevidence-linked plan." to "Ubah celah menjadi progres dengan rencana\nyang jelas dan terhubung bukti.",
    "Review the case" to "Tinjau kasus",
    "No action selected yet" to "Belum memilih langkah",
    "Selected by you" to "Anda pilih",
    "Suggested by verification" to "Disarankan pemeriksaan",
    "Requirement Trace" to "Jejak Persyaratan",
    "Trace the claim." to "Telusuri klaim.",
    "See why this requirement exists and\nwhere the support comes from." to "Lihat alasan persyaratan ini\ndan asal dukungannya.",
    "Why this is required" to "Mengapa diperlukan",
    "This requirement is part of the supplied case brief. Evidrilo keeps the requirement, evidence anchors, and claim boundary visible together." to "Persyaratan berasal dari instruksi kasus. Evidrilo menampilkan persyaratan, rujukan bukti, dan batas klaim bersama.",
    "Offline source locator" to "Lokasi sumber luring",
    "The competition case is bundled locally. Document page locators are unavailable, so Evidrilo shows stable fact IDs and supplied text instead of inventing citations." to "Kasus kompetisi tersedia lokal. Lokasi halaman dokumen tidak tersedia; Evidrilo menampilkan ID fakta tetap dan teks, tanpa mengarang sitasi.",
    "Review claim boundary" to "Tinjau batas klaim",
    "Continue to action plan" to "Lanjutkan ke rencana langkah",
    "Open claim review" to "Buka tinjauan klaim",
    "Claim Boundary" to "Batas Klaim",
    "Keep the claim inside the case." to "Batasi klaim sesuai kasus.",
    "Review the learner-authored claim, scope, limitations, and anchors before verification." to "Tinjau klaim tulisan pelajar, cakupan, batasan, dan rujukannya sebelum pemeriksaan.",
    "Not assessed yet" to "Belum dinilai",
    "Complete the local claim review to compare the boundary with the supplied observations." to "Selesaikan tinjauan klaim lokal untuk membandingkan batas dengan pengamatan tersedia.",
    "Current draft boundary" to "Batas draf saat ini",
    "No limitation selected yet" to "Belum memilih batasan",
    "Verify this claim" to "Periksa klaim ini",
    "Verify Claim" to "Periksa Klaim",
    "Does the claim stay inside the evidence?" to "Apakah klaim tetap dalam batas bukti?",
    "Verification reports the reducer's deterministic checks. It does not generate a replacement conclusion." to "Pemeriksaan melaporkan hasil aturan tetap. Kesimpulan pengganti tidak dibuat otomatis.",
    "Complete the local evidence draft to see anchored feedback for this claim." to "Lengkapi draf bukti lokal untuk melihat umpan balik berujukan.",
    "Hide verification details" to "Sembunyikan rincian pemeriksaan",
    "Review verification details" to "Tinjau rincian pemeriksaan",
    "Action plan" to "Rencana langkah",
    "What Changed?" to "Apa yang Berubah?",
    "See what changed." to "Lihat perubahannya.",
    "One revision is kept beside the original so you can inspect the change without losing learner authorship." to "Satu revisi disimpan bersama draf awal agar perubahan dapat diperiksa tanpa kehilangan tulisan pelajar.",
    "Before feedback → after one revision" to "Sebelum umpan balik → setelah satu revisi",
    "Verification unavailable" to "Pemeriksaan tidak tersedia",
    "This saved comparison includes the before/after drafts but does not store a verification record." to "Perbandingan tersimpan memuat draf sebelum/sesudah, tetapi tidak memuat catatan pemeriksaan.",
    "Open local history" to "Buka riwayat lokal",
    "Track what changed." to "Telusuri perubahannya.",
    "Follow how evidence, claims, and actions changed." to "Ikuti perubahan bukti, klaim, dan langkah.",
    "Complete the free evidence workflow and one revision to create a local before/after record." to "Selesaikan alur bukti gratis dan satu revisi untuk membuat catatan sebelum/sesudah lokal.",
    "Start evidence review" to "Mulai tinjauan bukti",
    "This workspace" to "Ruang kerja ini",
    "evidence removed" to "bukti dihapus",
    "evidence added" to "bukti ditambahkan",
    "actions changed" to "langkah berubah",
    "Latest local comparison" to "Perbandingan lokal terbaru",
    "The learner-authored before/after state is available locally." to "Tulisan sebelum/sesudah pelajar tersedia lokal.",
    "Boundary kept visible" to "Batas tetap terlihat",
    "History does not turn a bounded case into a scientific-truth score." to "Riwayat tidak mengubah kasus terbatas menjadi skor kebenaran ilmiah.",
    "View evidence delta" to "Lihat perubahan bukti",
    "Clear local comparison" to "Hapus perbandingan lokal",
    "Clear local comparison?" to "Hapus perbandingan lokal?",
    "This removes the saved before/after comparison from this device. It does not delete an account or change the bundled case." to "Perbandingan sebelum/sesudah dihapus dari perangkat. Akun tidak dihapus dan kasus bawaan tidak berubah.",
    "Clear comparison" to "Hapus perbandingan",
    "Keep it" to "Pertahankan",
    "Requirement 1" to "Persyaratan 1",
    "Tap to inspect requirement origin and links" to "Sentuh untuk memeriksa asal dan hubungan persyaratan",
    "Evidence linked to this requirement" to "Bukti terhubung dengan persyaratan",
    "Available observations are listed; selected anchors are marked. Selection alone is not a support verdict." to "Pengamatan tersedia ditampilkan; rujukan terpilih ditandai. Pemilihan saja bukan putusan dukungan.",
    "Other case fact" to "Fakta kasus lain",
    "This action is stale because its limitation anchor is not selected." to "Langkah kedaluwarsa karena rujukan batasannya belum dipilih.",
    "Start this action" to "Mulai langkah ini",
    "View all" to "Lihat semua",
    "Open student account" to "Buka akun pelajar",
    "Open account options" to "Buka pilihan akun",
    "Student account" to "Akun pelajar",
    "account history" to "riwayat akun",
    "no saved comparison" to "belum ada perbandingan tersimpan",
    "evidence changes" to "perubahan bukti",
    "Local" to "Lokal",
    "project storage" to "penyimpanan proyek",
    "Project progress" to "Progres proyek",
    "requirements" to "persyaratan",
    "selected / supplied" to "dipilih / tersedia",
    "next actions" to "langkah berikutnya",
    "Repeat the comparison" to "Ulangi perbandingan",
    "No further action" to "Tanpa langkah lanjutan",
    "Choose a next action" to "Pilih langkah berikutnya",
    "Map the supplied evidence" to "Petakan bukti tersedia",
    "Write a bounded claim" to "Tulis klaim terbatas",
    "Set the claim boundary" to "Tentukan batas klaim",
    "State the case limitation" to "Nyatakan batasan kasus",
    "Open Evidrilo chat guide. Drag to move." to "Buka panduan chat Evidrilo. Geser untuk memindahkan.",
    "Move assistant to left edge" to "Pindahkan asisten ke tepi kiri",
    "Move assistant to right edge" to "Pindahkan asisten ke tepi kanan",
    "Show the observations" to "Tampilkan pengamatan",
    "Explain the feedback" to "Jelaskan umpan balik",
    "Which evidence is linked?" to "Bukti apa yang terhubung?",
    "Local chat history could not be loaded. Your saved chats were not changed." to "Riwayat chat lokal gagal dimuat. Chat tersimpan tidak berubah.",
    "Could not save this chat on your device. Try again after checking free storage." to "Chat gagal disimpan di perangkat. Periksa ruang penyimpanan lalu coba lagi.",
    "Chat history is full. Delete an old chat to start another." to "Riwayat chat penuh. Hapus chat lama untuk memulai yang baru.",
    "This chat is full. Start a new chat to continue." to "Chat penuh. Mulai chat baru untuk melanjutkan.",
    "You can attach up to three files to one message." to "Maksimal tiga berkas dalam satu pesan.",
    "This file is over 10 MB. Choose a smaller file." to "Berkas melebihi 10 MB. Pilih berkas lebih kecil.",
    "Chat history" to "Riwayat chat",
    "Evidrilo chat" to "Chat Evidrilo",
    "New chat" to "Chat baru",
    "Close chat" to "Tutup chat",
    "Saved on this device" to "Tersimpan di perangkat ini",
    "No chats yet. Start a conversation about this case and it will appear here." to "Belum ada chat. Mulai percakapan tentang kasus ini untuk melihatnya di sini.",
    "Earlier case state · read only" to "Status kasus sebelumnya · hanya baca",
    "Delete" to "Hapus",
    "This chat is from an earlier case state. You can read it here; start a new chat for the current facts." to "Chat berasal dari status kasus sebelumnya. Baca di sini; mulai chat baru untuk fakta saat ini.",
    "What would you like to understand?" to "Apa yang ingin dipahami?",
    "Ask about the supplied observations, your hypothesis, or the next step. Answers stay within this case." to "Tanyakan pengamatan tersedia, hipotesis, atau langkah berikutnya. Jawaban tetap terbatas pada kasus.",
    "Add file, maximum 10 MB" to "Tambah berkas, maksimal 10 MB",
    "Start a new chat to continue" to "Mulai chat baru untuk melanjutkan",
    "Ask about this case" to "Tanyakan tentang kasus",
    "Files up to 10 MB stay on this device. The local guide does not analyze them." to "Berkas maksimal 10 MB tetap di perangkat. Panduan lokal tidak menganalisisnya.",
    "Open bounded AI help for this feedback" to "Buka bantuan AI terbatas untuk umpan balik",
    "Open verification" to "Buka pemeriksaan",
    "Explore evidence" to "Jelajahi bukti",
    "Continue this case" to "Lanjutkan kasus",
    "Delete this chat?" to "Hapus chat ini?",
    "Its messages and locally stored files will be removed from this device." to "Pesan dan berkas lokal akan dihapus dari perangkat ini.",
    "Start with the Evidence screen. Compare the supplied observations, then select the facts that directly support your claim." to "Mulai dari layar Bukti. Bandingkan pengamatan, lalu pilih fakta yang langsung mendukung klaim.",
    "You have selected evidence. Write a claim that stays within those observations, then set its scope and limitation." to "Anda sudah memilih bukti. Tulis klaim terbatas pada pengamatan, lalu tentukan cakupan dan batasan.",
    "Review your claim, its scope and limitation, and one useful next action. Then run the deterministic verification." to "Tinjau klaim, cakupan, batasan, dan satu langkah berguna. Lalu jalankan pemeriksaan kasus.",
    "This case has no supplied observations to show." to "Kasus tidak memiliki pengamatan untuk ditampilkan.",
    "Run verification to get feedback for this claim." to "Jalankan pemeriksaan untuk mendapatkan umpan balik klaim.",
    "This feedback has no linked evidence anchors." to "Umpan balik tidak memiliki rujukan bukti terhubung.",
    "Run verification to see linked evidence anchors." to "Jalankan pemeriksaan untuk melihat rujukan bukti terhubung.",
    "I can help with the supplied case facts. Ask about the observations, your hypothesis, or the next step." to "Saya membantu memahami fakta kasus tersedia. Tanyakan pengamatan, hipotesis, atau langkah berikutnya.",
    "I can guide you through this case's supplied facts and current verification. Try asking about the observations, a bounded hypothesis, linked evidence, or your next step. I cannot assess material outside this case." to "Saya memandu fakta kasus dan hasil pemeriksaan saat ini. Tanyakan pengamatan, hipotesis terbatas, bukti terhubung, atau langkah berikutnya. Saya tidak menilai materi di luar kasus.",
    "Evidrilo · local guide" to "Evidrilo · panduan lokal",
    "Evidrilo" to "Evidrilo",
    "Preparing your evidence workspace…" to "Menyiapkan ruang kerja bukti Anda…",
    "Loading Evidrilo" to "Memuat Evidrilo",
    "Connecting securely" to "Menghubungkan dengan aman",
    "This page needs a network connection. Your local work stays safe." to "Halaman membutuhkan internet. Pekerjaan lokal tetap aman.",
    "Loading network page" to "Memuat halaman daring",
    "Leave loading screen" to "Keluar dari layar pemuatan",
    "Replay the introduction artwork" to "Ulangi animasi pengantar",
    "Your question, notes, claim and next step, connected in Evidrilo" to "Pertanyaan, catatan, klaim, dan langkah berikutnya terhubung dalam Evidrilo",
    "Question" to "Pertanyaan",
    "Next step" to "Langkah berikutnya",
    "Tap to bring it together" to "Sentuh untuk menyatukannya",
    "Empty structure. Your own content." to "Struktur kosong. Isi Anda sendiri.",
    "Project pager dot" to "Penanda halaman proyek",
    "Your interpretation" to "Interpretasi Anda",
    "1 note linked" to "1 catatan terhubung",
    "Drop the note here" to "Letakkan catatan di sini",
    "Keep limits visible" to "Perlihatkan batasan",
    "Unlink the example note" to "Lepaskan catatan contoh",
    "Link the example note" to "Hubungkan catatan contoh",
    "Linked to the example claim" to "Terhubung dengan klaim contoh",
    "Not linked. Drag onto the claim, or tap to link." to "Belum terhubung. Geser ke klaim, atau sentuh untuk menghubungkan.",
    "Reading note" to "Catatan bacaan",
    "A source you choose" to "Sumber pilihan Anda",
    "Or tap to connect" to "Atau sentuh untuk menghubungkan",
    "Project AI activity" to "Aktivitas AI proyek",
    "Refresh" to "Muat ulang",
    "Metadata only: stage, revision, and outcome. Prompts, replies, and project text are not shown here." to "Hanya metadata: tahap, revisi, dan hasil. Instruksi AI, jawaban, dan teks proyek tidak ditampilkan di sini.",
    "Refresh to check account activity metadata." to "Muat ulang untuk memeriksa metadata aktivitas akun.",
    "Refresh to check this account's activity for the current project." to "Muat ulang untuk memeriksa aktivitas akun pada proyek saat ini.",
    "Loading activity metadata…" to "Memuat metadata aktivitas…",
    "No AI activity metadata is recorded for this account." to "Belum ada metadata aktivitas AI tercatat untuk akun ini.",
    "No Project AI activity is recorded for this project." to "Belum ada aktivitas AI proyek tercatat untuk proyek ini.",
    "GENERAL" to "UMUM",
    "General Chat · unlinked" to "Chat umum · tanpa hubungan",
    "Metadata only" to "Hanya metadata",
    "Loading older activity…" to "Memuat aktivitas sebelumnya…",
    "Show older activity" to "Tampilkan aktivitas sebelumnya",
    "Loading suggested review" to "Memuat saran tinjauan",
    "Loading a suggested review. The local workflow remains available." to "Memuat saran tinjauan. Alur lokal tetap tersedia.",
    "Starting suggested review" to "Memulai saran tinjauan",
    "Starting the suggested review. The local workflow remains available." to "Memulai saran tinjauan. Alur lokal tetap tersedia.",
    "SUGGESTED NEXT STEP" to "SARAN LANGKAH BERIKUTNYA",
    "A clearer next step" to "Langkah berikutnya lebih jelas",
    "Local checks on recorded material. No academic score." to "Pemeriksaan lokal materi tercatat. Tanpa nilai akademis.",
    "Showing current edits. Save before export or AI opinion." to "Menampilkan perubahan saat ini. Simpan sebelum ekspor atau meminta pendapat AI.",
)
