package dev.nextgen.mobile

// App-owned presentation copy. Record IDs and learner content are never changed.
internal fun indonesianCopy9(): Map<String, String> = mapOf(
    "Record your first source" to "Catat sumber pertama",
    "Add material you actually used. Keep its title and citation with it." to "Tambahkan materi yang benar-benar dipakai. Simpan judul dan sitasinya.",
    "Complete your source details" to "Lengkapi rincian sumber",
    "Add a title and citation to the source records that need them." to "Tambahkan judul dan sitasi pada sumber yang memerlukannya.",
    "Take a note from your material" to "Ambil catatan dari materi",
    "Record an excerpt or paraphrase and keep it connected to its source." to "Catat kutipan atau parafrasa dan hubungkan dengan sumber.",
    "Review your evidence notes" to "Tinjau catatan bukti",
    "Add the missing note text or recorded connection." to "Tambahkan isi catatan atau hubungan yang belum tercatat.",
    "Connect your findings" to "Hubungkan temuan",
    "Show which recorded material each finding or comparison uses." to "Tunjukkan materi tercatat yang dipakai setiap temuan atau perbandingan.",
    "Review your claim links" to "Tinjau hubungan klaim",
    "Connect each statement to the material you want it to use." to "Hubungkan setiap pernyataan dengan materi yang ingin dipakai.",
    "Give your question a place to grow." to "Beri tempat bagi pertanyaan untuk berkembang.",
    "Explore this step with the help available for your project." to "Jelajahi langkah dengan bantuan yang tersedia untuk proyek.",
    "Take one question at a time. Your answers stay editable." to "Selesaikan satu pertanyaan setiap kali. Jawaban tetap dapat diedit.",
    "Keep the material you used close to your work." to "Simpan materi yang dipakai dekat dengan pekerjaan.",
    "Turn a useful passage into a note you can trace." to "Ubah kutipan berguna menjadi catatan yang dapat ditelusuri.",
    "Describe what you noticed, then connect it to your notes." to "Jelaskan yang Anda amati, lalu hubungkan dengan catatan.",
    "Say what your material supports, and show the connection." to "Nyatakan yang didukung materi dan tunjukkan hubungannya.",
    "Make room for what is uncertain and what comes next." to "Beri ruang untuk ketidakpastian dan langkah berikutnya.",
    "Follow your work from material to statement." to "Ikuti pekerjaan dari materi hingga pernyataan.",
    "Recorded material" to "Materi tercatat",
    "Choose your next move" to "Pilih langkah berikutnya",
    "A useful next step" to "Langkah berikutnya yang berguna",
    "Inspect your material and its limits before sharing. Recorded fields and links do not establish research quality." to "Periksa materi dan batasannya sebelum membagikan. Isian serta hubungan tercatat tidak membuktikan kualitas penelitian.",
    "More to work on" to "Masih perlu dikerjakan",
    "These are structure prompts, not a grade or a verdict on your research." to "Ini panduan struktur, bukan nilai atau putusan penelitian.",
    "Try the Free practice first" to "Coba latihan Free dahulu",
    "Preview only · your work stays untouched" to "Hanya pratinjau · pekerjaan Anda tetap utuh",
    "Get Started progress" to "Progres pengantar",
    "Close plan comparison" to "Tutup perbandingan paket",
    "Choose a plan" to "Pilih paket",
    "Plan selection" to "Pemilihan paket",
    "Plan details" to "Rincian paket",
    "Free includes the first Practice case; Pro opens all three. Free credits are granted once to a verified account after AI consent. Active Pro adds 200 credits each month, including annual plans. Earned credits accumulate without expiring. AI also needs internet, consent and an available service. Choosing a plan never starts a purchase: review and confirm the store offer first." to "Free mencakup latihan pertama; Pro membuka ketiganya. Kredit Free diberikan sekali setelah verifikasi akun dan persetujuan AI. Pro aktif menambah 200 kredit setiap bulan, termasuk paket tahunan. Kredit terkumpul tanpa kedaluwarsa. AI juga membutuhkan internet, persetujuan, dan layanan tersedia. Pemilihan paket tidak memulai pembelian: tinjau dan konfirmasikan penawaran toko dahulu.",
    "Pro plans are unavailable in this build. Free stays available." to "Paket Pro tidak tersedia pada versi ini. Free tetap tersedia.",
    "Included" to "Termasuk",
    "Project spaces" to "Ruang proyek",
    "Practice cases" to "Kasus latihan",
    "One time" to "Sekali saja",
    "Each month" to "Setiap bulan",
    "Project archive (.evproj)" to "Cadangan proyek (.evproj)",
    "DOCX report" to "Laporan DOCX",
    "CSV table" to "Tabel CSV",
    "Project file" to "Berkas proyek",
    "AI conversations, account credentials, and credit records are excluded." to "Percakapan AI, kredensial akun, dan catatan kredit tidak disertakan.",
    "Package summary. The archive preserves the saved project, selected revision history, and listed attachment files." to "Ringkasan paket. Cadangan menyimpan proyek tersimpan, riwayat revisi terpilih, dan lampiran terdaftar.",
    "Review the text that will be saved in this file." to "Tinjau teks yang akan disimpan dalam berkas.",
    "Canceling stops file creation only; it does not undo a local save or checkpoint already made to prepare this snapshot." to "Pembatalan hanya menghentikan pembuatan berkas; simpan lokal atau titik simpan untuk cuplikan ini tidak dibatalkan.",
    "Archive checks detect file corruption; they do not verify the truth or quality of project content." to "Pemeriksaan cadangan mendeteksi kerusakan berkas; tidak memverifikasi kebenaran atau kualitas isi proyek.",
    "Choose save location" to "Pilih lokasi simpan",
    "Start with the evidence." to "Mulai dengan bukti.",
    "Tap the observations you want to use in your comparison." to "Sentuh pengamatan untuk perbandingan Anda.",
    "Connection" to "Hubungan",
    "What are you saying?" to "Apa yang Anda nyatakan?",
    "Choose the relationship your conclusion will describe." to "Pilih hubungan yang digambarkan kesimpulan.",
    "Put it in your own words." to "Tulis dengan kata-kata sendiri.",
    "Write a short claim that follows from your selected evidence." to "Tulis klaim singkat berdasarkan bukti terpilih.",
    "How far does it go?" to "Sejauh apa berlaku?",
    "Choose how broadly your claim applies." to "Pilih seberapa luas klaim berlaku.",
    "Give the claim its limits." to "Beri batas pada klaim.",
    "Choose a supplied limitation and explain why it matters." to "Pilih batasan tersedia dan jelaskan pentingnya.",
    "Turn a limit into a next move." to "Ubah batasan menjadi langkah.",
    "Choose what to do next, and explain your reason." to "Pilih langkah berikutnya dan jelaskan alasannya.",
    "Select at least one observation to continue." to "Pilih minimal satu pengamatan untuk melanjutkan.",
    "Keep no more than three evidence links." to "Maksimal tiga hubungan bukti.",
    "Choose a relationship to continue." to "Pilih hubungan untuk melanjutkan.",
    "Write at least 20 characters in your own words." to "Tulis minimal 20 karakter dengan kata-kata sendiri.",
    "Keep the claim within 320 characters." to "Batasi klaim hingga 320 karakter.",
    "Choose the scope of your claim." to "Pilih cakupan klaim.",
    "Select at least one supplied limitation." to "Pilih minimal satu batasan tersedia.",
    "Keep no more than two limitation links." to "Maksimal dua hubungan batasan.",
    "Explain the limit in 10–240 characters." to "Jelaskan batasan dalam 10–240 karakter.",
    "Choose a next action." to "Pilih langkah berikutnya.",
    "Explain your reason in 10–240 characters." to "Jelaskan alasan dalam 10–240 karakter.",
    "Compare an observed difference" to "Bandingkan perbedaan teramati",
    "Describe a limited observation" to "Gambarkan pengamatan terbatas",
    "Say the case is insufficient" to "Nyatakan kasus belum cukup",
    "Unsupported relationship" to "Hubungan tidak didukung",
    "Describe a difference between selected records." to "Gambarkan perbedaan antarcatatan terpilih.",
    "Keep the wording close to a specific observation." to "Dekatkan kalimat dengan pengamatan tertentu.",
    "Explain why these records do not support the conclusion." to "Jelaskan mengapa catatan tidak mendukung kesimpulan.",
    "Choose a supported relationship." to "Pilih hubungan yang didukung.",
    "These observations only" to "Hanya pengamatan ini",
    "A limited comparison" to "Perbandingan terbatas",
    "Describe what was recorded in this case." to "Gambarkan yang tercatat pada kasus.",
    "Compare the supplied conditions, with their limits." to "Bandingkan kondisi tersedia beserta batasannya.",
    "Claim that a cause applies beyond these records." to "Klaim suatu sebab berlaku di luar catatan ini.",
    "Choose a supported scope." to "Pilih cakupan yang didukung.",
    "Measure and control stirring" to "Ukur dan kendalikan pengadukan",
    "Narrow the claim" to "Persempit klaim",
    "No follow-up applies" to "Tidak ada tindak lanjut berlaku",
    "Bring the wording back within the available evidence." to "Batasi kembali kalimat sesuai bukti tersedia.",
    "Explain why no next action is applicable." to "Jelaskan mengapa tidak ada langkah berikutnya yang berlaku.",
    "Give a reason tied to a supplied limitation." to "Beri alasan terkait batasan tersedia.",
    "8–12 min" to "8–12 menit",
    "8–10 min" to "8–10 menit",
    "6–8 min" to "6–8 menit",
    "1 Free case · 2 more with Pro" to "1 kasus Free · 2 lagi dengan Pro",
    "Revisit case" to "Ulangi kasus",
    "Your full trail is open" to "Seluruh jalur terbuka",
    "Keep investigating with Pro" to "Terus menyelidiki dengan Pro",
    "Choose any case at your own pace." to "Pilih kasus sesuai ritme Anda.",
    "Unlock source comparison and changing data." to "Buka perbandingan sumber dan data berubah.",
    "What Practice records" to "Yang dicatat Latihan",
    "These are synthetic cases. Completion records your attempt, not a grade or proof of mastery. Your project work stays separate. The first case is Free; the other two require active Pro access. Saved attempts are retained when Pro ends." to "Ini kasus rekaan. Penyelesaian mencatat percobaan, bukan nilai atau bukti penguasaan. Pekerjaan proyek terpisah. Kasus pertama Free; dua lainnya membutuhkan Pro aktif. Percobaan tersimpan dipertahankan saat Pro berakhir.",
    "Pro · saved attempt retained" to "Pro · percobaan tersimpan dipertahankan",
    "Completed · revisit" to "Selesai · ulangi",
    "Ready to start" to "Siap dimulai",
    "Station selection" to "Pemilihan tahap",
    "Find your evidence trail" to "Temukan jalur bukti Anda",
    "Cases and Practice" to "Kasus dan Latihan",
    "Cases let you explore supplied evidence and an explainable claim/action workflow. Practice guides you through three short investigations. These synthetic learning records stay separate from your own projects; they are not sources you collected or a measure of mastery." to "Kasus membantu menjelajahi bukti tersedia serta alur klaim/langkah yang dapat dijelaskan. Latihan memandu tiga penyelidikan singkat. Catatan belajar rekaan terpisah dari proyek sendiri; bukan sumber yang Anda kumpulkan atau ukuran penguasaan.",
    "Swipe sideways or choose a type. Screen readers move focus through cards and activate one." to "Geser ke samping atau pilih jenis. Pembaca layar berpindah fokus antar kartu untuk membukanya.",
    "Structure only, not an evaluation or grade. Confirm method, evidence quality, and ethics with your instructor." to "Hanya struktur, bukan evaluasi atau nilai. Konfirmasikan metode, kualitas bukti, dan etika dengan pengajar.",
    "Investigate how a planned change relates to a measured outcome." to "Selidiki hubungan perubahan terencana dengan hasil terukur.",
    "Your assignment asks you to change a condition and observe a measurable result." to "Tugas meminta Anda mengubah kondisi dan mengamati hasil terukur.",
    "Frame the question and identify what will change and what will be measured." to "Rumuskan pertanyaan serta apa yang diubah dan diukur.",
    "Describe the procedure, comparison conditions, and any repeated trials." to "Jelaskan prosedur, kondisi perbandingan, dan pengulangan percobaan.",
    "Record observations, measurement context, and limitations." to "Catat pengamatan, konteks pengukuran, dan batasan.",
    "A single measurement or uncontrolled conditions limit what can be concluded." to "Satu pengukuran atau kondisi tidak terkendali membatasi kesimpulan.",
    "A difference in results does not by itself prove what caused the difference." to "Perbedaan hasil saja tidak membuktikan penyebabnya.",
    "Study patterns in existing conditions or responses without assigning an intervention." to "Pelajari pola kondisi atau jawaban yang ada tanpa memberikan intervensi.",
    "You observe existing patterns or collect survey responses without assigning a treatment." to "Anda mengamati pola atau mengumpulkan jawaban survei tanpa memberikan perlakuan.",
    "You observe people, events, or measurements as they already occur, or collect survey responses." to "Anda mengamati orang, peristiwa, atau pengukuran sebagaimana terjadi, atau mengumpulkan jawaban survei.",
    "Define the question, population, sample, and variables or survey topics." to "Tentukan pertanyaan, populasi, sampel, variabel, atau topik survei.",
    "Record how observations or responses were collected and who may be missing." to "Catat cara pengumpulan pengamatan/jawaban dan siapa yang belum tercakup.",
    "Summarize patterns while keeping the data and analysis traceable." to "Ringkas pola sambil menjaga data dan analisis dapat ditelusuri.",
    "An association between variables does not establish cause and effect." to "Hubungan antarvariabel belum membuktikan sebab akibat.",
    "Sampling, non-response, and question wording can affect what the results represent." to "Pengambilan sampel, tidak adanya respons, dan kalimat pertanyaan dapat memengaruhi keterwakilan hasil.",
    "Answer a focused question by comparing and synthesizing existing sources." to "Jawab pertanyaan terarah dengan membandingkan dan menyintesis sumber tersedia.",
    "You compare and synthesize research or other existing sources." to "Anda membandingkan dan menyintesis penelitian atau sumber yang ada.",
    "Your task asks what existing research or publications say about a defined topic." to "Tugas meminta meninjau penelitian atau publikasi tentang topik tertentu.",
    "Set the review question, scope, and how sources will be found and selected." to "Tentukan pertanyaan tinjauan, cakupan, serta cara mencari dan memilih sumber.",
    "Record source details and why each source belongs in the review." to "Catat rincian sumber dan alasan disertakan dalam tinjauan.",
    "Compare findings, methods, limitations, and points of disagreement." to "Bandingkan temuan, metode, batasan, dan perbedaan pendapat.",
    "A list of sources is not yet a synthesis; explain how the sources relate." to "Daftar sumber belum menjadi sintesis; jelaskan hubungan antarsumber.",
    "Source quality and relevance require judgment beyond citation completeness." to "Kualitas dan relevansi sumber memerlukan pertimbangan di luar kelengkapan sitasi.",
    "Explore experiences, meanings, or settings through interviews or field observations." to "Jelajahi pengalaman, makna, atau situasi melalui wawancara atau observasi lapangan.",
    "You explore people's experiences or a setting through interviews or field observation." to "Anda menjelajahi pengalaman orang atau situasi melalui wawancara atau observasi lapangan.",
    "You need to understand how people describe an experience or how something happens in context." to "Anda perlu memahami penuturan pengalaman atau peristiwa dalam konteks.",
    "Describe the research question, setting, participant context, and collection approach." to "Jelaskan pertanyaan penelitian, situasi, konteks peserta, dan cara pengumpulan.",
    "Protect privacy and follow the consent and ethics requirements for the assignment." to "Lindungi privasi dan ikuti persetujuan serta etika tugas.",
    "Connect interpretations and themes to contextualized notes or quotations." to "Hubungkan interpretasi dan tema dengan catatan atau kutipan berkonteks.",
    "Interpretations should preserve context and consider evidence that does not fit a theme." to "Pertahankan konteks interpretasi dan pertimbangkan bukti yang tidak sesuai tema.",
    "This overview cannot provide participant consent or replace an ethics review." to "Ringkasan ini tidak memberi persetujuan peserta atau menggantikan tinjauan etika.",
    "Develop or test a solution against stated user, design, or technical requirements." to "Kembangkan atau uji solusi sesuai persyaratan pengguna, desain, atau teknis.",
    "You design or build a solution and test it against stated criteria." to "Anda merancang atau membangun solusi dan mengujinya sesuai kriteria.",
    "Your assignment asks you to design, build, compare, or evaluate a solution." to "Tugas meminta merancang, membangun, membandingkan, atau mengevaluasi solusi.",
    "State the need, intended users, requirements, and constraints." to "Nyatakan kebutuhan, pengguna sasaran, persyaratan, dan batasan.",
    "Record design decisions, prototypes, test criteria, and observed results." to "Catat keputusan desain, prototipe, kriteria uji, dan hasil pengamatan.",
    "Compare results with the criteria and explain trade-offs and limitations." to "Bandingkan hasil dengan kriteria serta jelaskan kompromi dan batasan.",
    "Meeting a test criterion does not alone establish broad usability or real-world impact." to "Memenuhi kriteria uji saja belum membuktikan kemudahan pakai luas atau dampak nyata.",
    "User relevance and suitability may need feedback from the people affected." to "Relevansi dan kesesuaian mungkin memerlukan masukan orang yang terdampak.",
    "How to use this catalog" to "Cara memakai katalog",
    "Local starter available" to "Panduan lokal tersedia",
    "Open overview" to "Buka ringkasan",
    "Project types" to "Jenis proyek",
    "When this fits" to "Kapan cocok dipakai",
    "What you will organize" to "Yang akan Anda susun",
    "Check before you begin" to "Periksa sebelum memulai",
    "Start blank instead" to "Mulai kosong saja",
    "Offline project starter" to "Panduan proyek luring",
    "Creates" to "Membuat",
    "See project sections" to "Lihat bagian proyek",
    "Structure only. It adds no sources, observations, findings, or claims and does not evaluate your work." to "Hanya struktur. Tidak menambahkan sumber, pengamatan, temuan, atau klaim dan tidak menilai pekerjaan.",
    "Hide guide notes" to "Sembunyikan catatan panduan",
    "View limits and recording notes" to "Lihat batasan dan catatan pencatatan",
    "Provenance" to "Asal sumber",
    "Create my project" to "Buat proyek saya",
    "Template list" to "Daftar template",
    "Template details" to "Rincian template",
    "Template not selected" to "Template belum dipilih",
    "Return to the project-type overview and select a published template to inspect." to "Kembali ke ringkasan jenis proyek dan pilih template terbit untuk diperiksa.",
    "Loading published template…" to "Memuat template terbit…",
    "Template details unavailable" to "Rincian template tidak tersedia",
    "Template details could not be verified" to "Rincian template gagal diverifikasi",
    "The local project-type overview remains available. This template was not opened." to "Ringkasan jenis proyek lokal tetap tersedia. Template belum dibuka.",
    "Start a local project" to "Mulai proyek lokal",
    "Not available for a new project" to "Tidak tersedia untuk proyek baru",
)
