package dev.nextgen.mobile

// App-owned presentation copy. Record IDs and learner content are never changed.
internal fun indonesianCopy6(): Map<String, String> = mapOf(
    "Design question" to "Pertanyaan desain",
    "Options & tests" to "Pilihan dan pengujian",
    "Decisions & limits" to "Keputusan dan batasan",
    "Where can I start?" to "Dari mana saya mulai?",
    "Pick one question, one setting, and something you can observe." to "Pilih satu pertanyaan, satu situasi, dan sesuatu yang dapat diamati.",
    "Plan" to "Rencana",
    "What should I do next?" to "Apa langkah berikutnya?",
    "Separate what you have from what you need. Choose one small next action." to "Pisahkan yang sudah ada dari yang dibutuhkan. Pilih satu langkah kecil.",
    "Does my claim reach too far?" to "Apakah klaim saya terlalu luas?",
    "Trace it to a note. Keep the wording within the evidence you actually have." to "Telusuri ke catatan. Batasi kalimat sesuai bukti yang benar-benar tersedia.",
    "Markdown" to "Markdown",
    "A text report you can keep editing." to "Laporan teks yang dapat terus diedit.",
    "PDF" to "PDF",
    "A readable report you can share." to "Laporan mudah dibaca untuk dibagikan.",
    "DOCX" to "DOCX",
    "A report you can open in a document editor." to "Laporan untuk dibuka di pengolah dokumen.",
    "CSV" to "CSV",
    "Structured project rows for a spreadsheet." to "Baris proyek terstruktur untuk spreadsheet.",
    "evproj" to "evproj",
    "A project archive you can import into Evidrilo." to "Cadangan proyek untuk diimpor ke Evidrilo.",
    "Your own project writing stays as you wrote it." to "Tulisan proyek Anda tetap sebagaimana ditulis.",
    "Language could not be saved. Try again." to "Bahasa gagal disimpan. Coba lagi.",
    "Change" to "Ubah",
    "Remove" to "Hapus",
    "Save date" to "Simpan tanggal",
    "The tablet investigation" to "Penyelidikan tablet",
    "Revise once" to "Revisi sekali",
    "Rebuild after the evidence change" to "Susun ulang setelah bukti berubah",
    "See what you reconsidered." to "Lihat apa yang Anda tinjau ulang.",
    "Your initial claim is kept beside the one revision." to "Klaim awal dipertahankan bersama satu revisi.",
    "Your initial claim" to "Klaim awal Anda",
    "After the review" to "Setelah tinjauan",
    "Hide the retained decisions" to "Sembunyikan keputusan sebelumnya",
    "Compare evidence, limits, and next action" to "Bandingkan bukti, batasan, dan langkah berikutnya",
    "Next, reconsider this claim when an observation is unavailable." to "Berikutnya, tinjau ulang klaim saat pengamatan tidak tersedia.",
    "View tablet comparison history" to "Lihat riwayat perbandingan tablet",
    "No relation selected" to "Belum memilih hubungan",
    "Assignment or topic" to "Tugas atau topik",
    "Your assignment or topic" to "Tugas atau topik Anda",
    "Your research question" to "Pertanyaan penelitian Anda",
    "Start blank" to "Mulai kosong",
    "Observations or notes" to "Pengamatan atau catatan",
    "I’m not sure yet" to "Saya belum yakin",
    "Choose later" to "Pilih nanti",
    "Trace a claim" to "Telusuri klaim",
    "Notice limitations" to "Perhatikan batasan",
    "Review what changes" to "Tinjau perubahan",
    "Temporary preview · nothing is saved" to "Pratinjau sementara · tidak disimpan",
    "Next, choose what you may add first—or decide later." to "Berikutnya, pilih yang mungkin ditambahkan dahulu—atau tentukan nanti.",
    "This is a starting point, not a saved source or finding." to "Ini titik awal, bukan sumber atau temuan tersimpan.",
    "You stay in control of the interpretation and any next step." to "Anda tetap menentukan interpretasi dan langkah berikutnya.",
    "Optional AI help" to "Bantuan AI opsional",
    "Review suggestions before using them. Availability depends on your account and enabled services." to "Tinjau saran sebelum memakai. Ketersediaan bergantung pada akun dan layanan aktif.",
    "History and exports" to "Riwayat dan ekspor",
    "Keep local revisions, export a report, or move a project using an Evidrilo archive." to "Simpan revisi lokal, ekspor laporan, atau pindahkan proyek memakai cadangan Evidrilo.",
    "Your next question" to "Pertanyaan Anda berikutnya",
    "Open My Projects to create your own project explicitly." to "Buka Proyek Saya untuk membuat proyek sendiri secara eksplisit.",
    "Saving before leaving…" to "Menyimpan sebelum keluar…",
    "Saved practice needs recovery" to "Latihan tersimpan perlu dipulihkan",
    "Practice is temporary on this screen" to "Latihan sementara di layar ini",
    "Not saved · try again" to "Belum disimpan · coba lagi",
    "Temporary preview · synthetic data" to "Pratinjau sementara · data rekaan",
    "Saved on this device · synthetic data" to "Tersimpan di perangkat · data rekaan",
    "Opening local practice" to "Membuka latihan lokal",
    "Reading this device's practice record…" to "Membaca catatan latihan perangkat ini…",
    "Opening your practice." to "Membuka latihan Anda.",
    "Checking Pro access" to "Memeriksa akses Pro",
    "Your saved attempt stays on this device." to "Percobaan tersimpan tetap di perangkat ini.",
    "Checking your access…" to "Memeriksa akses Anda…",
    "Start a new attempt?" to "Mulai percobaan baru?",
    "This replaces only this case's saved attempt and comparison. Other cases and your Projects are retained." to "Hanya percobaan dan perbandingan kasus ini yang diganti. Kasus lain dan Proyek dipertahankan.",
    "Keep this attempt" to "Pertahankan percobaan ini",
    "Replace the unreadable practice record?" to "Ganti catatan latihan yang tidak terbaca?",
    "The new course record will replace the unreadable course data. Existing tablet history and Projects use separate storage." to "Catatan baru mengganti data latihan yang tidak terbaca. Riwayat tablet dan Proyek memakai penyimpanan terpisah.",
    "Save a fresh record" to "Simpan catatan baru",
    "Keep temporary practice" to "Tetap latihan sementara",
    "The latest practice could not be saved." to "Latihan terbaru gagal disimpan.",
    "Keep this screen open and retry to retain your latest changes, or leave with the previously saved record." to "Tetap di layar dan coba lagi untuk mempertahankan perubahan terbaru, atau keluar dengan catatan tersimpan sebelumnya.",
    "Keep and retry" to "Pertahankan dan coba lagi",
    "Leave anyway" to "Tetap keluar",
    "Local progress is unavailable" to "Progres lokal tidak tersedia",
    "The saved course record could not be read. It has been kept; this attempt is temporary." to "Catatan latihan gagal dibaca dan dipertahankan; percobaan ini sementara.",
    "You can practice here, but this build cannot retain this course record when you leave." to "Anda dapat berlatih, tetapi versi ini tidak dapat menyimpan catatan latihan saat keluar.",
    "Save a fresh course record" to "Simpan catatan latihan baru",
    "The latest change is not saved" to "Perubahan terakhir belum tersimpan",
    "Keep the screen open and retry saving." to "Tetap di layar dan coba simpan lagi.",
    "Next move" to "Langkah berikutnya",
    "Start with your\nmaterials." to "Mulai dari\nmateri Anda.",
    "Organize an assignment, criteria, and source notes inside a project. You decide what becomes a finding." to "Tata tugas, kriteria, dan catatan sumber dalam proyek. Anda menentukan yang menjadi temuan.",
    "CASE CONTENT" to "ISI KASUS",
    "This example stays separate from your projects and remains available offline." to "Contoh ini terpisah dari proyek dan tetap tersedia luring.",
    "Assignment Brief" to "Instruksi Tugas",
    "Rubric" to "Rubrik",
    "Open My Projects" to "Buka Proyek Saya",
    "Explore the bundled case" to "Jelajahi kasus bawaan",
    "AIM" to "TUJUAN",
    "FACTS" to "FAKTA",
    "LIMITS" to "BATASAN",
    "support gap status not assessed" to "celah dukungan belum dinilai",
    "no open support gaps" to "tidak ada celah dukungan terbuka",
    "1 open support gap" to "1 celah dukungan terbuka",
    "Evidence-backed local workspace" to "Ruang kerja lokal berbasis bukti",
    "What's covered" to "Yang tercakup",
    "Case requirement" to "Persyaratan kasus",
    "Supplied observations" to "Pengamatan tersedia",
    "Claim boundary" to "Batas klaim",
    "Visible" to "Terlihat",
    "What needs attention" to "Yang perlu diperhatikan",
    "Complete the evidence review" to "Selesaikan tinjauan bukti",
    "No open support gap" to "Tidak ada celah dukungan terbuka",
    "Review the supplied observations before treating the claim as supported." to "Tinjau pengamatan tersedia sebelum menganggap klaim didukung.",
    "The bounded checks pass; keep the next action within the case boundary." to "Pemeriksaan terbatas terpenuhi; batasi langkah berikutnya sesuai kasus.",
    "Review the claim boundary and choose a fact-linked next action." to "Tinjau batas klaim dan pilih langkah terkait fakta.",
    "Continue workspace" to "Lanjutkan ruang kerja",
    "Evidence Map" to "Peta Bukti",
    "See what holds up." to "Lihat apa yang mendukung.",
    "Explore how supplied evidence maps to your requirement — and spot what's still missing." to "Jelajahi hubungan bukti tersedia dengan persyaratan—dan temukan yang masih kurang.",
    "Select supplied observations before treating the claim as supported." to "Pilih pengamatan tersedia sebelum menganggap klaim didukung.",
    "Review the evidence that is still missing for a fully bounded claim." to "Tinjau bukti yang belum tersedia untuk klaim bercakupan tepat.",
    "The current claim cannot be assessed safely from the supplied case." to "Klaim saat ini belum dapat dinilai aman dari kasus tersedia.",
    "A selected reference is not available in the active case version." to "Rujukan terpilih tidak tersedia dalam versi kasus aktif.",
    "Open evidence lens" to "Buka lensa bukti",
    "Evidence Lens" to "Lensa Bukti",
    "Look closely at the evidence." to "Perhatikan buktinya.",
    "Inspect the supplied observations before deciding what your claim can support." to "Periksa pengamatan sebelum menentukan yang dapat didukung klaim.",
    "No supplied observations" to "Tidak ada pengamatan tersedia",
    "This case has no observation facts available for the evidence lens." to "Kasus ini tidak memiliki fakta pengamatan untuk lensa bukti.",
    "Bounded local evidence" to "Bukti lokal terbatas",
    "This case provides stable fact IDs and supplied text. Page locators, extracted citations, and scientific-truth judgments are not available in the offline slice." to "Kasus menyediakan ID fakta tetap dan teks. Lokasi halaman, sitasi ekstraksi, dan penilaian kebenaran ilmiah tidak tersedia pada fitur luring.",
    "Trace this requirement" to "Telusuri persyaratan ini",
    "Supplied observation" to "Pengamatan tersedia",
    "Unavailable reference" to "Rujukan tidak tersedia",
    "Not an observation" to "Bukan pengamatan",
    "Available" to "Tersedia",
    "Tap to inspect source and usage" to "Sentuh untuk memeriksa sumber dan pemakaian",
    "Evidence detail" to "Rincian bukti",
    "Origin" to "Asal",
    "Bundled case record" to "Catatan kasus bawaan",
    "Case ID" to "ID kasus",
    "Case version" to "Versi kasus",
    "Not provided by this case" to "Tidak disediakan kasus ini",
    "Fact ID" to "ID fakta",
    "Availability" to "Ketersediaan",
    "Record type" to "Jenis catatan",
    "Relationship to this draft" to "Hubungan dengan draf ini",
    "Selected by you as an evidence anchor; support is assessed separately." to "Anda memilih sebagai rujukan bukti; dukungan dinilai terpisah.",
    "Available in the case, but not selected in this draft." to "Tersedia dalam kasus, tetapi belum dipilih pada draf.",
    "Recorded value" to "Nilai tercatat",
    "Supplied text" to "Teks tersedia",
    "Interpretation boundary" to "Batas interpretasi",
    "Selection records your choice; it does not by itself establish that this observation supports the claim." to "Pemilihan mencatat keputusan Anda; itu sendiri belum membuktikan pengamatan mendukung klaim.",
    "Draft reference" to "Rujukan draf",
    "This draft references this ID, but its target is unavailable." to "Draf merujuk ID ini, tetapi catatan tujuan tidak tersedia.",
    "This ID is not referenced by the current draft." to "ID ini tidak dirujuk draf saat ini.",
    "What is known" to "Yang diketahui",
    "This reference is not present in the active case version. No substitute observation is shown." to "Rujukan tidak ada dalam versi kasus aktif. Pengamatan pengganti tidak ditampilkan.",
    "This draft contains the ID, but it is not counted as a selected observation." to "Draf memuat ID ini, tetapi tidak dihitung sebagai pengamatan terpilih.",
    "This case fact is not selected as evidence." to "Fakta kasus ini belum dipilih sebagai bukti.",
    "Source locator" to "Lokasi sumber",
    "Page or section locator is not supplied in this case." to "Lokasi halaman atau bagian tidak disediakan dalam kasus.",
    "Requirement trace" to "Jejak persyaratan",
    "Requirement ID" to "ID persyaratan",
    "Requirement text" to "Teks persyaratan",
    "Requirement" to "Persyaratan",
    "No requirement fact is supplied in the active case." to "Fakta persyaratan tidak disediakan dalam kasus aktif.",
    "Selected evidence in this draft" to "Bukti terpilih pada draf",
    "No supplied observations are selected." to "Belum ada pengamatan dipilih.",
    "Recorded relationship" to "Hubungan tercatat",
    "Student-recorded relation" to "Hubungan yang dicatat pelajar",
    "No relationship has been recorded by you." to "Anda belum mencatat hubungan.",
    "Evidence assessment" to "Penilaian bukti",
    "This bounded case check explains the current draft against supplied rules; it does not establish universal scientific truth." to "Pemeriksaan kasus terbatas menjelaskan draf sesuai aturan tersedia; tidak membuktikan kebenaran ilmiah universal.",
    "No claim-boundary fact is supplied in the active case." to "Fakta batas klaim tidak disediakan dalam kasus aktif.",
    "Available in active case" to "Tersedia dalam kasus aktif",
    "Unavailable in active case" to "Tidak tersedia dalam kasus aktif",
    "Present, but not an observation" to "Ada, tetapi bukan pengamatan",
    "Case context" to "Konteks kasus",
    "Stated limitation" to "Batasan dinyatakan",
    "Observed difference" to "Perbedaan teramati",
    "Limited observation" to "Pengamatan terbatas",
)
