package dev.nextgen.mobile

// App-owned presentation copy. Record IDs and learner content are never changed.
internal fun indonesianCopy0(): Map<String, String> = mapOf(
    "Evidence-change challenge" to "Tantangan perubahan bukti",
    "Revise" to "Revisi",
    "Your one revision" to "Satu revisi Anda",
    "Guided investigation" to "Penyelidikan terpandu",
    "Feedback checks the supplied case, not academic quality." to "Umpan balik memeriksa kasus ini, bukan kualitas akademis.",
    "Your draft stays with this practice." to "Draf Anda tetap berada dalam latihan ini.",
    "Previous practice task" to "Tugas latihan sebelumnya",
    "Review my conclusion" to "Tinjau kesimpulan saya",
    "A required input needs attention" to "Ada isian wajib yang perlu dilengkapi",
    "The evidence has changed" to "Buktinya berubah",
    "Evidence" to "Bukti",
    "Choose your interpretation. The case checks come after your complete draft." to "Pilih interpretasi Anda. Pemeriksaan kasus dilakukan setelah draf lengkap.",
    "Your claim" to "Klaim Anda",
    "What do your selected observations support?" to "Apa yang didukung pengamatan pilihan Anda?",
    "You already have this scope cue. You can edit it in your sentence." to "Petunjuk cakupan ini sudah ada. Anda dapat mengeditnya dalam kalimat Anda.",
    "Shorten the draft before adding this cue. Your wording has been kept." to "Pendekkan draf sebelum menambahkan petunjuk ini. Tulisan Anda tetap disimpan.",
    "Add an editable scope cue" to "Tambahkan petunjuk cakupan yang bisa diedit",
    "Keep the sentence yours. Use the selected records; avoid adding facts the case does not supply." to "Gunakan kalimat sendiri dan catatan terpilih. Jangan menambahkan fakta yang tidak tersedia dalam kasus.",
    "Your current claim" to "Klaim Anda saat ini",
    "Supplied limitation" to "Batasan dalam kasus",
    "Limitation" to "Batasan",
    "Why does this limit matter?" to "Mengapa batasan ini penting?",
    "Explain what the evidence leaves uncertain…" to "Jelaskan apa yang masih belum diketahui dari bukti…",
    "Why this next action?" to "Mengapa memilih langkah ini?",
    "Connect the action to a limitation you selected…" to "Hubungkan langkah ini dengan batasan yang Anda pilih…",
    "Leave practice" to "Keluar dari latihan",
    "Open practice hints and supplied facts" to "Buka petunjuk dan fakta latihan",
    "Synthetic practice data" to "Data latihan rekaan",
    "Available observation" to "Pengamatan tersedia",
    "Connected to your claim" to "Terhubung dengan klaim Anda",
    "Not selected" to "Belum dipilih",
    "Three evidence links already selected" to "Tiga hubungan bukti sudah dipilih",
    "Observation" to "Pengamatan",
    "Unavailable in this round" to "Tidak tersedia pada tahap ini",
    "The withdrawn observation is not part of this active evidence set." to "Pengamatan yang ditarik bukan bagian dari bukti aktif.",
    "Recorded time · seconds" to "Waktu tercatat · detik",
    "Evidence selected" to "Bukti dipilih",
    "No evidence connected yet" to "Belum ada bukti terhubung",
    "Some links are unavailable" to "Sebagian hubungan tidak tersedia",
    "Hide my selected evidence" to "Sembunyikan bukti pilihan saya",
    "View my selected evidence" to "Lihat bukti pilihan saya",
    "No available observation is connected. Go back to evidence to choose one." to "Belum ada pengamatan tersedia yang terhubung. Kembali ke bagian bukti untuk memilihnya.",
    "No claim written yet." to "Belum ada klaim ditulis.",
    "A hint, if you need it." to "Petunjuk, jika Anda membutuhkannya.",
    "Use the observations that answer the comparison question. The supplied hypothesis is a prediction, not a measured result." to "Gunakan pengamatan yang menjawab pertanyaan perbandingan. Hipotesis dalam kasus adalah prediksi, bukan hasil pengukuran.",
    "An observed difference describes the records. It does not establish what caused them." to "Perbedaan yang diamati menggambarkan catatan. Itu belum membuktikan penyebabnya.",
    "A cue such as “in these observations” can help you keep the claim bounded. Write the rest in your own words." to "Frasa seperti “dalam pengamatan ini” membantu membatasi klaim. Tulis sisanya dengan kata-kata Anda sendiri.",
    "Ask whether your wording describes these records or makes a promise about other situations." to "Apakah tulisan Anda menggambarkan catatan ini atau menjanjikan hasil dalam situasi lain?",
    "Explain how a supplied limitation constrains the conclusion. Keep uncertainty connected to evidence." to "Jelaskan bagaimana batasan dalam kasus membatasi kesimpulan. Hubungkan ketidakpastian dengan bukti.",
    "Choose an action that responds to a limitation you selected. A future trial does not retroactively prove this claim." to "Pilih langkah yang menjawab batasan terpilih. Percobaan berikutnya tidak membuktikan klaim ini secara surut.",
    "Read the evidence records and the reason behind the feedback. These checks apply to the supplied case only." to "Baca catatan bukti dan alasan umpan balik. Pemeriksaan ini hanya berlaku pada kasus yang disediakan.",
    "Supplied case facts" to "Fakta dalam kasus",
    "Start this practice over" to "Ulangi latihan ini",
    "Done" to "Selesai",
    "Start this practice over?" to "Ulangi latihan ini?",
    "Your current practice draft will be discarded and the workflow will return to its start." to "Draf latihan saat ini akan dihapus dan alur dimulai dari awal.",
    "Start over" to "Mulai ulang",
    "Keep my draft" to "Pertahankan draf saya",
    "Follow the reasoning." to "Ikuti penalarannya.",
    "Read what the selected facts support and what still needs attention." to "Baca apa yang didukung fakta terpilih dan apa yang masih perlu diperhatikan.",
    "Revise my conclusion" to "Revisi kesimpulan saya",
    "A smaller set. A fresh review." to "Bukti berkurang. Tinjau kembali.",
    "Feedback now uses only the observations available in the challenge." to "Umpan balik kini hanya memakai pengamatan yang tersedia dalam tantangan.",
    "See my comparison" to "Lihat perbandingan saya",
    "Case feedback" to "Umpan balik kasus",
    "Challenge feedback" to "Umpan balik tantangan",
    "Your current conclusion" to "Kesimpulan Anda saat ini",
    "Evidence you selected" to "Bukti yang Anda pilih",
    "A selected record is not available in this case version." to "Salah satu catatan terpilih tidak tersedia dalam versi kasus ini.",
    "Hide the earlier claim" to "Sembunyikan klaim sebelumnya",
    "Compare with the earlier claim" to "Bandingkan dengan klaim sebelumnya",
    "Before the evidence changed · retained" to "Sebelum bukti berubah · dipertahankan",
    "Hide the check details" to "Sembunyikan rincian pemeriksaan",
    "Inspect the case checks" to "Periksa pemeriksaan kasus",
    "No individual check results are available. Read the main feedback above." to "Hasil pemeriksaan terpisah belum tersedia. Baca umpan balik utama di atas.",
    "Case-bounded feedback. This is not an academic grade or proof of a real-world causal effect." to "Umpan balik terbatas pada kasus ini. Ini bukan nilai akademis atau bukti sebab akibat di dunia nyata.",
    "These case checks pass" to "Pemeriksaan kasus terpenuhi",
    "Review the available feedback" to "Tinjau umpan balik tersedia",
    "Your next move" to "Langkah Anda berikutnya",
    "Evidence behind this feedback" to "Bukti di balik umpan balik ini",
    "A referenced record is not available in this case version." to "Catatan yang dirujuk tidak tersedia dalam versi kasus ini.",
    "The supplied checks connect your evidence, scope, limitations, and next action." to "Pemeriksaan menghubungkan bukti, cakupan, batasan, dan langkah berikutnya.",
    "There is not enough check information to confirm a result." to "Informasi pemeriksaan belum cukup untuk memastikan hasil.",
    "Evidence checked" to "Bukti diperiksa",
    "Your evidence-change comparison" to "Perbandingan saat bukti berubah",
    "Start a new attempt" to "Mulai percobaan baru",
    "Explore practice" to "Jelajahi latihan",
    "You reconsidered the claim." to "Anda meninjau ulang klaim.",
    "When evidence changes, trace what still supports the conclusion." to "Saat bukti berubah, telusuri apa yang masih mendukung kesimpulan.",
    "Evidence → claim → next action" to "Bukti → klaim → langkah berikutnya",
    "Before the evidence changed" to "Sebelum bukti berubah",
    "With the available evidence" to "Dengan bukti tersedia",
    "What changed" to "Apa yang berubah",
    "Hide active records" to "Sembunyikan catatan aktif",
    "Inspect the active evidence" to "Periksa bukti aktif",
    "A move for your next project" to "Langkah untuk proyek berikutnya",
    "Link a claim to its sources. If a source changes or becomes unavailable, review the claim before reusing it." to "Hubungkan klaim dengan sumbernya. Jika sumber berubah atau tidak tersedia, tinjau klaim sebelum memakainya kembali.",
    "Use this move in my project" to "Gunakan langkah ini di proyek saya",
    "This is a synthetic practice case. The comparison is not a real experiment or an academic grade." to "Ini kasus latihan rekaan. Perbandingan ini bukan eksperimen nyata atau nilai akademis.",
    "Offline case · add your work in My Projects." to "Kasus luring · tambahkan pekerjaan Anda di Proyek Saya.",
    "Requirement supplied with this case" to "Persyaratan dalam kasus ini",
    "Bounded checks for this case" to "Pemeriksaan terbatas pada kasus ini",
    "Bundled observations and stated limits" to "Pengamatan dan batasan yang disediakan",
    "Project attachments stay source material until you choose and record a finding." to "Lampiran proyek tetap berupa materi sumber sampai Anda memilih dan mencatat temuan.",
    "Case workspace" to "Ruang kerja kasus",
    "Ready" to "Siap",
    "Not assessed" to "Belum dinilai",
    "Loading" to "Memuat",
    "Nothing here yet" to "Belum ada isi",
    "Offline" to "Luring",
    "Unavailable" to "Tidak tersedia",
    "Something went wrong" to "Terjadi kesalahan",
    "Action unavailable" to "Tindakan tidak tersedia",
    "Only this observation" to "Hanya pengamatan ini",
    "This limited comparison" to "Perbandingan terbatas ini",
    "A general causal claim" to "Klaim sebab akibat umum",
    "Unsupported scope" to "Cakupan tidak didukung",
    "Action" to "Tindakan",
    "Partially supported" to "Didukung sebagian",
    "Supported" to "Didukung",
    "Cannot assess" to "Belum dapat dinilai",
    "Review requirement trace" to "Tinjau jejak persyaratan",
    "Review the evidence gap" to "Tinjau celah bukti",
    "Review evidence links" to "Tinjau hubungan bukti",
    "Check unavailable evidence" to "Periksa bukti tidak tersedia",
    "See why this cannot be assessed" to "Lihat mengapa belum dapat dinilai",
    "Evidence anchors unchanged" to "Rujukan bukti tidak berubah",
    "Evidence anchors changed" to "Rujukan bukti berubah",
    "Claim revision saved" to "Revisi klaim disimpan",
    "Changed-evidence response saved" to "Tanggapan perubahan bukti disimpan",
    "Local comparison saved" to "Perbandingan lokal disimpan",
    "Evaluate support independently from the learner's next action." to "Nilai dukungan bukti secara terpisah dari langkah pelajar berikutnya.",
    "No comparison saved yet" to "Belum ada perbandingan disimpan",
    "One revision is ready to review" to "Satu revisi siap ditinjau",
    "Review your latest before/after comparison" to "Tinjau perbandingan sebelum dan sesudah terbaru",
    "Challenge context" to "Konteks tantangan",
    "Explain this feedback" to "Jelaskan umpan balik ini",
    "Understand the current deterministic feedback." to "Pahami umpan balik pemeriksaan saat ini.",
    "Why this action?" to "Mengapa langkah ini?",
    "See how the next action connects to the current result." to "Lihat hubungan langkah berikutnya dengan hasil saat ini.",
    "Help me reflect" to "Bantu saya berefleksi",
    "Get one bounded question to guide your own revision." to "Dapatkan satu pertanyaan terbatas untuk memandu revisi sendiri.",
    "Why can't this be assessed?" to "Mengapa belum bisa dinilai?",
    "Explain this result" to "Jelaskan hasil ini",
    "Clarify the current evaluator result without changing it." to "Perjelas hasil pemeriksaan saat ini tanpa mengubahnya.",
    "Complete the missing part" to "Lengkapi bagian yang belum terisi",
    "Identify what's missing" to "Cari informasi yang belum tersedia",
    "Check the claim boundary" to "Periksa batas klaim",
    "Reconsider the claim boundary" to "Tinjau ulang batas klaim",
    "Get one question grounded in the current result." to "Dapatkan satu pertanyaan berdasarkan hasil saat ini.",
    "Clarify the limitation" to "Perjelas batasan",
    "Clarify the next action" to "Perjelas langkah berikutnya",
    "Try narrower wording" to "Coba cakupan lebih sempit",
    "Review an optional wording suggestion; it will not edit your draft automatically." to "Tinjau saran kalimat opsional; draf Anda tidak diedit otomatis.",
    "Title" to "Judul",
    "Observe" to "Amati",
    "Compare" to "Bandingkan",
    "Reconsider" to "Tinjau ulang",
    "Investigation progress" to "Progres penyelidikan",
    "D adds a different recall finding: no observed difference at 14 days. Its new context stays visible alongside A and B." to "D menambahkan temuan ingatan yang berbeda: tidak ada perbedaan teramati setelah 14 hari. Konteks barunya tetap terlihat bersama A dan B.",
    "Quiet space" to "Ruang tenang",
    "Group space" to "Ruang kelompok",
    "Hide the anonymous rows" to "Sembunyikan baris anonim",
    "Inspect the anonymous rows" to "Periksa baris anonim",
    "quiet space" to "ruang tenang",
    "group space" to "ruang kelompok",
    "Fictional identifiers. The sample is small and self-selected." to "Identitas rekaan. Sampelnya kecil dan peserta memilih sendiri untuk ikut.",
    "Read context, method and limit" to "Baca konteks, metode, dan batasan",
    "Method" to "Metode",
    "Limit" to "Batasan",
    "Similar" to "Serupa",
    "Different" to "Berbeda",
    "similar finding" to "temuan serupa",
    "different finding" to "temuan berbeda",
    "context, a different outcome" to "konteks, hasil berbeda",
    "Similar describes a reported direction; it does not mean the methods or effect sizes are interchangeable." to "Serupa menggambarkan arah hasil yang dilaporkan; metode atau besaran efeknya belum tentu dapat dibandingkan langsung.",
    "changed set" to "bukti berubah",
    "initial set" to "bukti awal",
    "No record connected." to "Belum ada catatan terhubung.",
    "COUNT-QUIET · 4/7 unique respondents" to "COUNT-QUIET · 4/7 responden unik",
)
