package dev.nextgen.mobile

// App-owned presentation copy. Record IDs and learner content are never changed.
internal fun indonesianCopy1(): Map<String, String> = mapOf(
    "COUNT-QUIET · 5/8 submitted rows" to "COUNT-QUIET · 5/8 baris jawaban",
    "COUNT-GROUP · 3/7 unique respondents" to "COUNT-GROUP · 3/7 responden unik",
    "COUNT-GROUP · 3/8 submitted rows" to "COUNT-GROUP · 3/8 baris jawaban",
    "After removing R07 · 7 unique respondents" to "Setelah R07 dihapus · 7 responden unik",
    "Initial survey · 8 submitted rows" to "Survei awal · 8 baris jawaban",
    "One fictional campus · self-selected sample" to "Satu kampus rekaan · sampel sukarela",
    "Share of the active set · 0–100%" to "Bagian dari data aktif · 0–100%",
    "Section navigation" to "Navigasi bagian",
    "Close sections" to "Tutup daftar bagian",
    "Moving between sections" to "Berpindah antarbagian",
    "Work is saved before moving to another section. If that save fails, this panel stays open and your current work is retained. Swipe left or touch outside to close." to "Pekerjaan disimpan sebelum berpindah bagian. Jika gagal, panel tetap terbuka dan pekerjaan Anda dipertahankan. Geser ke kiri atau sentuh di luar panel untuk menutup.",
    "Untitled project" to "Proyek tanpa judul",
    "Open project map" to "Buka peta proyek",
    "Local save feedback" to "Status penyimpanan lokal",
    "Not saved" to "Belum disimpan",
    "Saved" to "Tersimpan",
    "Your workspace" to "Ruang kerja Anda",
    "Move between sections. Your work is saved before switching." to "Berpindah antarbagian. Pekerjaan disimpan sebelum berpindah.",
    "Preview file" to "Pratinjau berkas",
    "About these exports" to "Tentang ekspor ini",
    "Reports contain your recorded material, not verified research. The .evproj archive preserves project data, revision history, and verified attachments for recovery. CSV cells that may act as formulas are prefixed with an apostrophe; review values in your spreadsheet app." to "Laporan berisi materi yang Anda catat, bukan penelitian terverifikasi. Arsip .evproj menyimpan data proyek, riwayat revisi, dan lampiran terverifikasi untuk pemulihan. Sel CSV yang mungkin terbaca sebagai rumus diawali apostrof; tinjau nilainya di aplikasi spreadsheet.",
    "Untitled source" to "Sumber tanpa judul",
    "Evidence note" to "Catatan bukti",
    "Empty note" to "Catatan kosong",
    "Empty finding" to "Temuan kosong",
    "Comparison" to "Perbandingan",
    "Untitled comparison" to "Perbandingan tanpa judul",
    "Empty claim" to "Klaim kosong",
    "Boundary / next action" to "Batasan / langkah berikutnya",
    "Empty boundary" to "Batasan kosong",
    "Recorded source" to "Sumber tercatat",
    "Selected for comparison" to "Dipilih untuk perbandingan",
    "Affected by boundary" to "Terpengaruh batasan",
    "Close project map" to "Tutup peta proyek",
    "Show graph" to "Tampilkan graf",
    "Show list" to "Tampilkan daftar",
    "All records" to "Semua catatan",
    "Connected" to "Terhubung",
    "No linked records yet. Switch to All records to find your next connection." to "Belum ada catatan terhubung. Pilih Semua catatan untuk mencari hubungan berikutnya.",
    "Explore sideways. Tap a record to follow its connections." to "Jelajahi ke samping. Sentuh catatan untuk mengikuti hubungannya.",
    "Context · dashed" to "Konteks · putus-putus",
    "Next actions" to "Langkah berikutnya",
    "Supports, contradicts and context are relationships you selected, not Evidrilo verdicts. Placement does not imply a link. Source-level legacy claim links are not converted into note-to-claim relationships. This map uses the current project material, including unsaved changes, and does not upload it." to "Dukungan, pertentangan, dan konteks adalah hubungan pilihan Anda, bukan putusan Evidrilo. Posisi tidak menandakan hubungan. Hubungan klaim lama pada tingkat sumber tidak diubah menjadi hubungan catatan–klaim. Peta ini memakai materi proyek saat ini, termasuk perubahan belum tersimpan, tanpa mengunggahnya.",
    "Synthetic preview · campus shade" to "Pratinjau rekaan · peneduh kampus",
    "Supplied reading A" to "Bacaan contoh A",
    "Supplied reading B" to "Bacaan contoh B",
    "Shade reduced exposure in the supplied example." to "Peneduh mengurangi paparan dalam contoh yang disediakan.",
    "The second setting had different surfaces and measurements." to "Lokasi kedua memakai permukaan dan pengukuran berbeda.",
    "Shade may reduce exposure in this supplied example." to "Peneduh mungkin mengurangi paparan dalam contoh ini.",
    "Selected within the example's scope." to "Dipilih dalam cakupan contoh.",
    "Recorded challenge to transferring the result to another campus." to "Tantangan tercatat untuk menerapkan hasil ke kampus lain.",
    "Campus applicability is unknown." to "Kesesuaian untuk kampus ini belum diketahui.",
    "Compare local conditions." to "Bandingkan kondisi setempat.",
    "Open recorded links" to "Buka hubungan tercatat",
    "No project with a supported AI stage is available yet. Your saved projects remain available in Home." to "Belum ada proyek dengan tahap AI yang didukung. Proyek tersimpan tetap tersedia di Beranda.",
    "AI service is not configured in this build." to "Layanan AI belum dikonfigurasi dalam versi ini.",
    "A verified account is required. Sign in again before sending a message." to "Akun terverifikasi diperlukan. Masuk kembali sebelum mengirim pesan.",
    "Your account session expired. Sign in again before sending a message." to "Sesi akun berakhir. Masuk kembali sebelum mengirim pesan.",
    "Secure session storage is unavailable; the message was not sent." to "Penyimpanan sesi aman tidak tersedia; pesan belum dikirim.",
    "General Chat is not enabled by the platform right now. Your message was not answered; your project remains available." to "Chat umum belum diaktifkan platform. Pesan belum dijawab; proyek tetap tersedia.",
    "The AI service is temporarily unavailable. No answer was shown. Try again later." to "Layanan AI sementara tidak tersedia. Belum ada jawaban ditampilkan. Coba lagi nanti.",
    "Account-level AI data-use consent is missing or out of date. Refresh and review consent before sending again." to "Persetujuan penggunaan data AI belum ada atau kedaluwarsa. Muat ulang dan tinjau sebelum mengirim kembali.",
    "There are not enough AI credits for this request. No answer was returned." to "Kredit AI tidak cukup untuk permintaan ini. Belum ada jawaban diberikan.",
    "Confirm the General chat notice for this message, then try again." to "Konfirmasikan pemberitahuan chat umum untuk pesan ini, lalu coba lagi.",
    "The response could not be verified, so it was not displayed. Check your credit balance before sending again." to "Jawaban tidak dapat diverifikasi sehingga tidak ditampilkan. Periksa saldo kredit sebelum mengirim kembali.",
    "We could not confirm whether the request completed. It may have used credits; check your AI credit balance before sending again." to "Penyelesaian permintaan belum dapat dipastikan. Kredit mungkin terpakai; periksa saldo AI sebelum mengirim kembali.",
    "The device appears offline. Reconnect before sending this message." to "Perangkat tampaknya luring. Sambungkan internet sebelum mengirim pesan.",
    "The request failed. No response was shown." to "Permintaan gagal. Belum ada jawaban ditampilkan.",
    "AI chat shortcut. Tap to open AI modes. Drag to move." to "Pintasan chat AI. Sentuh untuk membuka mode AI. Geser untuk memindahkan.",
    "Move AI shortcut to upper left" to "Pindahkan pintasan AI ke kiri atas",
    "Move AI shortcut to upper right" to "Pindahkan pintasan AI ke kanan atas",
    "Move AI shortcut to lower left" to "Pindahkan pintasan AI ke kiri bawah",
    "Move AI shortcut to lower right" to "Pindahkan pintasan AI ke kanan bawah",
    "Selected project excerpt" to "Cuplikan proyek terpilih",
    "Only this message will be sent after your explicit approval. No original files. AI usage consumes credits." to "Hanya pesan ini yang dikirim setelah persetujuan Anda. Tanpa berkas asli. Penggunaan AI memakai kredit.",
    "AI is not connected in this build" to "AI belum terhubung dalam versi ini",
    "Your account needs attention" to "Akun Anda perlu diperiksa",
    "Review AI data use before asking" to "Tinjau penggunaan data AI sebelum bertanya",
    "Check AI consent before sending" to "Periksa persetujuan AI sebelum mengirim",
    "Choose the help you need" to "Pilih bantuan yang dibutuhkan",
    "Keep working locally. Questions and project material are not sent from this build." to "Lanjutkan secara lokal. Pertanyaan dan materi proyek tidak dikirim dari versi ini.",
    "You choose what to share. Each request keeps its own context and confirmation." to "Anda memilih apa yang dibagikan. Setiap permintaan memiliki konteks dan konfirmasinya sendiri.",
    "Consent status needs to be checked. Open a chat to check it before sending." to "Status persetujuan perlu diperiksa. Buka chat untuk memeriksanya sebelum mengirim.",
    "Your account and connection are configured. Service availability is checked when you send a request." to "Akun dan koneksi sudah dikonfigurasi. Ketersediaan layanan diperiksa saat mengirim permintaan.",
    "Ask a study question. No project is connected." to "Ajukan pertanyaan belajar. Tanpa proyek terhubung.",
    "Project AI" to "AI proyek",
    "Reading your supported project stages…" to "Membaca tahap proyek yang didukung…",
    "No supported project yet. Local starters remain available for manual work." to "Belum ada proyek didukung. Panduan lokal tetap tersedia untuk pekerjaan manual.",
    "Choose an eligible project" to "Pilih proyek yang memenuhi syarat",
    "Only a published template with a declared AI operation appears here. The server rechecks the template and project revision; other work remains manual." to "Hanya template terbit dengan operasi AI yang dinyatakan muncul di sini. Server memeriksa kembali template dan revisi proyek; pekerjaan lainnya tetap manual.",
    "Create or open a project" to "Buat atau buka proyek",
    "Project excerpt · AI opinion" to "Cuplikan proyek · pendapat AI",
    "Review selected excerpt" to "Tinjau cuplikan terpilih",
    "This project changed. Close chat and prepare a fresh excerpt from Review before sending." to "Proyek berubah. Tutup chat dan siapkan cuplikan baru dari Tinjauan sebelum mengirim.",
    "Each request sends only its current message. Earlier turns are not sent or saved to account history." to "Setiap permintaan hanya mengirim pesan saat ini. Percakapan sebelumnya tidak dikirim atau disimpan ke riwayat akun.",
    "Checking account consent…" to "Memeriksa persetujuan akun…",
    "The platform requires account-level AI data-use consent. Granting it sends nothing; each message still needs separate approval. Only the text you choose in the composer is sent." to "Platform memerlukan persetujuan penggunaan data AI pada akun. Persetujuan saja tidak mengirim data; setiap pesan tetap perlu izin terpisah. Hanya teks pilihan Anda di kolom pesan yang dikirim.",
    "Check consent again" to "Periksa persetujuan kembali",
    "The Evidrilo AI API is not configured in this build. No message can be sent; your project remains usable manually." to "API AI Evidrilo belum dikonfigurasi dalam versi ini. Pesan belum dapat dikirim; proyek tetap bisa dikerjakan manual.",
    "Open account" to "Buka akun",
    "Start with" to "Mulai dengan",
    "Help me turn an assignment into a focused research question." to "Bantu saya mengubah tugas menjadi pertanyaan penelitian yang terarah.",
    "What should I check before saying evidence supports a claim?" to "Apa yang perlu diperiksa sebelum menyatakan bukti mendukung klaim?",
    "Help me choose a manageable next step for my project." to "Bantu saya memilih langkah berikutnya yang realistis untuk proyek.",
    "Ask a general study question" to "Ajukan pertanyaan belajar umum",
    "Allow this message to be sent to AI. Actual verified usage (up to 200 credits) is charged; a reply is not guaranteed." to "Izinkan pesan ini dikirim ke AI. Penggunaan terverifikasi sebenarnya (hingga 200 kredit) ditagihkan; jawaban belum tentu tersedia.",
    "Send message" to "Kirim pesan",
    "AI workspace" to "Ruang kerja AI",
    "AI activity" to "Aktivitas AI",
    "Choose a separate chat or project workspace" to "Pilih chat terpisah atau ruang kerja proyek",
    "1 shared AI credit" to "1 kredit AI bersama",
    "Evidrilo Pro" to "Evidrilo Pro",
    "More projects. The full Practice trail." to "Lebih banyak proyek. Semua jalur latihan.",
    "Make room for more." to "Beri ruang untuk lebih banyak.",
    "200 AI credits each active month" to "200 kredit AI setiap bulan aktif",
    "Credits & access" to "Kredit dan akses",
    "Pro needs verified subscription access. Free receives 20 AI credits once after account verification and AI consent; active Pro adds 200 each month, including annual plans. Earned credits accumulate and do not expire. AI needs internet, consent and an available service. Your first Practice case stays Free." to "Pro memerlukan akses langganan terverifikasi. Free mendapat 20 kredit AI sekali setelah verifikasi akun dan persetujuan AI; Pro aktif menambah 200 setiap bulan, termasuk paket tahunan. Kredit terkumpul dan tidak kedaluwarsa. AI membutuhkan internet, persetujuan, dan layanan tersedia. Latihan pertama tetap Free.",
    "Visual preview · no account, provider or payment is connected." to "Pratinjau visual · tanpa akun, penyedia, atau pembayaran terhubung.",
    "This visual preview cannot restore or change a subscription." to "Pratinjau ini tidak dapat memulihkan atau mengubah langganan.",
    "Plans come from the provider. This preview does not connect to it." to "Paket berasal dari penyedia. Pratinjau ini tidak terhubung dengannya.",
    "Close preview" to "Tutup pratinjau",
    "Retry projects" to "Coba memuat proyek lagi",
    "Your practice" to "Latihan Anda",
    "Practice progress couldn't be read." to "Progres latihan belum dapat dibaca.",
    "Continue your attempt" to "Lanjutkan percobaan Anda",
    "Completed practice stays recorded, even when Pro access ends." to "Latihan yang selesai tetap tercatat meskipun akses Pro berakhir.",
    "Recorded progress" to "Progres tercatat",
    "Projects and notes come from this device. Response bars count required fields with recorded content; finished cases come from saved Practice sessions. These counts are not grades or assessments of research quality. Previously finished Pro cases remain history, not proof of current access." to "Proyek dan catatan berasal dari perangkat ini. Indikator isian menghitung isian wajib dengan isi tercatat; kasus selesai berasal dari sesi latihan tersimpan. Angka ini bukan nilai atau penilaian kualitas penelitian. Kasus Pro yang pernah selesai tetap menjadi riwayat, bukan bukti akses saat ini.",
    "Recorded count" to "Jumlah tercatat",
    "Close full-screen review" to "Tutup tinjauan layar penuh",
    "Full screen" to "Layar penuh",
    "Sign in with a verified account to manage Project AI consent. No context was sent." to "Masuk dengan akun terverifikasi untuk mengelola persetujuan AI proyek. Konteks belum dikirim.",
    "Sign in with a verified account to use Project AI. Your local project remains available; no context was sent." to "Masuk dengan akun terverifikasi untuk memakai AI proyek. Proyek lokal tetap tersedia; konteks belum dikirim.",
    "The saved consent policy is out of date. Grant consent again before sending project context." to "Kebijakan persetujuan tersimpan kedaluwarsa. Berikan persetujuan ulang sebelum mengirim konteks proyek.",
    "Project AI consent is not configured in this build." to "Persetujuan AI proyek belum dikonfigurasi dalam versi ini.",
    "Sign in with a verified account to manage project AI consent." to "Masuk dengan akun terverifikasi untuk mengelola persetujuan AI proyek.",
    "Your session expired. Sign in again to manage project AI consent." to "Sesi Anda berakhir. Masuk kembali untuk mengelola persetujuan AI proyek.",
    "Secure session storage is unavailable; consent could not be checked." to "Penyimpanan sesi aman tidak tersedia; persetujuan belum dapat diperiksa.",
    "Your session is no longer authorized. Sign in again before managing project AI consent." to "Sesi Anda tidak lagi diizinkan. Masuk kembali sebelum mengelola persetujuan AI proyek.",
    "This account cannot manage project AI consent. No project context was sent." to "Akun ini tidak dapat mengelola persetujuan AI proyek. Konteks belum dikirim.",
    "The project AI consent policy changed. Review and grant consent again." to "Kebijakan persetujuan AI proyek berubah. Tinjau dan berikan persetujuan ulang.",
    "You are offline. Project AI consent could not be checked; project work stays local." to "Anda luring. Persetujuan AI proyek belum dapat diperiksa; pekerjaan tetap lokal.",
    "Project AI is not configured in this build. Your project remains usable manually." to "AI proyek belum dikonfigurasi dalam versi ini. Proyek tetap dapat dikerjakan manual.",
    "Sign in with a verified account before requesting project AI." to "Masuk dengan akun terverifikasi sebelum meminta bantuan AI proyek.",
    "Your session expired. Sign in again; your local project is unchanged." to "Sesi Anda berakhir. Masuk kembali; proyek lokal tidak berubah.",
    "Secure session storage is unavailable. No AI request was sent." to "Penyimpanan sesi aman tidak tersedia. Permintaan AI belum dikirim.",
    "Project AI is not enabled yet. No AI-generated content or credits were produced; continue manually." to "AI proyek belum diaktifkan. Konten AI atau kredit belum dihasilkan; lanjutkan manual.",
    "The request may have completed, but its credit settlement could not be confirmed. Check your shared AI balance before retrying; your project is unchanged." to "Permintaan mungkin selesai, tetapi penagihan kredit belum terkonfirmasi. Periksa saldo AI bersama sebelum mencoba lagi; proyek tidak berubah.",
    "Project AI is temporarily unavailable. Your project and manual workflow remain available." to "AI proyek sementara tidak tersedia. Proyek dan alur manual tetap tersedia.",
    "Project AI consent changed or is out of date. Refresh and review consent before another request. Your project was not changed." to "Persetujuan AI proyek berubah atau kedaluwarsa. Muat ulang dan tinjau sebelum meminta lagi. Proyek tidak berubah.",
    "The request outcome is unknown. Check your shared AI balance before retrying; no project fields were applied." to "Hasil permintaan belum diketahui. Periksa saldo AI bersama sebelum mencoba lagi; tidak ada isian proyek diterapkan.",
    "You are offline. Project work stays local; reconnect before asking AI." to "Anda luring. Pekerjaan tetap lokal; sambungkan internet sebelum bertanya kepada AI.",
    "Project AI could not complete this request. Your project was not changed." to "AI proyek belum dapat menyelesaikan permintaan ini. Proyek tidak berubah.",
    "My project" to "Proyek saya",
    "Create with project AI" to "Buat dengan AI proyek",
    "Ask about this project" to "Tanyakan tentang proyek ini",
    "AI can help frame your assignment and suggest editable project fields. It does not verify research quality, supply evidence, or replace your decision." to "AI membantu merumuskan tugas dan menyarankan isian yang dapat diedit. AI tidak memverifikasi kualitas penelitian, menyediakan bukti, atau menggantikan keputusan Anda.",
    "Project AI requires an account and separate consent, and is disabled in this build. You can create and edit local projects without signing in." to "AI proyek membutuhkan akun dan persetujuan terpisah, serta dinonaktifkan dalam versi ini. Proyek lokal dapat dibuat dan diedit tanpa masuk.",
    "What does your assignment ask you to do?" to "Apa yang diminta dalam tugas Anda?",
    "Use your own instructions; do not include names or sensitive participant details." to "Gunakan instruksi sendiri; jangan sertakan nama atau data sensitif peserta.",
    "Save your current project edits before asking AI so the request is bound to the saved revision." to "Simpan perubahan proyek sebelum bertanya kepada AI agar permintaan terikat pada revisi tersimpan.",
    "Add your assignment brief in the project fields below before asking AI." to "Tambahkan instruksi tugas pada isian proyek di bawah sebelum bertanya kepada AI.",
    "AI context comes from your current assignment brief and the fields you have entered." to "Konteks AI berasal dari instruksi tugas dan isian yang Anda masukkan.",
    "What would you like help with? (optional)" to "Bantuan apa yang Anda perlukan? (opsional)",
    "For example: help me make the question more specific, or suggest a manageable next step." to "Contoh: perjelas pertanyaan saya, atau sarankan langkah berikutnya yang realistis.",
    "Choose saved project fields to include (none selected by default)" to "Pilih isian proyek tersimpan untuk disertakan (tidak ada dipilih secara bawaan)",
    "Check saved account consent" to "Periksa persetujuan akun tersimpan",
    "Checking saved account consent…" to "Memeriksa persetujuan akun tersimpan…",
    "Project AI needs a separate, revocable account-level consent before project context can be sent. Granting it does not send project data by itself." to "AI proyek membutuhkan persetujuan akun terpisah yang dapat dicabut sebelum mengirim konteks. Memberi persetujuan tidak langsung mengirim data proyek.",
    "Allow project AI data processing" to "Izinkan pemrosesan data AI proyek",
    "Revocable account consent is saved. It does not include project files or send data by itself." to "Persetujuan akun yang dapat dicabut tersimpan. Berkas proyek tidak disertakan dan data tidak dikirim otomatis.",
    "Check again" to "Periksa kembali",
    "For this request only, send the assignment brief, optional question, and selected saved fields to Evidrilo's AI endpoint. Source files are excluded. Nothing is applied or saved from a response until I confirm." to "Untuk permintaan ini saja, kirim instruksi tugas, pertanyaan opsional, dan isian tersimpan terpilih ke layanan AI Evidrilo. Berkas sumber tidak disertakan. Jawaban tidak diterapkan atau disimpan sebelum saya mengonfirmasi.",
    "Project AI is optional and may be unavailable when the API or provider is offline or not enabled. Each request needs your confirmation; manual project work remains available. Revoking consent stops future requests but cannot recall data already sent." to "AI proyek opsional dan mungkin tidak tersedia saat API atau penyedia luring atau belum aktif. Setiap permintaan perlu konfirmasi; pekerjaan manual tetap tersedia. Pencabutan persetujuan menghentikan permintaan berikutnya, tetapi tidak menarik kembali data terkirim.",
    "Checking project AI availability…" to "Memeriksa ketersediaan AI proyek…",
    "Retry recording choice" to "Coba mencatat pilihan lagi",
    "Request AI suggestions" to "Minta saran AI",
    "Review your AI draft" to "Tinjau draf AI Anda",
    "AI draft · review before using" to "Draf AI · tinjau sebelum dipakai",
    "This is a suggestion, not verified academic guidance. Check it against your assignment and instructor's requirements." to "Ini saran, bukan panduan akademis terverifikasi. Cocokkan dengan tugas dan ketentuan pengajar Anda.",
)
