package dev.nextgen.mobile

internal val AdditionalIndonesianCopy=mapOf(
    "Cloud progress sync" to "Sinkronisasi progres awan",
    "Local sync storage is unavailable; no cloud sync is active." to "Penyimpanan sinkronisasi lokal tidak tersedia; sinkronisasi awan tidak aktif.",
    "Sign in to sync minimal progress metadata. Draft text stays on this device." to "Masuk untuk menyinkronkan metadata progres minimal. Teks draf tetap di perangkat.",
    "Off by default. Enable it to sync minimal progress metadata; draft text stays local." to "Nonaktif secara bawaan. Aktifkan untuk menyinkronkan metadata progres minimal; teks draf tetap lokal.",
    "Ready. Only redacted progress metadata syncs; draft text stays local." to "Siap. Hanya metadata progres disunting disinkronkan; teks draf tetap lokal.",
    "Sign in or create an account" to "Masuk atau buat akun",
    "Local projects stay on this device. Account sign-in is optional and does not upload projects. Pro requires a signed-in account and a confirmed entitlement. AI also needs internet, a verified account, consent, credits and an available service." to "Proyek lokal tetap di perangkat. Masuk opsional dan tidak mengunggah proyek. Pro membutuhkan akun yang masuk dan akses terkonfirmasi. AI juga memerlukan internet, akun terverifikasi, persetujuan, kredit, dan layanan tersedia.",
    "Preparing account sign-in" to "Menyiapkan masuk akun",
    "Sign-in is in progress. Account features will be ready when it finishes; local projects remain available." to "Proses masuk berjalan. Fitur akun siap setelah selesai; proyek lokal tetap tersedia.",
    "Finish sign-in" to "Selesaikan masuk",
    "Finish sign-in in your browser, then return to Evidrilo. Local projects remain available." to "Selesaikan masuk di browser, lalu kembali ke Evidrilo. Proyek lokal tetap tersedia.",
    "You are signed in on this device. Online AI and Pro have their own service and access checks. Local projects stay here; signing in does not upload them." to "Anda masuk di perangkat ini. AI daring dan Pro memiliki pemeriksaan layanan serta akses masing-masing. Proyek tetap lokal; masuk tidak mengunggahnya.",
    "Sign-in expired" to "Sesi masuk berakhir",
    "Sign-in expired and was removed from this device. Your local project data is still here; sign in again to use account features." to "Sesi masuk berakhir dan dihapus dari perangkat. Data proyek lokal tetap ada; masuk kembali untuk fitur akun.",
    "Choose a new password" to "Pilih kata sandi baru",
    "Your recovery link was verified. Choose a new password to finish recovering this account." to "Tautan pemulihan terverifikasi. Pilih kata sandi baru untuk menyelesaikan pemulihan akun.",
    "Local only · Sign-in optional" to "Hanya lokal · Masuk opsional",
    "Signing in securely" to "Masuk dengan aman",
    "Account request not confirmed" to "Permintaan akun belum terkonfirmasi",
    "Finish password recovery" to "Selesaikan pemulihan kata sandi",
    "Sign-in unavailable · Local projects stay here" to "Masuk tidak tersedia · Proyek tetap lokal",
    "Welcome back" to "Selamat datang kembali",
    "Create your account" to "Buat akun Anda",
    "Reset your password" to "Reset kata sandi",
    "Secure storage unavailable" to "Penyimpanan aman tidak tersedia",
    "Account service unavailable" to "Layanan akun tidak tersedia",
    "Account response could not be verified" to "Jawaban akun gagal diverifikasi",
    "Request outcome not confirmed" to "Hasil permintaan belum terkonfirmasi",
    "Credentials not verified" to "Kredensial belum terverifikasi",
    "Check the account details" to "Periksa rincian akun",
    "Too many attempts" to "Terlalu banyak percobaan",
    "Export exceeds size limit" to "Ekspor melewati batas ukuran",
    "Confirm your email" to "Konfirmasikan email",
    "Check your email" to "Periksa email",
    "Sign-in cancelled" to "Masuk dibatalkan",
    "Sign-in link was not accepted" to "Tautan masuk ditolak",
    "Transfer ownership first" to "Alihkan kepemilikan dahulu",
    "The account session could not be accessed safely. No token was shown or copied; try signing in again." to "Sesi akun gagal diakses aman. Token tidak ditampilkan atau disalin; coba masuk kembali.",
    "The account service is unavailable offline, so Evidrilo cannot verify your session. Reconnect and retry; no cloud sync was attempted." to "Layanan akun tidak tersedia luring; sesi belum dapat diverifikasi. Sambungkan internet lalu coba lagi; sinkronisasi belum dicoba.",
    "The account service could not complete this request. Retry when it is available; your local project data has not been deleted." to "Layanan akun gagal menyelesaikan permintaan. Coba saat tersedia; data proyek lokal tidak dihapus.",
    "The account provider returned data Evidrilo could not verify. No unverified session was stored; try signing in again." to "Penyedia akun memberikan data tidak terverifikasi. Sesi tersebut tidak disimpan; coba masuk kembali.",
    "The account service may have processed this request even though its response was lost. Check the account state before repeating a change." to "Layanan akun mungkin memproses permintaan meski jawaban hilang. Periksa status akun sebelum mengulang perubahan.",
    "The credentials could not be verified. Check them and try again; no account data was disclosed." to "Kredensial gagal diverifikasi. Periksa lalu coba lagi; data akun tidak dibocorkan.",
    "The account details need attention. Correct them and try again; no credentials were stored." to "Rincian akun perlu diperiksa. Perbaiki lalu coba lagi; kredensial tidak disimpan.",
    "Please wait before trying again. No credentials were stored." to "Tunggu sebelum mencoba lagi. Kredensial tidak disimpan.",
    "This account export exceeds the current size limit and could not be downloaded. No account data was changed." to "Ekspor akun melewati batas ukuran saat ini dan gagal diunduh. Data akun tidak berubah.",
    "Confirm the email address from the message we sent, then sign in." to "Konfirmasikan alamat email melalui pesan kami, lalu masuk.",
    "If that address can receive mail, a reset message was requested. Sign in again after resetting your password." to "Jika alamat dapat menerima email, pesan reset telah diminta. Masuk kembali setelah reset kata sandi.",
    "Sign-in was cancelled. You can retry or choose email sign-in." to "Masuk dibatalkan. Coba lagi atau gunakan email.",
    "The sign-in callback could not be verified. No unverified session was stored; retry sign-in." to "Hasil pengalihan masuk gagal diverifikasi. Sesi tidak terverifikasi tidak disimpan; coba masuk kembali.",
    "Sign-in is not available in this build. Local projects remain available, and no project data was changed." to "Masuk tidak tersedia dalam versi ini. Proyek lokal tetap tersedia dan datanya tidak berubah.",
    "This account is the only active owner of an organization. Transfer ownership before deleting it." to "Akun ini satu-satunya pemilik aktif organisasi. Alihkan kepemilikan sebelum menghapusnya.",
    "Account creation may have completed. Check for a verification email or try signing in before repeating the request." to "Pembuatan akun mungkin selesai. Periksa email verifikasi atau coba masuk sebelum mengulang permintaan.",
    "A password reset email may have been requested. Check your inbox before requesting another." to "Email reset mungkin sudah diminta. Periksa kotak masuk sebelum meminta lagi.",
    "Your password change may have completed. Verify which password works before submitting another change." to "Perubahan kata sandi mungkin selesai. Periksa kata sandi yang berfungsi sebelum mengubah lagi.",
    "Account deletion may have completed. Check the account state before repeating the deletion; do not assume the remote account was deleted or remains active." to "Penghapusan akun mungkin selesai. Periksa status sebelum mengulang; jangan mengasumsikan akun sudah dihapus atau masih aktif.",
    "A short evidence review is ready to begin." to "Tinjauan bukti singkat siap dimulai.",
    "A focused review can help turn your latest feedback into a next step." to "Tinjauan terarah membantu mengubah umpan balik terbaru menjadi langkah berikutnya.",
    "A bounded follow-up review is ready when you are." to "Tinjauan lanjutan terbatas siap saat Anda siap.",
    "Suggested next review" to "Saran tinjauan berikutnya",
    "Start suggested review" to "Mulai saran tinjauan",
    "Not now" to "Nanti saja",
    "Dismiss" to "Tutup",
    "Current: " to "Saat ini: ",
    "Project map" to "Peta proyek",
    "Reading this map" to "Cara membaca peta",
    "Close record" to "Tutup catatan",
    "No explicit links recorded." to "Belum ada hubungan eksplisit tercatat.",
    "Your map starts with your material." to "Peta dimulai dari materi Anda.",
    "Record a source, then add notes and explicit links. Nothing is filled in for you." to "Catat sumber, lalu tambahkan catatan dan hubungan eksplisit. Isi tidak dibuat otomatis.",
    "In these observations, " to "Dalam pengamatan ini, ",
    "You can try again." to "Anda dapat mencoba lagi.",
    "Manual project work remains available." to "Pekerjaan proyek manual tetap tersedia.",
    "The local project remains available." to "Proyek lokal tetap tersedia.",
    "Account features remain unavailable until sign-in works again; local projects remain usable." to "Fitur akun belum tersedia hingga proses masuk kembali berfungsi; proyek lokal tetap dapat dipakai.",
    "Free case" to "Kasus Free",
    "Pro case" to "Kasus Pro",
    "synthetic practice material" to "materi latihan rekaan",
    "A useful hypothesis names a relationship you can check, then states its limits. Start with these supplied observations:" to "Hipotesis yang berguna menyebut hubungan yang dapat diperiksa, lalu batasannya. Mulai dengan pengamatan tersedia:",
    "Try: ‘If [condition changes], then [observed outcome] may change within this case.’ What other condition would you need to control before making a broader claim?" to "Coba: ‘Jika [kondisi berubah], maka [hasil teramati] mungkin berubah dalam kasus ini.’ Kondisi lain apa yang perlu dikendalikan sebelum membuat klaim lebih luas?",
)
