package dev.nextgen.mobile

// App-owned presentation copy. Record IDs and learner content are never changed.
internal fun indonesianCopy13(): Map<String, String> = mapOf(
    "Separate missing and non-response counts from the responses that were analyzed." to "Pisahkan jumlah data hilang dan tanpa respons dari jawaban yang dianalisis.",
    "Use clear, neutral wording and describe response options in text." to "Gunakan kalimat jelas dan netral serta jelaskan opsi jawaban dalam teks.",
    "Provide a text summary for any chart or visual comparison." to "Sediakan ringkasan teks untuk grafik atau perbandingan visual.",
    "Synthesize literature for a focused question" to "Sintesis literatur untuk pertanyaan terarah",
    "Compare selected sources and explain how their findings, methods, or limits relate." to "Bandingkan sumber terpilih dan jelaskan hubungan temuan, metode, atau batasannya.",
    "A directed literature-synthesis outline. It does not claim to be a systematic or exhaustive review." to "Kerangka sintesis literatur terarah. Tidak mengklaim sebagai tinjauan sistematis atau menyeluruh.",
    "What focused question will the selected literature help address?" to "Pertanyaan terarah apa yang dijawab literatur terpilih?",
    "Which topic, population, time period, or source types are in scope?" to "Topik, populasi, periode, atau jenis sumber apa yang termasuk cakupan?",
    "Where and when did you look, and why did each source fit? Do not call the search exhaustive unless it was designed and checked as such." to "Di mana/kapan Anda mencari, dan mengapa sumber sesuai? Jangan menyebut pencarian menyeluruh jika tidak dirancang dan diperiksa demikian.",
    "Which concepts, methods, outcomes, or limitations will you compare?" to "Konsep, metode, hasil ukur, atau batasan apa yang dibandingkan?",
    "What themes, agreements, differences, or gaps appear across the selected sources?" to "Tema, kesepakatan, perbedaan, atau celah apa yang muncul antarsumber?",
    "What answer is supported by the sources you actually selected?" to "Jawaban apa yang didukung sumber yang benar-benar Anda pilih?",
    "Which sources, perspectives, or search limits may change the synthesis?" to "Sumber, perspektif, atau batas pencarian apa yang mungkin mengubah sintesis?",
    "What source check or comparison would most improve the synthesis?" to "Pemeriksaan sumber atau perbandingan apa yang paling memperbaiki sintesis?",
    "Frame the question and scope" to "Rumuskan pertanyaan dan cakupan",
    "Record where sources came from" to "Catat asal sumber",
    "Compare sources on shared dimensions" to "Bandingkan sumber pada dimensi sama",
    "State a source-bounded answer" to "Nyatakan jawaban terbatas pada sumber",
    "Check coverage and next action" to "Periksa cakupan dan langkah berikutnya",
    "This starter supports a directed synthesis; it does not establish a systematic search or exhaustive coverage." to "Panduan mendukung sintesis terarah; tidak membuktikan pencarian sistematis atau cakupan menyeluruh.",
    "A complete citation does not by itself verify a source's quality, relevance, or accuracy." to "Sitasi lengkap saja tidak memverifikasi kualitas, relevansi, atau akurasi sumber.",
    "Keep claims tied to the sources and passages you inspected, including disagreement and limitations." to "Hubungkan klaim dengan sumber serta kutipan diperiksa, termasuk perbedaan pendapat dan batasan.",
    "Keep the source citation, retrieval location or date, and page or section locator when available." to "Simpan sitasi, lokasi/tanggal pengambilan, serta halaman/bagian jika tersedia.",
    "Record search terms and source-selection reasons when they matter to the assignment; never imply a database search that was not performed." to "Catat kata pencarian dan alasan pemilihan jika relevan; jangan menyiratkan pencarian basis data yang tidak dilakukan.",
    "Keep source notes and synthesis readable as text; use descriptive headings instead of color-only labels." to "Jaga catatan dan sintesis terbaca sebagai teks; gunakan judul deskriptif, bukan label warna saja.",
    "Record page or section locators in text so another reader can find the cited passage." to "Catat halaman/bagian dalam teks agar pembaca dapat menemukan kutipan.",
    "Organize an interview or field study" to "Tata wawancara atau studi lapangan",
    "Keep a qualitative question, collection context, anonymized notes, and interpretations connected." to "Hubungkan pertanyaan kualitatif, konteks pengumpulan, catatan anonim, dan interpretasi.",
    "A local organizer for an interview or field-study assignment. It does not approve participant research or ethics procedures." to "Pengelola lokal tugas wawancara/studi lapangan. Tidak memberi izin penelitian peserta atau prosedur etika.",
    "What experience, meaning, or setting are you trying to understand?" to "Pengalaman, makna, atau situasi apa yang ingin dipahami?",
    "What non-identifying setting and context are relevant?" to "Situasi dan konteks tanpa identitas apa yang relevan?",
    "What instructor, consent, privacy, or ethics requirements must be met before collection? Do not enter names or contact details." to "Ketentuan pengajar, persetujuan, privasi, atau etika apa yang diperlukan sebelum pengumpulan? Jangan masukkan nama atau kontak.",
    "What interview prompts or observation protocol will you use?" to "Pertanyaan wawancara atau protokol pengamatan apa yang dipakai?",
    "Which de-identified notes or excerpts are relevant to the question?" to "Catatan tanpa identitas atau kutipan apa yang relevan?",
    "What tentative themes appear, and what notes do not fit them?" to "Tema sementara apa yang muncul, dan catatan apa yang tidak sesuai?",
    "What interpretation is supported by these contextualized notes?" to "Interpretasi apa yang didukung catatan berkonteks ini?",
    "Which context, participant perspectives, or collection choices limit this interpretation?" to "Konteks, perspektif peserta, atau pilihan pengumpulan apa yang membatasi interpretasi?",
    "What additional context or review would help before drawing a broader conclusion?" to "Konteks tambahan atau tinjauan apa yang membantu sebelum kesimpulan lebih luas?",
    "Frame the inquiry and setting" to "Rumuskan penyelidikan dan situasi",
    "Check permission and privacy first" to "Periksa izin dan privasi dahulu",
    "Plan interviews or field observations" to "Rencanakan wawancara atau pengamatan lapangan",
    "Organize de-identified notes" to "Tata catatan tanpa identitas",
    "Interpret themes and exceptions" to "Tafsirkan tema dan pengecualian",
    "Review boundaries and next action" to "Tinjau batas dan langkah berikutnya",
    "Do not collect participant information until the instructor and applicable consent or ethics requirements are satisfied." to "Jangan kumpulkan informasi peserta sebelum ketentuan pengajar dan persetujuan/etika terpenuhi.",
    "Do not store names, contact details, or direct identifiers in project notes; use an approved privacy-safe approach." to "Jangan simpan nama, kontak, atau identitas langsung dalam catatan; gunakan pendekatan aman yang disetujui.",
    "A theme is an interpretation. Keep context, exceptions, and the underlying note visible." to "Tema adalah interpretasi. Perlihatkan konteks, pengecualian, dan catatan dasarnya.",
    "Record the protocol version and a non-identifying collection context; use approved participant codes rather than identities." to "Catat versi protokol dan konteks tanpa identitas; gunakan kode peserta yang disetujui, bukan identitas.",
    "Keep each excerpt linked to its note or location without copying confidential material into an unapproved service." to "Hubungkan kutipan ke catatan/lokasinya tanpa menyalin materi rahasia ke layanan belum disetujui.",
    "Keep prompts and notes available as selectable text; provide text transcripts for any audio relied on in analysis." to "Sediakan pertanyaan dan catatan sebagai teks yang dapat dipilih; sertakan transkrip untuk audio yang dipakai analisis.",
    "Use clear labels for speaker or field-note roles without using personal identifiers." to "Gunakan label jelas untuk peran pembicara/catatan lapangan tanpa identitas pribadi.",
    "Design, build, and test a solution" to "Rancang, bangun, dan uji solusi",
    "Connect a defined need and requirements to design choices and observed test results." to "Hubungkan kebutuhan dan persyaratan dengan pilihan desain serta hasil uji teramati.",
    "A project outline that compares a prototype or design against stated criteria and explains remaining trade-offs." to "Kerangka proyek membandingkan prototipe/desain dengan kriteria dan menjelaskan kompromi tersisa.",
    "What need or technical problem is in scope, and for whom? Avoid unnecessary personal data." to "Kebutuhan atau masalah teknis apa yang tercakup, dan untuk siapa? Hindari data pribadi tidak diperlukan.",
    "What requirements or success criteria must the solution meet?" to "Persyaratan atau kriteria keberhasilan apa yang perlu dipenuhi?",
    "What resources, safety, time, accessibility, or technical limits apply?" to "Batas sumber daya, keselamatan, waktu, aksesibilitas, atau teknis apa yang berlaku?",
    "Which design choices were made, and what alternatives were considered?" to "Pilihan desain apa yang dibuat dan alternatif apa yang dipertimbangkan?",
    "What prototype or implementation version was tested?" to "Versi prototipe atau implementasi apa yang diuji?",
    "What test conditions and criteria will be used?" to "Kondisi dan kriteria uji apa yang dipakai?",
    "What happened during each test, including conditions and failures?" to "Apa yang terjadi pada setiap uji, termasuk kondisi dan kegagalan?",
    "How did observed results compare with each stated criterion?" to "Bagaimana hasil teramati dibandingkan dengan setiap kriteria?",
    "What does the tested version demonstrate within these conditions?" to "Apa yang ditunjukkan versi diuji dalam kondisi ini?",
    "What remains untested or could affect performance or user suitability?" to "Apa yang belum diuji atau dapat memengaruhi kinerja/kesesuaian pengguna?",
    "What test or design change would reduce the most important remaining limit?" to "Uji atau perubahan desain apa yang mengurangi batas tersisa paling penting?",
    "Define the need and context" to "Tentukan kebutuhan dan konteks",
    "Set requirements and constraints" to "Tentukan persyaratan dan batasan",
    "Record design and prototype" to "Catat desain dan prototipe",
    "Test against stated criteria" to "Uji sesuai kriteria",
    "Review trade-offs and next action" to "Tinjau kompromi dan langkah berikutnya",
    "Passing a stated test does not by itself establish broad usability, safety, reliability, or real-world impact." to "Lulus uji tertentu saja tidak membuktikan kemudahan pakai luas, keselamatan, keandalan, atau dampak nyata.",
    "Separate observed test results from design expectations and interpretations." to "Pisahkan hasil uji teramati dari perkiraan desain dan interpretasi.",
    "User feedback or safety claims may require appropriate consent, specialist review, and testing beyond this organizer." to "Masukan pengguna atau klaim keselamatan mungkin memerlukan persetujuan, tinjauan ahli, dan pengujian di luar pengelola ini.",
    "Record the requirement source, prototype or design version, test conditions, and the criteria used." to "Catat asal persyaratan, versi prototipe/desain, kondisi uji, dan kriteria.",
    "Keep unsuccessful tests and deviations alongside successful results; do not report only the best run." to "Simpan kegagalan serta penyimpangan bersama keberhasilan; jangan hanya melaporkan percobaan terbaik.",
    "State accessibility-related requirements explicitly and report which were actually tested." to "Nyatakan kebutuhan aksesibilitas dan laporkan yang benar-benar diuji.",
    "Pair diagrams or measurements with text labels and units that can be read without relying on color alone." to "Sertai diagram atau pengukuran dengan label dan satuan teks yang dapat dibaca tanpa hanya mengandalkan warna.",
)
