package dev.nextgen.mobile

// App-owned presentation copy. Record IDs and learner content are never changed.
internal fun indonesianCopy12(): Map<String, String> = mapOf(
    "Another small sample, material, and follow-up. It does not erase A or B." to "Sampel kecil, materi, dan waktu lanjutan berbeda. Hasil ini tidak menghapus A atau B.",
    "When studies tell different stories" to "Ketika studi memberi cerita berbeda",
    "One response changes the picture" to "Satu jawaban mengubah gambaran",
    "Trace a claim back to observations." to "Telusuri klaim ke pengamatan.",
    "Synthesize findings without flattening their differences." to "Sintesis temuan tanpa menghilangkan perbedaannya.",
    "Reconsider a claim when its data changes." to "Tinjau ulang klaim saat data berubah.",
    "What can the supplied dissolution times tell you about these three water conditions?" to "Apa yang ditunjukkan waktu pelarutan tersedia tentang tiga kondisi air ini?",
    "What do three supplied cards support about quiz practice and rereading?" to "Apa yang didukung tiga kartu tentang latihan kuis dan membaca ulang?",
    "What can a small, self-selected survey tell you about study-space preferences?" to "Apa yang ditunjukkan survei kecil sukarela tentang preferensi ruang belajar?",
    "The times may differ." to "Waktunya mungkin berbeda.",
    "I need to see the observations." to "Saya perlu melihat pengamatan.",
    "The times may be similar." to "Waktunya mungkin serupa.",
    "The findings may agree." to "Temuannya mungkin sejalan.",
    "Different methods may matter." to "Metode berbeda mungkin berpengaruh.",
    "I want to inspect the cards first." to "Saya ingin memeriksa kartu dahulu.",
    "The counts may suggest a preference." to "Jumlahnya mungkin menunjukkan preferensi.",
    "The sample may limit the claim." to "Sampel mungkin membatasi klaim.",
    "I need to inspect the records first." to "Saya perlu memeriksa catatan dahulu.",
    "A small sample does not represent every student." to "Sampel kecil tidak mewakili semua pelajar.",
    "Recall time, method, population, and preference are different." to "Waktu ingatan, metode, populasi, dan preferensi berbeda.",
    "Respondents chose to participate at one fictional campus." to "Responden memilih sendiri untuk ikut di satu kampus rekaan.",
    "Include a broader, planned sample" to "Gunakan sampel terencana lebih luas",
    "Compare the same outcome and follow-up" to "Bandingkan hasil ukur dan waktu lanjutan sama",
    "Treat this as conclusive proof" to "Anggap sebagai bukti pasti",
    "Keep all findings and reconsider the pattern" to "Pertahankan semua temuan dan tinjau ulang pola",
    "Discard A and B because D differs" to "Buang A dan B karena D berbeda",
    "Say quiz practice always works better" to "Nyatakan latihan kuis selalu lebih baik",
    "Keep R03 and remove only duplicate R07" to "Pertahankan R03 dan hapus hanya duplikat R07",
    "Keep both submissions as two respondents" to "Hitung kedua jawaban sebagai dua responden",
    "Remove both of C's submissions" to "Hapus kedua jawaban C",
    "Use the tablet evaluator" to "Gunakan pemeriksa tablet",
    "The tablet case is assessed by the existing conclusion evaluator." to "Kasus tablet dinilai dengan pemeriksa kesimpulan yang sudah ada.",
    "Return to the tablet workflow." to "Kembali ke alur tablet.",
    "Active evidence" to "Bukti aktif",
    "Every selected link belongs to this synthetic evidence set." to "Semua hubungan terpilih termasuk kumpulan bukti rekaan ini.",
    "An absent or unknown link cannot support this case." to "Hubungan hilang atau tidak dikenal tidak mendukung kasus ini.",
    "Inspect and select available records." to "Periksa dan pilih catatan tersedia.",
    "Compare like outcomes" to "Bandingkan hasil ukur sejenis",
    "A and B both record higher recall after quiz practice on their own measures. C measures preference, so its result is context, not a recall contradiction." to "A dan B mencatat ingatan lebih tinggi setelah latihan kuis pada pengukuran masing-masing. C mengukur preferensi; hasilnya memberi konteks, bukan pertentangan hasil ingatan.",
    "Keep A/B's observed pattern distinct from C's preference result; do not pool unlike measures." to "Pisahkan pola A/B dari preferensi C; jangan gabungkan pengukuran berbeda.",
    "Support the comparison" to "Dukung perbandingan",
    "D's 5/10 versus 5/10 adds a no-difference finding. A and B are retained; the combined pattern is mixed across these contexts." to "Hasil D 5/10 dibanding 5/10 menambah temuan tanpa perbedaan. A dan B dipertahankan; pola gabungan bervariasi antarkonteks.",
    "A and B are the two supplied recall comparisons. A synthesis that compares them needs links to both." to "A dan B adalah dua perbandingan ingatan tersedia. Sintesis perbandingan memerlukan hubungan ke keduanya.",
    "Connect D as well as A/B and reconsider the wording." to "Hubungkan D bersama A/B dan tinjau ulang kalimat.",
    "Link both recall comparisons." to "Hubungkan kedua perbandingan ingatan.",
    "Counts and denominator" to "Jumlah dan penyebut",
    "After removing R07 only, four of seven unique respondents prefer quiet space. Three prefer group space." to "Setelah hanya R07 dihapus, empat dari tujuh responden unik memilih ruang tenang. Tiga memilih ruang kelompok.",
    "Five of eight submitted rows prefer quiet space; three prefer group space. These are submission counts before duplicate review." to "Lima dari delapan baris jawaban memilih ruang tenang; tiga ruang kelompok. Ini jumlah sebelum pemeriksaan duplikat.",
    "Keep the count, denominator, and sampling boundary in view." to "Perlihatkan jumlah, penyebut, dan batas sampel.",
    "Reach of the claim" to "Cakupan klaim",
    "Small, different source contexts do not establish one causal rule for all students." to "Konteks sumber kecil dan berbeda tidak membuktikan aturan sebab akibat untuk semua pelajar.",
    "A small, self-selected survey at one campus does not establish every student's preference or a cause." to "Survei kecil sukarela di satu kampus tidak membuktikan preferensi semua pelajar atau penyebab.",
    "Limit the declared scope to the supplied records." to "Batasi cakupan dinyatakan pada catatan tersedia.",
    "Limit and next action" to "Batasan dan langkah berikutnya",
    "A wider sampling limitation calls for planned broader sampling; unlike outcomes call for a comparable measure. Neither turns the present claim into proof." to "Batas sampel memerlukan sampel terencana lebih luas; hasil ukur berbeda memerlukan pengukuran sebanding. Keduanya tidak membuat klaim saat ini menjadi bukti pasti.",
    "Choose a next action that responds to your selected limitation." to "Pilih langkah yang menjawab batasan pilihan Anda.",
    "Choose a decision before reviewing its consequence." to "Pilih keputusan sebelum meninjau akibatnya.",
    "D adds a no-difference observation. Keep A and B, include D, and reconsider how far the pattern reaches. C still measures preference." to "D menambah pengamatan tanpa perbedaan. Pertahankan A/B, sertakan D, dan tinjau cakupan pola. C tetap mengukur preferensi.",
    "D differs on another sample and follow-up. It neither erases A/B nor supports an always-better claim. Reconsider with all active cards." to "D berbeda pada sampel serta waktu lanjutan lain. Tidak menghapus A/B atau mendukung klaim selalu lebih baik. Tinjau semua kartu aktif.",
    "R07 repeats respondent C's R03 submission. Retain R03, remove only R07: quiet 5/8 becomes 4/7; group 3/8 becomes 3/7." to "R07 mengulang jawaban C pada R03. Pertahankan R03, hapus hanya R07: ruang tenang 5/8 menjadi 4/7; kelompok 3/8 menjadi 3/7.",
    "R03 is C's retained response. Removing both would exclude that respondent entirely. Remove only the duplicated submission R07." to "R03 adalah jawaban C yang dipertahankan. Menghapus keduanya mengeluarkan responden tersebut sepenuhnya. Hapus hanya duplikat R07.",
    "Counting R03 and R07 as two people double-counts C. Keep the retained R03 and remove only R07." to "Menghitung R03 dan R07 sebagai dua orang menghitung C dua kali. Pertahankan R03 dan hapus hanya R07.",
    "Tablet dissolution · water temperature" to "Pelarutan tablet · suhu air",
    "Compare supplied dissolution observations across three water temperatures." to "Bandingkan pengamatan pelarutan pada tiga suhu air.",
    "Compare dissolution time across warm, room-temperature, and cold water." to "Bandingkan waktu pelarutan pada air hangat, suhu ruang, dan dingin.",
    "The case hypothesis expects faster dissolution in warmer water." to "Hipotesis kasus memperkirakan pelarutan lebih cepat dalam air lebih hangat.",
    "Warm water: 32 seconds." to "Air hangat: 32 detik.",
    "Warm" to "Hangat",
    "Room temperature: 58 seconds." to "Suhu ruang: 58 detik.",
    "Room" to "Suhu ruang",
    "Cold water: 92 seconds." to "Air dingin: 92 detik.",
    "Cold" to "Dingin",
    "Each condition was measured once." to "Setiap kondisi diukur sekali.",
    "Stirring speed was not measured with an instrument." to "Kecepatan pengadukan tidak diukur dengan alat.",
    "The case does not establish a general causal effect." to "Kasus belum membuktikan sebab akibat umum.",
    "Tablet dissolution · evidence change" to "Pelarutan tablet · perubahan bukti",
    "Rebuild the comparison after the cold-water observation is unavailable." to "Susun ulang perbandingan setelah pengamatan air dingin tidak tersedia.",
    "Evidence change: the cold-water observation is unavailable in this round." to "Perubahan bukti: pengamatan air dingin tidak tersedia pada tahap ini.",
    "Tablet form · whole versus crushed" to "Bentuk tablet · utuh dan dihancurkan",
    "Compare two supplied dissolution observations while keeping the claim bounded." to "Bandingkan dua pengamatan pelarutan dengan klaim tetap terbatas.",
    "Compare dissolution time for a whole tablet and a crushed tablet in room-temperature water." to "Bandingkan waktu pelarutan tablet utuh dan dihancurkan pada air suhu ruang.",
    "The case hypothesis expects the crushed tablet to dissolve faster." to "Hipotesis kasus memperkirakan tablet dihancurkan larut lebih cepat.",
    "Whole tablet: 74 seconds." to "Tablet utuh: 74 detik.",
    "Whole" to "Utuh",
    "Crushed tablet: 41 seconds." to "Tablet dihancurkan: 41 detik.",
    "Crushed" to "Dihancurkan",
    "Each tablet form was measured once." to "Setiap bentuk tablet diukur sekali.",
    "Water volume · 100 mL versus 200 mL" to "Volume air · 100 mL dan 200 mL",
    "Compare supplied dissolution observations across two water volumes." to "Bandingkan pengamatan pelarutan pada dua volume air.",
    "Compare dissolution time in 100 mL and 200 mL of room-temperature water." to "Bandingkan waktu pelarutan pada 100 mL dan 200 mL air suhu ruang.",
    "The case hypothesis expects the water volume to change the observed dissolution time." to "Hipotesis kasus memperkirakan volume air mengubah waktu pelarutan teramati.",
    "100 mL: 52 seconds." to "100 mL: 52 detik.",
    "200 mL: 61 seconds." to "200 mL: 61 detik.",
    "Each water volume was measured once." to "Setiap volume air diukur sekali.",
    "Cannot assess this case safely from the supplied information." to "Kasus belum dapat dinilai aman dari informasi tersedia.",
    "The case configuration does not satisfy the evaluator contract." to "Konfigurasi kasus tidak memenuhi aturan pemeriksa.",
    "Return to a supported case and try again." to "Kembali ke kasus didukung dan coba lagi.",
    "The value is outside the supported input contract." to "Nilai di luar bentuk masukan didukung.",
    "Choose one of the supported options shown by the case." to "Pilih salah satu opsi didukung pada kasus.",
    "Cannot assess a case outside the supported case." to "Kasus di luar dukungan belum dapat dinilai.",
    "The selected case ID is not supported by this evaluator." to "ID kasus terpilih tidak didukung pemeriksa ini.",
    "Return to the supplied case and use its supported facts." to "Kembali ke kasus tersedia dan gunakan fakta didukung.",
    "Choose at least one observation fact ID before submitting." to "Pilih minimal satu ID fakta pengamatan sebelum mengirim.",
    "The supported input contract allows at most three evidence fact IDs." to "Masukan didukung maksimal tiga ID fakta bukti.",
    "Choose no more than three OBS-* fact IDs." to "Pilih maksimal tiga ID fakta OBS-*.",
    "Write a claim between 20 and 320 characters." to "Tulis klaim dalam 20–320 karakter.",
    "Choose the scope of this conclusion." to "Pilih cakupan kesimpulan.",
    "Choose at least one supplied limitation fact ID." to "Pilih minimal satu ID fakta batasan tersedia.",
    "The supported input contract allows at most two limitation fact IDs." to "Masukan didukung maksimal dua ID fakta batasan.",
    "Choose no more than two LIMIT-* fact IDs." to "Pilih maksimal dua ID fakta LIMIT-*.",
    "Explain the limitation in 10 to 240 characters." to "Jelaskan batasan dalam 10–240 karakter.",
    "Choose a supported next action." to "Pilih langkah berikutnya yang didukung.",
    "Explain the next action in 10 to 240 characters." to "Jelaskan langkah berikutnya dalam 10–240 karakter.",
    "The evaluator cannot make a quality judgement until this field is complete." to "Pemeriksa belum dapat menilai sebelum isian lengkap.",
    "Complete the highlighted field, then submit again." to "Lengkapi isian ditandai, lalu kirim kembali.",
    "Cannot assess this input shape safely." to "Bentuk masukan belum dapat dinilai aman.",
    "Cannot assess this evidence reference from the supplied case." to "Rujukan bukti belum dapat dinilai dari kasus tersedia.",
    "Choose only OBS-* fact IDs shown on the case card." to "Pilih hanya ID fakta OBS-* pada kartu kasus.",
    "Cannot assess this limitation reference from the supplied case." to "Rujukan batasan belum dapat dinilai dari kasus tersedia.",
    "Choose only LIMIT-* fact IDs shown on the case card." to "Pilih hanya ID fakta LIMIT-* pada kartu kasus.",
    "The free-text claim does not state what this case cannot establish." to "Klaim teks bebas belum menyatakan yang tidak dapat dibuktikan kasus.",
    "Explain the limitation of the case instead of asserting the observed difference." to "Jelaskan batasan kasus, alih-alih menyatakan perbedaan teramati.",
    "Remove the unsupported literal or select a supported fact ID." to "Hapus nilai tidak didukung atau pilih ID fakta didukung.",
    "The bounded evaluator cannot safely resolve a negation in learner-authored text." to "Pemeriksa terbatas tidak dapat menafsirkan negasi tulisan pelajar dengan aman.",
    "Use the structured relation and a non-contradictory bounded claim." to "Gunakan hubungan terstruktur dan klaim terbatas yang tidak bertentangan.",
    "The supplied facts do not provide a safe causal explanation for this claim." to "Fakta tersedia tidak memberikan penjelasan sebab akibat aman untuk klaim.",
    "Limit the claim to the observed comparison and supplied limitations." to "Batasi klaim pada perbandingan teramati dan batasan tersedia.",
    "Cannot assess this claim safely from the supplied information." to "Klaim belum dapat dinilai aman dari informasi tersedia.",
    "Limit the scope; the supplied case does not establish a general causal effect." to "Batasi cakupan; kasus belum membuktikan sebab akibat umum.",
    "Choose this observation or limited comparison and explain its limitation." to "Pilih pengamatan ini atau perbandingan terbatas, lalu jelaskan batasannya.",
    "Select at least two observation fact IDs for this comparison." to "Pilih minimal dua ID fakta pengamatan untuk perbandingan.",
    "A difference claim needs a supplied comparator, not one observation alone." to "Klaim perbedaan memerlukan pembanding tersedia, bukan satu pengamatan saja.",
    "Add another OBS-* fact ID from the case card." to "Tambahkan ID fakta OBS-* lain dari kartu kasus.",
    "Connect this next action to the limitation it addresses." to "Hubungkan langkah berikutnya dengan batasan yang dijawab.",
    "Select the matching limitation fact ID and explain the connection." to "Pilih ID fakta batasan sesuai dan jelaskan hubungannya.",
    "Plan and record an experiment" to "Rencanakan dan catat eksperimen",
    "Organize a planned change, a measured outcome, and the conditions around each trial." to "Tata perubahan terencana, hasil terukur, dan kondisi setiap percobaan.",
    "A project outline for an experiment or laboratory assignment. You provide the procedure, measurements, and interpretation." to "Kerangka proyek eksperimen atau tugas laboratorium. Anda menyediakan prosedur, pengukuran, dan interpretasi.",
    "What does the assignment ask you to produce?" to "Hasil apa yang diminta dalam tugas?",
    "What condition will you change and what outcome will you measure?" to "Kondisi apa yang diubah dan hasil apa yang diukur?",
    "Optional: what result do you expect, and why?" to "Opsional: hasil apa yang diperkirakan, dan mengapa?",
    "What will be compared, what will stay the same, and how many trials are planned?" to "Apa yang dibandingkan, apa yang tetap sama, dan berapa percobaan direncanakan?",
    "What steps and equipment will be used?" to "Langkah dan peralatan apa yang dipakai?",
    "Which values, units, trial numbers, and measurement conditions must be recorded?" to "Nilai, satuan, nomor percobaan, dan kondisi pengukuran apa yang perlu dicatat?",
    "What pattern do the recorded measurements show?" to "Pola apa yang ditunjukkan pengukuran tercatat?",
    "What does this set of trials support, within the tested conditions?" to "Apa yang didukung percobaan ini dalam kondisi diuji?",
    "Which uncontrolled condition or measurement limit narrows the interpretation?" to "Kondisi tidak terkendali atau batas pengukuran apa yang mempersempit interpretasi?",
    "What repeat or measurement would help address that limit?" to "Pengulangan atau pengukuran apa yang menjawab batasan tersebut?",
    "Frame the test" to "Rumuskan pengujian",
    "Plan the comparison" to "Rencanakan perbandingan",
    "Record measurements" to "Catat pengukuran",
    "Interpret the pattern" to "Tafsirkan pola",
    "Review limits and next action" to "Tinjau batasan dan langkah berikutnya",
    "A difference in one or a few trials does not by itself establish what caused it." to "Perbedaan pada satu atau beberapa percobaan saja belum membuktikan penyebab.",
    "Keep any conclusion within the materials, measurements, and conditions actually tested." to "Batasi kesimpulan sesuai materi, pengukuran, dan kondisi yang benar-benar diuji.",
    "A hypothesis is optional; include one only when it fits the assignment." to "Hipotesis opsional; sertakan hanya jika sesuai tugas.",
    "Record units, trial identifiers, instrument or setup details, and when measurements were taken." to "Catat satuan, identitas percobaan, rincian alat/setup, dan waktu pengukuran.",
    "Keep original observations separate from later calculations and interpretations." to "Pisahkan pengamatan asli dari perhitungan dan interpretasi berikutnya.",
    "Write units and condition names in text; do not rely on chart color or position alone." to "Tulis satuan dan nama kondisi; jangan hanya mengandalkan warna atau posisi grafik.",
    "Keep procedures and measurements readable as text that can be enlarged or read by assistive technology." to "Jaga prosedur dan pengukuran terbaca sebagai teks yang dapat diperbesar atau dibaca teknologi bantu.",
    "Observe a pattern or survey responses" to "Amati pola atau jawaban survei",
    "Organize observations or responses without assigning an intervention." to "Tata pengamatan atau jawaban tanpa memberikan intervensi.",
    "A project outline that records who or what was observed, how information was collected, and what the data can represent." to "Kerangka proyek yang mencatat siapa/apa diamati, cara pengumpulan, dan keterwakilan data.",
    "What pattern, experience, or response are you studying?" to "Pola, pengalaman, atau jawaban apa yang dipelajari?",
    "Who or what could be included, and how will cases be selected?" to "Siapa/apa yang dapat disertakan, dan bagaimana pemilihannya?",
    "What observation protocol or survey questions will be used?" to "Protokol pengamatan atau pertanyaan survei apa yang dipakai?",
    "When, where, and under what conditions are observations or responses collected?" to "Kapan, di mana, dan dalam kondisi apa pengamatan/jawaban dikumpulkan?",
    "What response counts, measurements, or recurring patterns are present?" to "Jumlah jawaban, pengukuran, atau pola berulang apa yang ada?",
    "What can you say about this sample or setting without extending beyond it?" to "Apa yang dapat dinyatakan tentang sampel atau situasi ini tanpa memperluas cakupan?",
    "Who may be missing, and how could sampling or question wording affect the pattern?" to "Siapa yang belum tercakup, dan bagaimana sampel atau kalimat pertanyaan memengaruhi pola?",
    "What additional observation or response would clarify the pattern?" to "Pengamatan atau jawaban tambahan apa yang memperjelas pola?",
    "Define the question and group" to "Tentukan pertanyaan dan kelompok",
    "Plan observation or survey collection" to "Rencanakan pengamatan atau survei",
    "Record what was observed" to "Catat yang diamati",
    "Describe the pattern" to "Gambarkan pola",
    "Check who the pattern represents" to "Periksa siapa yang diwakili pola",
    "An association or response pattern does not establish cause and effect." to "Hubungan atau pola jawaban tidak membuktikan sebab akibat.",
    "Sampling, non-response, setting, and question wording can affect what the results represent." to "Sampel, tanpa respons, situasi, dan kalimat pertanyaan dapat memengaruhi keterwakilan hasil.",
    "A survey or observation starter does not replace instructor approval, consent, or ethics requirements." to "Panduan survei/pengamatan tidak menggantikan persetujuan pengajar, peserta, atau etika.",
    "Record the observation or survey dates, setting, selection rules, and the exact question or protocol version." to "Catat tanggal, situasi, aturan pemilihan, dan versi pertanyaan/protokol yang tepat.",
)
