package dev.nextgen.mobile

// App-owned presentation copy. Record IDs and learner content are never changed.
internal fun indonesianCopy8(): Map<String, String> = mapOf(
    "Work on this next" to "Kerjakan ini berikutnya",
    "Assignment responses" to "Jawaban tugas",
    "Add your first source" to "Tambahkan sumber pertama",
    "Record a note from your source" to "Catat bukti dari sumber Anda",
    "Claim relationships" to "Hubungan klaim",
    "Draft a claim from your notes" to "Susun klaim dari catatan",
    "Scope and limits" to "Cakupan dan batasan",
    "Add a claim, then record its limits" to "Tambahkan klaim, lalu catat batasan",
    "Link integrity" to "Keutuhan hubungan",
    "Explore project map" to "Jelajahi peta proyek",
    "Ask for an AI opinion" to "Minta pendapat AI",
    "Optional · uses AI credits" to "Opsional · memakai kredit AI",
    "Review the saved excerpt before sending. AI gives suggestions, not a verdict; it may be wrong." to "Tinjau cuplikan tersimpan sebelum mengirim. AI memberi saran, bukan putusan; jawaban mungkin salah.",
    "Review context with AI" to "Tinjau konteks dengan AI",
    "What these checks mean" to "Arti pemeriksaan ini",
    "Explainable checks" to "Pemeriksaan yang dapat dijelaskan",
    "Checks count required responses, nonempty records and explicit relationships. Recorded boundaries and links do not prove a claim. Missing references mean a linked record is absent. These checks cannot evaluate methods, scientific truth, citation credibility or academic quality. The same required-field rules follow your selected project structure." to "Pemeriksaan menghitung jawaban wajib, catatan berisi, dan hubungan eksplisit. Batasan serta hubungan tercatat tidak membuktikan klaim. Rujukan hilang berarti catatan tujuan tidak ada. Metode, kebenaran ilmiah, kredibilitas sitasi, dan kualitas akademis tidak dinilai. Aturan isian wajib mengikuti struktur proyek terpilih.",
    "Skip" to "Lewati",
    "Make yourself at home." to "Mulai dengan nyaman.",
    "Choose your language. You can change it in Settings anytime." to "Pilih bahasa. Ubah kapan saja di Pengaturan.",
    "About 2–3 minutes · at your pace" to "Sekitar 2–3 menit · ikuti ritme Anda",
    "Workspace section preview" to "Pratinjau bagian ruang kerja",
    "Record who wrote it and where you found it." to "Catat penulis dan tempat Anda menemukannya.",
    "Keep a useful passage and its source together." to "Simpan kutipan berguna bersama sumbernya.",
    "Write what your notes support, then record the limits." to "Tulis yang didukung catatan, lalu catat batasannya.",
    "Choose a section to explore · temporary preview" to "Pilih bagian untuk dijelajahi · pratinjau sementara",
    "Illustrative map · not saved" to "Peta ilustrasi · tidak disimpan",
    "A source gives the note its origin. Keep its details traceable." to "Sumber menunjukkan asal catatan. Jaga rincian agar dapat ditelusuri.",
    "A note carries a passage or observation into your reasoning." to "Catatan membawa kutipan atau pengamatan ke dalam penalaran.",
    "A claim connects to specific notes. Its scope and uncertainty remain visible." to "Klaim terhubung dengan catatan tertentu. Cakupan dan ketidakpastian tetap terlihat.",
    "Tap each record to follow the reasoning." to "Sentuh setiap catatan untuk mengikuti penalaran.",
    "Pro" to "Pro",
    "Trace a claim back to the supplied observations." to "Telusuri klaim kembali ke pengamatan tersedia.",
    "Compare findings without losing their differences." to "Bandingkan temuan tanpa menghilangkan perbedaannya.",
    "Revise a claim when the supplied data changes." to "Revisi klaim saat data tersedia berubah.",
    "An earlier AI reply belongs to a previous workspace state. It was not added to this chat, and no draft change was applied." to "Jawaban AI sebelumnya berasal dari status ruang kerja lama. Tidak ditambahkan ke chat dan tidak mengubah draf.",
    "An earlier AI turn became unavailable after the workspace changed. No draft change was applied." to "Pesan AI sebelumnya tidak tersedia setelah ruang kerja berubah. Draf tidak berubah.",
    "An earlier AI turn may have been processed before the workspace changed. Its reply was not added; check the refreshed credit balance before retrying." to "Pesan AI sebelumnya mungkin diproses sebelum ruang kerja berubah. Jawaban tidak ditambahkan; periksa saldo terbaru sebelum mencoba lagi.",
    "Close AI chat" to "Tutup chat AI",
    "Finishing the conversation reset…" to "Menyelesaikan reset percakapan…",
    "Clearing this conversation's server session metadata…" to "Menghapus metadata sesi percakapan di server…",
    "This conversation was cleared on this device, but the server did not confirm clearing its session metadata. It may remain until the session expires. Your project and deterministic feedback are unchanged." to "Percakapan dihapus dari perangkat, tetapi penghapusan metadata sesi di server belum terkonfirmasi. Metadata mungkin tetap ada hingga sesi berakhir. Proyek dan umpan balik pemeriksaan tidak berubah.",
    "Retry server clear" to "Coba hapus dari server lagi",
    "The current response is still processing. Clear becomes available when it finishes." to "Jawaban masih diproses. Penghapusan tersedia setelah selesai.",
    "I can explain this verification feedback or ask a reflection question. Every answer stays linked to this case." to "Saya dapat menjelaskan umpan balik pemeriksaan atau memberi pertanyaan refleksi. Jawaban tetap terkait kasus ini.",
    "Suggested prompts" to "Saran pertanyaan",
    "Suggested next" to "Saran berikutnya",
    "Sign in with a verified account to request AI help. The case guide still works offline." to "Masuk dengan akun terverifikasi untuk meminta AI. Panduan kasus tetap berfungsi luring.",
    "Share the shown feedback, my claim, and selected evidence for this request." to "Bagikan umpan balik ditampilkan, klaim saya, dan bukti terpilih untuk permintaan ini.",
    "Five requests reached for this review. Revise and verify again to start a new context." to "Lima permintaan tercapai untuk tinjauan ini. Revisi dan periksa kembali untuk memulai konteks baru.",
    "Ask about this feedback" to "Tanyakan umpan balik ini",
    "Credits follow verified provider token usage. A valid AI response is charged; failed or rejected requests release the reservation. The deterministic check remains authoritative." to "Kredit mengikuti penggunaan token penyedia terverifikasi. Jawaban AI valid ditagihkan; permintaan gagal atau ditolak melepaskan reservasi. Pemeriksaan kasus tetap menjadi acuan.",
    "Evidrilo AI" to "AI Evidrilo",
    "A bounded assistant for this evidence review." to "Asisten terbatas untuk tinjauan bukti ini.",
    "Clear this conversation" to "Hapus percakapan ini",
    "Close Evidrilo AI assistant" to "Tutup asisten AI Evidrilo",
    "AI can explain feedback and offer a draft suggestion. It cannot change verification status or invent evidence; a suggestion stays unapplied until you choose it and verify again." to "AI dapat menjelaskan umpan balik dan menyarankan draf. AI tidak mengubah status pemeriksaan atau mengarang bukti; saran belum diterapkan sampai Anda memilihnya dan memeriksa kembali.",
    "Claim scope" to "Cakupan klaim",
    "Draft field" to "Isian draf",
    "Choose how far the claim should reach" to "Pilih sejauh mana klaim berlaku",
    "This observation only" to "Hanya pengamatan ini",
    "Limited comparison" to "Perbandingan terbatas",
    "Cause-and-effect claim" to "Klaim sebab akibat",
    "Unsupported" to "Tidak didukung",
    "Your edit stays in this proposal until you apply it. The original evidence links do not verify your changed wording; submit the draft for a fresh check." to "Edit tetap dalam usulan sampai diterapkan. Hubungan bukti awal tidak memverifikasi kalimat baru; kirim draf untuk pemeriksaan baru.",
    "Not applied. Review it, then submit your draft for a fresh deterministic check." to "Belum diterapkan. Tinjau lalu kirim draf untuk pemeriksaan baru.",
    "This field or value cannot be applied to the current case draft. No draft changes were made." to "Isian atau nilai ini tidak dapat diterapkan pada draf kasus saat ini. Draf tidak berubah.",
    "Cancel edit" to "Batalkan edit",
    "Edit suggestion" to "Edit saran",
    "Apply edited proposal" to "Terapkan usulan yang diedit",
    "Apply to draft" to "Terapkan ke draf",
    "No AI credits were charged" to "Kredit AI tidak ditagihkan",
    "credit" to "kredit",
    "credits" to "kredit",
    "Evidrilo AI is thinking…" to "AI Evidrilo sedang berpikir…",
    "Review consent to see available credits" to "Tinjau persetujuan untuk melihat kredit",
    "No active AI credit grants" to "Tidak ada pemberian kredit AI aktif",
    "Free · one-time" to "Free · sekali saja",
    "Pro · current period" to "Pro · periode saat ini",
    "AI grant" to "Pemberian kredit AI",
    "Example chat" to "Contoh chat",
    "Choose an example conversation" to "Pilih contoh percakapan",
    "Example chat change" to "Perubahan contoh chat",
    "A possible next step" to "Kemungkinan langkah berikutnya",
    "AI availability" to "Ketersediaan AI",
    "You stay in charge" to "Anda tetap menentukan",
    "AI is optional. It needs an eligible account and enabled services. Project assistance also needs a supported, published template.\n\nGeneral chat does not automatically send your project. You choose what to share. Suggestions are not scientific validation.\n\nThis introduction only shows example conversations." to "AI opsional, membutuhkan akun sesuai dan layanan aktif. Bantuan proyek juga membutuhkan template terbit yang didukung.\n\nChat umum tidak otomatis mengirim proyek. Anda memilih yang dibagikan. Saran bukan validasi ilmiah.\n\nPengantar ini hanya menunjukkan contoh percakapan.",
    "Transform the export document" to "Ubah dokumen ekspor",
    "Local revisions" to "Revisi lokal",
    "Choose a format preview" to "Pilih pratinjau format",
    "Format preview · no file is created" to "Pratinjau format · berkas tidak dibuat",
    "Replay the welcome celebration" to "Ulangi perayaan sambutan",
    "Your next project in Evidrilo. Tap to replay the paper celebration." to "Proyek berikutnya di Evidrilo. Sentuh untuk mengulang perayaan kertas.",
    "YOUR NEXT PROJECT" to "PROYEK BERIKUTNYA",
    "An idea worth\nexploring." to "Gagasan untuk\ndijelajahi.",
    "Start with your question" to "Mulai dengan pertanyaan Anda",
    "Tap for another little celebration" to "Sentuh untuk perayaan kecil lagi",
    "WORKSPACE TRACE" to "JEJAK RUANG KERJA",
    "No requirement was supplied for this workspace." to "Tidak ada persyaratan untuk ruang kerja ini.",
    "Evidence relationship" to "Hubungan bukti",
    "No observation selected yet" to "Belum ada pengamatan dipilih",
    "EVIDENCE LENS" to "LENSA BUKTI",
    "Selection is shown as a student anchor; it is not a claim of proof by itself." to "Pilihan ditampilkan sebagai rujukan pelajar; bukan bukti kebenaran dengan sendirinya.",
    "VERIFY CLAIM · CLAIM BOUNDARY" to "PERIKSA KLAIM · BATAS KLAIM",
    "Student claim" to "Klaim pelajar",
    "Deterministic checks found no boundary issue in the supplied information." to "Pemeriksaan tidak menemukan masalah batas pada informasi tersedia.",
    "Verification detail for claim verification" to "Rincian pemeriksaan klaim",
    "VERIFICATION DETAIL" to "RINCIAN PEMERIKSAAN",
    "No blocking verification issue found in the bounded checks." to "Tidak ada masalah penghambat dalam pemeriksaan terbatas.",
    "Each deterministic check passed for the supplied claim and anchors." to "Semua pemeriksaan terpenuhi untuk klaim dan rujukan tersedia.",
    "No evidence changed" to "Tidak ada bukti berubah",
    "Verification" to "Pemeriksaan",
    "Changed" to "Berubah",
    "Unchanged" to "Tetap",
    "Open gap" to "Celah terbuka",
    "Evidence retained" to "Bukti dipertahankan",
    "No retained anchors" to "Tidak ada rujukan dipertahankan",
    "Evidence added" to "Bukti ditambahkan",
    "No evidence added" to "Tidak ada bukti ditambahkan",
    "Evidence removed or unavailable" to "Bukti dihapus atau tidak tersedia",
    "No evidence removed" to "Tidak ada bukti dihapus",
    "Claim text changed" to "Teks klaim berubah",
    "Scope changed" to "Cakupan berubah",
    "Limitations added" to "Batasan ditambahkan",
    "No limitation added" to "Tidak ada batasan ditambahkan",
    "Limitations removed" to "Batasan dihapus",
    "No limitation removed" to "Tidak ada batasan dihapus",
    "Limitation note changed" to "Catatan batasan berubah",
    "Next action changed" to "Langkah berikutnya berubah",
    "Evidence relationship changed" to "Hubungan bukti berubah",
    "Hide comparison details" to "Sembunyikan rincian perbandingan",
    "Show comparison details" to "Tampilkan rincian perbandingan",
    "General causal claim" to "Klaim sebab akibat umum",
    "Selected anchor" to "Rujukan terpilih",
    "New and anchored" to "Baru dan berujukan",
    "Unchanged and anchored" to "Tetap dan berujukan",
    "Changed and anchored" to "Berubah dan berujukan",
    "Stale: limitation anchor missing" to "Kedaluwarsa: rujukan batasan hilang",
    "DATA" to "DATA",
    "PROPOSAL" to "USULAN",
    "AI help for this stage" to "Bantuan AI untuk tahap ini",
    "Suggestions only—not a grade or verification. You decide what, if anything, to apply." to "Hanya saran—bukan nilai atau verifikasi. Anda menentukan yang akan diterapkan.",
    "A previous Project AI result is still awaiting review or reconciliation. Return to its project and stage, or sign in to the account that requested it. New Project AI requests stay paused until it is resolved." to "Hasil AI proyek sebelumnya menunggu tinjauan atau penyelarasan. Kembali ke proyek dan tahapnya, atau masuk ke akun peminta. Permintaan baru dijeda hingga selesai.",
    "Choose the context to send" to "Pilih konteks yang dikirim",
    "Add a saved field or source/evidence note before asking for help in this stage." to "Tambahkan isian tersimpan atau catatan sumber/bukti sebelum meminta bantuan tahap ini.",
    "Check Project AI consent" to "Periksa persetujuan AI proyek",
    "Checking saved consent…" to "Memeriksa persetujuan tersimpan…",
    "Project AI consent is separate and revocable. Granting it does not send project content by itself." to "Persetujuan AI proyek terpisah dan dapat dicabut. Persetujuan tidak mengirim isi proyek otomatis.",
    "Allow Project AI processing" to "Izinkan pemrosesan AI proyek",
    "Account consent is on. Only the choices below are sent for this request." to "Persetujuan akun aktif. Hanya pilihan di bawah dikirim untuk permintaan ini.",
    "Revoke consent" to "Cabut persetujuan",
    "Sign in with a verified account to use Project AI. Manual project work stays available." to "Masuk dengan akun terverifikasi untuk memakai AI proyek. Pekerjaan manual tetap tersedia.",
    "For this request, send only the selected fields and evidence notes, plus project/method/revision metadata for ownership and stale checks. Nothing is applied until I review it." to "Untuk permintaan ini, kirim hanya isian dan catatan bukti terpilih, serta metadata proyek/metode/revisi untuk pemeriksaan kepemilikan dan kedaluwarsa. Tidak diterapkan sebelum ditinjau.",
    "Ask AI about this stage" to "Tanyakan tahap ini kepada AI",
    "Save the current edits first; AI only uses the saved revision." to "Simpan perubahan dahulu; AI hanya memakai revisi tersimpan.",
    "The result of this request is unknown. Do not start a new request; retry the same request key to reconcile it without creating a second charge." to "Hasil belum diketahui. Jangan mulai permintaan baru; coba ulang kunci permintaan yang sama untuk menyelaraskan tanpa biaya kedua.",
    "Retry same request" to "Coba permintaan yang sama",
    "Review AI suggestions" to "Tinjau saran AI",
    "Retry activity settlement" to "Coba penyelarasan aktivitas",
    "No evaluation was run. These suggestions do not change evidence, sources, or project status." to "Evaluasi tidak dijalankan. Saran tidak mengubah bukti, sumber, atau status proyek.",
    "This preview is from an older or unsaved project revision. It cannot be applied; dismiss it to reconcile the already charged request." to "Pratinjau berasal dari revisi lama atau belum disimpan. Tidak dapat diterapkan; tutup untuk menyelaraskan permintaan yang sudah ditagihkan.",
    "Review or edit" to "Tinjau atau edit",
    "This response contains guidance only; it has no field changes to apply." to "Jawaban hanya berisi panduan; tidak ada perubahan isian untuk diterapkan.",
    "Apply selected" to "Terapkan pilihan",
    "Evidence guide" to "Panduan bukti",
    "A short way to move from an observation to a claim you can explain." to "Cara singkat beralih dari pengamatan ke klaim yang dapat dijelaskan.",
    "Three evidence habits" to "Tiga kebiasaan bukti",
    "Does a selected fact prove the claim?" to "Apakah fakta terpilih membuktikan klaim?",
    "No. It gives the claim an explicit evidence anchor. The evaluator still checks scope and limitations." to "Tidak. Fakta memberi rujukan bukti eksplisit. Pemeriksa tetap menilai cakupan dan batasan.",
    "What if the evidence is incomplete?" to "Bagaimana jika bukti belum lengkap?",
    "Keep the claim bounded to what remains observable and say which limitation prevents a broader conclusion." to "Batasi klaim pada yang masih teramati dan nyatakan batasan yang mencegah kesimpulan lebih luas.",
    "Who writes the conclusion?" to "Siapa menulis kesimpulan?",
    "You do. Evidrilo gives reasons and anchors; it does not generate or grade the conclusion for you." to "Anda. Evidrilo memberi alasan dan rujukan; tidak membuat atau menilai kesimpulan untuk Anda.",
    "Open evidence workflow" to "Buka alur bukti",
    "See the introduction again" to "Lihat pengantar kembali",
    "The bundled example is separate from your projects. Your own project work stays on this device." to "Contoh bawaan terpisah dari proyek. Pekerjaan proyek sendiri tetap di perangkat.",
    "Revision" to "Revisi",
    "common questions" to "pertanyaan umum",
    "Common questions" to "Pertanyaan umum",
    "A few boundaries worth remembering" to "Beberapa batasan yang perlu diingat",
)
