package dev.nextgen.mobile

// App-owned presentation copy. Record IDs and learner content are never changed.
internal fun indonesianCopy11(): Map<String, String> = mapOf(
    "We will verify whether Apple is already linked before changing sign-in methods." to "Kami memeriksa apakah Apple sudah terhubung sebelum mengubah metode masuk.",
    "Cancel Apple linking" to "Batalkan penghubungan Apple",
    "Link Apple to this account" to "Hubungkan Apple ke akun ini",
    "Export account data" to "Ekspor data akun",
    "Delete account data" to "Hapus data akun",
    "Evidrilo app icon" to "Ikon aplikasi Evidrilo",
    "Build conclusions you can defend" to "Susun kesimpulan yang dapat dijelaskan",
    "Turn a question into a project you can explain. Organize sources, connect evidence to claims, keep limits visible, and export your work." to "Ubah pertanyaan menjadi proyek yang dapat dijelaskan. Tata sumber, hubungkan bukti dengan klaim, perlihatkan batasan, dan ekspor pekerjaan.",
    "What this app does" to "Yang dilakukan aplikasi",
    "Create a local project from five structure-only starters or a blank page. Record sources and evidence, develop findings and claims, review revisions, and export reports or a recovery archive. Three synthetic Practice cases help you rehearse these moves." to "Buat proyek lokal dari lima panduan struktur atau halaman kosong. Catat sumber dan bukti, kembangkan temuan serta klaim, tinjau revisi, lalu ekspor laporan atau cadangan pemulihan. Tiga latihan rekaan membantu melatih langkah ini.",
    "What this app does not do" to "Batas kemampuan aplikasi",
    "Structure progress is not a grade. Practice checks are bounded to supplied material. AI suggestions require available services, account access, and separate consent; you review suggestions before using them. Evidrilo does not verify your research or replace your instructor." to "Progres struktur bukan nilai. Pemeriksaan latihan terbatas pada materi tersedia. Saran AI membutuhkan layanan tersedia, akses akun, dan persetujuan terpisah; tinjau sebelum memakai. Evidrilo tidak memverifikasi penelitian atau menggantikan pengajar.",
    "Privacy boundary" to "Batas privasi",
    "Local projects, evidence work and Free practice do not need an account. Online AI needs internet, a verified account, consent, credits and an available service. Projects stay on this device; an AI request sends the context you separately confirm. Billing is not required for local work." to "Proyek lokal, pekerjaan bukti, dan latihan Free tidak membutuhkan akun. AI daring memerlukan internet, akun terverifikasi, persetujuan, kredit, dan layanan tersedia. Proyek tetap di perangkat; permintaan AI mengirim konteks yang Anda konfirmasikan terpisah. Pembayaran tidak diperlukan untuk pekerjaan lokal.",
    "Open-source and attribution" to "Kode terbuka dan atribusi",
    "The repository contains the reproducible application source, setup instructions, and retained third-party notices. Final publication assets and owner eligibility checks remain separate release gates." to "Repositori berisi sumber aplikasi yang dapat dibangun ulang, instruksi setup, dan pemberitahuan pihak ketiga. Aset publikasi akhir dan pemeriksaan kelayakan pemilik tetap menjadi syarat rilis terpisah.",
    "A quiet record of the latest evidence-change comparison on this device." to "Catatan perbandingan perubahan bukti terbaru di perangkat ini.",
    "This is not an account timeline. The free core keeps one completed comparison locally and never uploads it." to "Ini bukan linimasa akun. Fitur inti gratis menyimpan satu perbandingan selesai lokal tanpa mengunggahnya.",
    "Clear latest comparison" to "Hapus perbandingan terbaru",
    "No comparison saved yet." to "Belum ada perbandingan tersimpan.",
    "Complete the free evidence workflow and the evidence-change round to create one local comparison." to "Selesaikan alur bukti gratis dan tahap perubahan bukti untuk membuat perbandingan lokal.",
    "LATEST COMPARISON" to "PERBANDINGAN TERBARU",
    "Base round" to "Tahap awal",
    "Changed-evidence round" to "Tahap perubahan bukti",
    "Read-only local record" to "Catatan lokal hanya baca",
    "The saved comparison keeps learner-authored drafts and the active evidence boundary. It is not a score or learning claim." to "Perbandingan tersimpan mempertahankan draf tulisan pelajar dan batas bukti aktif. Ini bukan skor atau klaim hasil belajar.",
    "Local storage and optional services" to "Penyimpanan lokal dan layanan opsional",
    "Your Evidrilo" to "Evidrilo Anda",
    "How Evidrilo works" to "Cara kerja Evidrilo",
    "Evidence · claims · limits · revision" to "Bukti · klaim · batasan · revisi",
    "Try a guided case" to "Coba kasus terpandu",
    "A separate worked example" to "Contoh terpisah",
    "Track what changed" to "Telusuri perubahan",
    "Review your latest local comparison" to "Tinjau perbandingan lokal terbaru",
    "Optional project capacity and evidence cases" to "Kapasitas proyek dan kasus opsional",
    "Unavailable in this build" to "Tidak tersedia dalam versi ini",
    "Account & help" to "Akun dan bantuan",
    "Support and billing" to "Dukungan dan pembayaran",
    "Restore · manage · refund · privacy" to "Pulihkan · kelola · pengembalian dana · privasi",
    "Boundaries, privacy, and attribution" to "Batasan, privasi, dan atribusi",
    "Local-first by default" to "Lokal secara bawaan",
    "Free project work stays on this device. Pro requires sign-in and a confirmed RevenueCat entitlement. Server AI, cloud sync, and analytics transmission remain paused." to "Pekerjaan proyek Free tetap di perangkat. Pro membutuhkan masuk dan akses RevenueCat terkonfirmasi. AI server, sinkronisasi awan, serta pengiriman analitik tetap dijeda.",
    "Theme" to "Tema",
    "Workflow" to "Alur kerja",
    "Reading and motion" to "Bacaan dan animasi",
    "Follows your device accessibility settings" to "Mengikuti aksesibilitas perangkat",
    "Evidrilo keeps system text-size and reduced-motion behavior in the platform layer. No in-app toggle is advertised until a separate setting is implemented and tested on each target." to "Evidrilo mengikuti ukuran teks dan pengurangan gerakan perangkat. Pengaturan aplikasi terpisah belum ditawarkan sebelum tersedia dan diperiksa pada setiap platform.",
    "Audio assistance" to "Bantuan audio",
    "Narration and interaction sounds on" to "Narasi dan suara interaksi aktif",
    "Narration on · interaction sounds off" to "Narasi aktif · suara interaksi nonaktif",
    "Narration off · interaction sounds on" to "Narasi nonaktif · suara interaksi aktif",
    "Off · visible text remains available" to "Nonaktif · teks tetap tersedia",
    "Audio is optional. The visible text remains complete. Bundled narration is preferred when reviewed assets are available; otherwise Evidrilo uses an offline-capable platform voice and never falls back to the network." to "Audio opsional; teks tetap lengkap. Narasi bawaan diutamakan jika aset ditinjau tersedia; lainnya memakai suara platform yang berfungsi luring tanpa beralih ke internet.",
    "Turn narration off" to "Nonaktifkan narasi",
    "Turn narration on" to "Aktifkan narasi",
    "Turn interaction sounds off" to "Nonaktifkan suara interaksi",
    "Turn interaction sounds on" to "Aktifkan suara interaksi",
    "Audio preference could not be saved on this device; it will remain active for this session." to "Preferensi audio gagal disimpan di perangkat; tetap aktif untuk sesi ini.",
    "Local reminders" to "Pengingat lokal",
    "Updating reminder permission…" to "Memperbarui izin pengingat…",
    "On · no eligible case yet" to "Aktif · belum ada kasus memenuhi syarat",
    "Local reminders are optional, off by default, and never promotional. Evidrilo schedules them on this device without sending draft text to a server." to "Pengingat lokal opsional, nonaktif secara bawaan, dan tidak untuk promosi. Jadwal dibuat di perangkat tanpa mengirim teks draf ke server.",
    "Updating reminders…" to "Memperbarui pengingat…",
    "Turn reminders off" to "Nonaktifkan pengingat",
    "Enable local reminders" to "Aktifkan pengingat lokal",
    "Unfinished case reminders on" to "Pengingat kasus belum selesai aktif",
    "Unfinished case reminders off" to "Pengingat kasus belum selesai nonaktif",
    "Completed review reminders on" to "Pengingat tinjauan selesai aktif",
    "Completed review reminders off" to "Pengingat tinjauan selesai nonaktif",
    "Earlier" to "Lebih awal",
    "Later" to "Lebih akhir",
    "No reminder is currently scheduled. Start or complete a case, then return here to review the eligible reminder." to "Belum ada pengingat terjadwal. Mulai atau selesaikan kasus, lalu kembali untuk meninjau pengingat yang sesuai.",
    "System notification permission is granted." to "Izin notifikasi perangkat aktif.",
    "System notification permission is off. Enable it in system settings to receive reminders." to "Izin notifikasi perangkat nonaktif. Aktifkan di pengaturan perangkat untuk menerima pengingat.",
    "Open notification settings" to "Buka pengaturan notifikasi",
    "Permission is requested only after you choose Enable local reminders." to "Izin diminta hanya setelah memilih Aktifkan pengingat lokal.",
    "Data controls" to "Kontrol data",
    "Privacy and local data" to "Privasi dan data lokal",
    "Stored on this device only" to "Hanya tersimpan di perangkat",
    "Drafts and the latest evidence-change comparison stay inside the platform storage adapter. The evaluator does not send learner text to a server." to "Draf dan perbandingan perubahan bukti terbaru tetap pada penyimpanan platform. Pemeriksa tidak mengirim tulisan pelajar ke server.",
    "Reset current workflow" to "Reset alur saat ini",
    "Optional product analytics" to "Analitik produk opsional",
    "On · minimal events only" to "Aktif · hanya peristiwa minimal",
    "Analytics is optional and off by default. If enabled, a signed-in account may send completion and recommendation events without draft text, passwords, or payment data. Turning it off stops future sends." to "Analitik opsional dan nonaktif secara bawaan. Jika aktif, akun yang masuk dapat mengirim peristiwa penyelesaian dan rekomendasi tanpa teks draf, kata sandi, atau data pembayaran. Menonaktifkan menghentikan pengiriman berikutnya.",
    "Enable optional analytics" to "Aktifkan analitik opsional",
    "Turn analytics off" to "Nonaktifkan analitik",
    "Cloud sync is optional and off by default. When enabled for a verified account, only redacted progress metadata is sent; learner-authored draft text remains on this device." to "Sinkronisasi awan opsional dan nonaktif secara bawaan. Akun terverifikasi hanya mengirim metadata progres disunting; tulisan draf tetap di perangkat.",
    "Turn cloud sync off" to "Nonaktifkan sinkronisasi awan",
    "Sign in first to enable this option." to "Masuk dahulu untuk mengaktifkan pilihan ini.",
    "Enable cloud progress sync" to "Aktifkan sinkronisasi progres awan",
    "Checking cloud sync…" to "Memeriksa sinkronisasi awan…",
    "Sync now" to "Sinkronkan sekarang",
    "What stays local" to "Yang tetap lokal",
    "Project drafts and case work stay on this device. Pro requires sign-in and a confirmed RevenueCat entitlement; server AI, cloud sync, and analytics transmission remain paused." to "Draf proyek dan kasus tetap di perangkat. Pro membutuhkan masuk dan akses RevenueCat terkonfirmasi; AI server, sinkronisasi awan, serta pengiriman analitik tetap dijeda.",
    "Reset current workflow?" to "Reset alur saat ini?",
    "This removes the saved in-progress draft. Your completed comparison stays in local history." to "Draf yang sedang dikerjakan dihapus. Perbandingan selesai tetap pada riwayat lokal.",
    "Reset workflow" to "Reset alur",
    "Clear latest comparison?" to "Hapus perbandingan terbaru?",
    "This removes the one completed comparison stored on this device. It cannot be recovered by the free core." to "Satu perbandingan selesai di perangkat dihapus. Fitur inti gratis tidak dapat memulihkannya.",
    "How can we help?" to "Apa yang bisa kami bantu?",
    "Help with your account, data, and purchases." to "Bantuan akun, data, dan pembelian.",
    "Restore a purchase" to "Pulihkan pembelian",
    "Open Premium and choose Restore purchase. The store account holds the completed transaction." to "Buka Pro dan pilih Pulihkan pembelian. Akun toko menyimpan transaksi selesai.",
    "Manage a subscription" to "Kelola langganan",
    "Use Customer Center. The store controls billing and cancellation." to "Gunakan Pusat Pelanggan. Toko mengendalikan pembayaran dan pembatalan.",
    "Use Apple Account subscriptions on iOS or Google Play subscriptions on Android." to "Gunakan langganan Akun Apple di iOS atau Google Play di Android.",
    "Request a refund" to "Minta pengembalian dana",
    "Contact the store that processed your purchase. Include the order or transaction reference. Never send passwords or payment credentials to support." to "Hubungi toko pemroses pembelian dan sertakan rujukan transaksi. Jangan kirim kata sandi atau kredensial pembayaran ke dukungan.",
    "Privacy and deletion" to "Privasi dan penghapusan",
    "Local projects stay on this device. Request server-account deletion from Account; local workflow and history are cleared separately." to "Proyek lokal tetap di perangkat. Minta penghapusan akun server dari Akun; alur lokal dan riwayat dihapus terpisah.",
    "Contact" to "Kontak",
    "For help, email the Evidrilo team. Do not include passwords or payment credentials." to "Kirim email ke tim Evidrilo untuk bantuan. Jangan sertakan kata sandi atau kredensial pembayaran.",
    "No email app opened. Select and copy the address above." to "Aplikasi email tidak terbuka. Pilih dan salin alamat di atas.",
    "Email support" to "Email dukungan",
    "Open Premium plans" to "Buka paket Pro",
    "Open Account and privacy controls" to "Buka Akun dan kontrol privasi",
    "Published content is unavailable offline." to "Konten terbit tidak tersedia luring.",
    "The published content service is unavailable." to "Layanan konten terbit tidak tersedia.",
    "The published case was not found." to "Kasus terbit tidak ditemukan.",
    "Published content is temporarily unavailable." to "Konten terbit sementara tidak tersedia.",
    "Published content could not be loaded." to "Konten terbit gagal dimuat.",
    "Published content response is too large." to "Jawaban konten terbit terlalu besar.",
    "The published content response is invalid." to "Jawaban konten terbit tidak valid.",
    "Choose supporting evidence" to "Pilih bukti pendukung",
    "Use observations, not assumptions." to "Gunakan pengamatan, bukan asumsi.",
    "Select the supplied observation facts that directly support the relationship you want to describe. A selected fact is an anchor for your writing, not proof that the conclusion is correct." to "Pilih fakta pengamatan tersedia yang langsung mendukung hubungan pilihan Anda. Fakta terpilih adalah rujukan tulisan, bukan bukti bahwa kesimpulan benar.",
    "Keep the claim in bounds" to "Batasi klaim",
    "Say only what the case can support." to "Nyatakan hanya yang didukung kasus.",
    "Choose a scope that matches the supplied observations and name the limitations that still matter. The case can support a bounded comparison without establishing a general causal effect." to "Pilih cakupan sesuai pengamatan dan sebutkan batasan penting. Kasus mendukung perbandingan terbatas tanpa membuktikan sebab akibat umum.",
    "Read feedback, then revise" to "Baca umpan balik, lalu revisi",
    "Inspect the reason. Revise once." to "Periksa alasannya. Revisi sekali.",
    "Feedback points to a specific field and its fact anchors. Use that reason to make one student-authored revision; the original draft remains available for comparison." to "Umpan balik merujuk isian dan fakta tertentu. Gunakan alasan untuk satu revisi tulisan sendiri; draf awal tetap tersedia untuk dibandingkan.",
    "Meet your student workspace." to "Kenali ruang kerja pelajar Anda.",
    "Discover projects, evidence links, optional AI, and exports in about 1–2 minutes. This introduction uses synthetic examples and does not create a project." to "Jelajahi proyek, hubungan bukti, AI opsional, dan ekspor sekitar 2–3 menit. Pengantar memakai contoh rekaan tanpa membuat proyek.",
    "Skip Get Started" to "Lewati pengantar",
    "Choose a project structure, connect your notes, and keep the limits of a claim in view." to "Pilih struktur proyek, hubungkan catatan, dan perlihatkan batas klaim.",
    "Explore optional AI help and local history. AI needs an eligible account and enabled services." to "Jelajahi bantuan AI opsional dan riwayat lokal. AI membutuhkan akun sesuai dan layanan aktif.",
    "Create and edit local projects without an account. Sign-in is only for account-bound services; cloud sync needs separate consent." to "Buat dan edit proyek lokal tanpa akun. Masuk diperlukan hanya untuk layanan terkait akun; sinkronisasi awan membutuhkan persetujuan terpisah.",
    "This evidence reference is unavailable in the active case version." to "Rujukan bukti tidak tersedia dalam kasus aktif.",
    "No next action has been selected yet." to "Belum memilih langkah berikutnya.",
    "This action was selected by the learner and is bounded by the current case." to "Langkah dipilih pelajar dan dibatasi kasus saat ini.",
    "Start workspace" to "Mulai ruang kerja",
    "Review feedback" to "Tinjau umpan balik",
    "Continue revision" to "Lanjutkan revisi",
    "Review your comparison" to "Tinjau perbandingan Anda",
    "Continue challenge" to "Lanjutkan tantangan",
    "Review challenge feedback" to "Tinjau umpan balik tantangan",
    "View comparison" to "Lihat perbandingan",
    "Observation unavailable" to "Pengamatan tidak tersedia",
    "A suggested review is temporarily unavailable." to "Saran tinjauan sementara tidak tersedia.",
    "Cloud progress sync is optional, requires a verified account and explicit consent, and keeps learner draft text on this device." to "Sinkronisasi progres awan opsional, membutuhkan akun terverifikasi serta persetujuan eksplisit, dan mempertahankan tulisan draf di perangkat.",
    "Confirm that your revision uses the changed evidence." to "Pastikan revisi memakai bukti yang berubah.",
    "Connect A, B, and the new Study D to compare the recall findings." to "Hubungkan A, B, dan Studi D baru untuk membandingkan temuan ingatan.",
    "Connect both corrected counts to keep the comparison visible." to "Hubungkan kedua jumlah terkoreksi agar perbandingan terlihat.",
    "Connect at least one active record." to "Hubungkan minimal satu catatan aktif.",
    "Use only the supplied records and choices." to "Gunakan hanya catatan dan pilihan tersedia.",
    "Connect at least one supplied record." to "Hubungkan minimal satu catatan tersedia.",
    "Place all three cards on the comparison board." to "Letakkan ketiga kartu pada papan perbandingan.",
    "Choose a supplied limitation." to "Pilih batasan tersedia.",
    "Place each of the three cards on your comparison board." to "Letakkan masing-masing dari tiga kartu pada papan perbandingan.",
    "Write your own claim in 20–320 characters." to "Tulis klaim sendiri dalam 20–320 karakter.",
    "A · Recall after a week" to "A · Ingatan setelah seminggu",
    "24 first-year volunteers at one fictional campus." to "24 sukarelawan tahun pertama di satu kampus rekaan.",
    "12 practiced a quiz and 12 reread the same material for 30 minutes; groups were randomly assigned." to "12 berlatih kuis dan 12 membaca ulang materi yang sama selama 30 menit; kelompok ditentukan acak.",
    "At seven days, mean recall was 7/10 after quiz practice and 5/10 after rereading." to "Setelah tujuh hari, rata-rata ingatan 7/10 setelah latihan kuis dan 5/10 setelah membaca ulang.",
    "Small volunteer sample; one material and one delayed recall measure." to "Sampel sukarelawan kecil; satu materi dan satu pengukuran ingatan tertunda.",
    "B · Recall on the same day" to "B · Ingatan pada hari yang sama",
    "18 volunteers from a different fictional course." to "18 sukarelawan dari mata kuliah rekaan lain.",
    "The same learners used both methods in a fixed order, then took an immediate quiz." to "Pelajar yang sama memakai kedua metode dalam urutan tetap, lalu mengikuti kuis langsung.",
    "Mean immediate recall was 8/10 after quiz practice and 6/10 after rereading." to "Rata-rata ingatan langsung 8/10 setelah latihan kuis dan 6/10 setelah membaca ulang.",
    "Fixed order can influence results; the follow-up differs from Study A." to "Urutan tetap dapat memengaruhi hasil; pengamatan lanjutan berbeda dari Studi A.",
    "C · A preference survey" to "C · Survei preferensi",
    "46 self-selected students at a third fictional campus." to "46 pelajar sukarela dari kampus rekaan ketiga.",
    "An anonymous survey asked which study method they preferred; recall was not measured." to "Survei anonim menanyakan metode belajar pilihan; ingatan tidak diukur.",
    "31/46 respondents said they preferred rereading." to "31/46 responden menyatakan lebih memilih membaca ulang.",
    "Preference is a different outcome from recall; self-selection limits reach." to "Preferensi berbeda dari ingatan; sampel sukarela membatasi cakupan.",
    "D · A new delayed comparison" to "D · Perbandingan tertunda baru",
    "12 volunteers in another fictional course." to "12 sukarelawan dari mata kuliah rekaan lainnya.",
    "Six used quiz practice and six reread; recall was checked after 14 days." to "Enam memakai latihan kuis dan enam membaca ulang; ingatan diperiksa setelah 14 hari.",
    "Both groups averaged 5/10 at 14 days: no observed difference on this measure." to "Kedua kelompok rata-rata 5/10 setelah 14 hari: tidak ada perbedaan teramati pada pengukuran ini.",
)
