package dev.nextgen.mobile

import androidx.compose.runtime.Composable
import androidx.compose.runtime.staticCompositionLocalOf

public enum class EvidriloLanguage(public val tag: String, public val nativeName: String) {
    ENGLISH("en", "English"), INDONESIAN("id", "Bahasa Indonesia");
}

public val LocalEvidriloLanguage = staticCompositionLocalOf { EvidriloLanguage.ENGLISH }

/** UI copy only. Student records, citations and provider replies keep their language. */
@Composable
public fun uiText(english: String, indonesian: String? = null): String =
    if (LocalEvidriloLanguage.current == EvidriloLanguage.INDONESIAN)
        indonesian ?: translateIndonesianUi(english)
    else english

internal val IndonesianUiCopy: Map<String, String> = mapOf(
    "Home" to "Beranda",
    "Projects" to "Proyek",
    "Practice" to "Latihan",
    "Cases" to "Kasus",
    "Profile" to "Profil",
    "Settings" to "Pengaturan",
    "Language" to "Bahasa",
    "Selected" to "Dipilih",
    "Preferences" to "Preferensi",
    "Workspace preferences" to "Preferensi tampilan",
    "Theme, reading, and audio" to "Tema, bacaan, dan audio",
    "Notifications" to "Notifikasi",
    "Privacy & data" to "Privasi dan data",
    "Account" to "Akun",
    "Sign in" to "Masuk",
    "Account connected" to "Akun terhubung",
    "Local workspace" to "Ruang kerja lokal",
    "Your account" to "Akun Anda",
    "Local student" to "Pelajar lokal",
    "Your recorded work" to "Aktivitas tercatat",
    "Active projects" to "Proyek aktif",
    "Notes" to "Catatan",
    "Cases finished" to "Latihan selesai",
    "Keep going" to "Lanjutkan",
    "All projects" to "Semua proyek",
    "Start a project" to "Mulai proyek",
    "Your question, your material" to "Pertanyaan dan materi Anda",
    "Local history" to "Riwayat lokal",
    "How progress is counted" to "Cara menghitung progres",
    "Your projects" to "Proyek Anda",
    "Create a project" to "Buat proyek",
    "Continue project" to "Lanjutkan proyek",
    "Open project" to "Buka proyek",
    "Mark complete" to "Tandai selesai",
    "Reopen project" to "Buka kembali proyek",
    "Recover project" to "Pulihkan proyek",
    "Recovery needed" to "Perlu dipulihkan",
    "Active" to "Aktif",
    "Completed" to "Selesai",
    "Delete permanently?" to "Hapus proyek secara permanen?",
    "Delete permanently" to "Hapus permanen",
    "Delete project" to "Hapus proyek",
    "Cancel" to "Batal",
    "Close" to "Tutup",
    "Keep data" to "Simpan data",
    "Export project" to "Ekspor proyek",
    "Import project" to "Impor proyek",
    "Independent project" to "Proyek mandiri",
    "Project backup (.evproj)" to "Cadangan proyek (.evproj)",
    "Markdown report" to "Laporan Markdown",
    "PDF report" to "Laporan PDF",
    "Word document" to "Dokumen Word",
    "Source matrix (CSV)" to "Matriks sumber (CSV)",
    "Synthesis themes (CSV)" to "Tema sintesis (CSV)",
    "Evidence notes (CSV)" to "Catatan bukti (CSV)",
    "Findings (CSV)" to "Temuan (CSV)",
    "Evidence relationships (CSV)" to "Hubungan bukti (CSV)",
    "Review your material" to "Tinjau materi Anda",
    "Project name" to "Nama proyek",
    "A short name to find this draft later." to "Nama singkat agar proyek ini mudah ditemukan.",
    "Blank project" to "Proyek mandiri",
    "Local starter" to "Panduan lokal",
    "About this project" to "Tentang proyek",
    "Project basics" to "Dasar proyek",
    "Frame your question" to "Rumuskan pertanyaan",
    "Set your boundaries" to "Tentukan batas",
    "Plan your material" to "Rencanakan materi",
    "Sources and files" to "Sumber dan berkas",
    "Evidence notes" to "Catatan bukti",
    "Findings and comparison" to "Temuan dan perbandingan",
    "Claims and evidence links" to "Klaim dan hubungan bukti",
    "Limitations and next steps" to "Batasan dan langkah berikutnya",
    "Review" to "Tinjauan",
    "Continue" to "Lanjutkan",
    "Sections" to "Bagian",
    "Saved on this device." to "Tersimpan di perangkat ini.",
    "Saving on this device…" to "Menyimpan di perangkat ini…",
    "Deadline" to "Tenggat",
    "Optional · no reminder is scheduled." to "Opsional · belum ada pengingat terjadwal.",
    "Not set" to "Belum ditentukan",
    "Add date" to "Tambah tanggal",
    "Sources" to "Sumber",
    "Source" to "Sumber",
    "Claims" to "Klaim",
    "Claim" to "Klaim",
    "Findings" to "Temuan",
    "Finding" to "Temuan",
    "Links" to "Tautan",
    "Add a source" to "Tambah sumber",
    "Add evidence note" to "Tambah catatan bukti",
    "Add a finding" to "Tambah temuan",
    "Add a claim" to "Tambah klaim",
    "Add a limitation or next action" to "Tambah batasan atau langkah berikutnya",
    "Source title" to "Judul sumber",
    "Author or organization" to "Penulis atau organisasi",
    "Year" to "Tahun",
    "Source type" to "Jenis sumber",
    "Access date" to "Tanggal akses",
    "Citation text" to "Teks sitasi",
    "Your selection" to "Pilihan Anda",
    "Checked by you" to "Sudah Anda periksa",
    "Yes" to "Ya",
    "No" to "Tidak",
    "Your notes" to "Catatan Anda",
    "Excerpt or paraphrase" to "Kutipan atau parafrasa",
    "Location" to "Lokasi",
    "Statement" to "Pernyataan",
    "Scope" to "Cakupan",
    "Limitations" to "Batasan",
    "Next action" to "Langkah berikutnya",
    "Supports" to "Mendukung",
    "Contradicts" to "Bertentangan",
    "Context" to "Konteks",
    "Start with your idea" to "Mulai dari gagasan Anda",
    "Choose a structure that fits your assignment, or start blank." to "Pilih struktur sesuai tugas Anda, atau mulai tanpa template.",
    "Start without a template" to "Mulai tanpa template",
    "My projects" to "Proyek saya",
    "Experiment" to "Eksperimen",
    "Survey" to "Survei",
    "Literature review" to "Kajian literatur",
    "Literature" to "Literatur",
    "Interview" to "Wawancara",
    "Engineering" to "Rekayasa",
    "Interviews & fieldwork" to "Wawancara dan studi lapangan",
    "Design & engineering" to "Desain dan rekayasa",
    "You change a condition and measure what happens." to "Ubah suatu kondisi dan ukur hasilnya.",
    "You observe patterns without changing conditions." to "Amati pola tanpa mengubah kondisi.",
    "You compare and connect existing sources." to "Bandingkan dan hubungkan sumber yang ada.",
    "You interpret what people say or what happens in a setting." to "Tafsirkan pengalaman dan peristiwa dalam suatu konteks.",
    "You design, test, and improve an artifact or solution." to "Rancang, uji, dan perbaiki suatu solusi.",
    "Change and measure" to "Ubah dan ukur",
    "Observe patterns" to "Amati pola",
    "Compare sources" to "Bandingkan sumber",
    "Hear perspectives" to "Pahami pengalaman",
    "Build and test" to "Rancang dan uji",
    "About this structure" to "Tentang struktur ini",
    "Use this structure" to "Gunakan struktur ini",
    "Start this project" to "Mulai proyek ini",
    "Remote catalog unavailable" to "Katalog online belum tersedia",
    "Retry" to "Coba lagi",
    "Try again" to "Coba lagi",
    "Got it" to "Mengerti",
    "Understood" to "Mengerti",
    "Support" to "Bantuan",
    "About Evidrilo" to "Tentang Evidrilo",
    "Choose what you want to manage." to "Pilih pengaturan yang ingin Anda kelola.",
    "Manage reminders on this device." to "Kelola pengingat pada perangkat ini.",
    "Adjust how your workspace looks and sounds." to "Sesuaikan tampilan dan audio ruang kerja.",
    "Review what stays local and control optional data use." to "Tinjau data lokal dan kendalikan penggunaan data opsional.",
    "Appearance" to "Tampilan",
    "Reading & display" to "Bacaan dan tampilan",
    "Text size" to "Ukuran teks",
    "Match device" to "Ikuti perangkat",
    "Light" to "Terang",
    "Dark" to "Gelap",
    "Audio" to "Audio",
    "Narration" to "Narasi",
    "Sound effects" to "Efek suara",
    "Local data" to "Data lokal",
    "Analytics" to "Analitik",
    "Cloud sync" to "Sinkronisasi cloud",
    "Account export" to "Ekspor akun",
    "Requires sign-in" to "Perlu masuk",
    "Off by default" to "Nonaktif secara bawaan",
    "On · local reminders" to "Aktif · pengingat lokal",
    "Evidrilo guide" to "Panduan Evidrilo",
    "Explore Evidrilo" to "Jelajahi Evidrilo",
    "Enable reminders" to "Aktifkan pengingat",
    "Disable reminders" to "Nonaktifkan pengingat",
    "Open system settings" to "Buka pengaturan perangkat",
    "Privacy policy" to "Kebijakan privasi",
    "Contact support" to "Hubungi bantuan",
    "Your research, connected." to "Penelitian Anda, saling terhubung.",
    "Explore" to "Jelajahi",
    "Case library" to "Katalog kasus",
    "See how evidence changes a claim." to "Lihat bagaimana bukti mengubah klaim.",
    "Cases worth questioning." to "Kasus yang layak ditelaah.",
    "Explore a worked investigation at your own pace." to "Jelajahi contoh penyelidikan sesuai ritme Anda.",
    "Free · synthetic case" to "Gratis · kasus sintetis",
    "Read the observations. Trace a claim. Reconsider it when evidence changes." to "Baca pengamatan. Telusuri klaim. Tinjau kembali saat bukti berubah.",
    "Open worked case" to "Buka contoh kasus",
    "Go deeper" to "Telusuri lebih jauh",
    "Explore with verified Pro access" to "Jelajahi dengan akses Pro terverifikasi",
    "Checking your Pro access…" to "Memeriksa akses Pro Anda…",
    "Review your Pro case collection" to "Jelajahi koleksi kasus Pro Anda",
    "Every strong claim starts with evidence." to "Klaim yang kuat dimulai dari bukti.",
    "Your evidence trail" to "Perjalanan bukti Anda",
    "Trace observations" to "Telusuri pengamatan",
    "Reconsider data" to "Tinjau ulang data",
    "Saved attempt" to "Latihan tersimpan",
    "Unlock with Pro" to "Buka dengan Pro",
    "Resume case" to "Lanjutkan latihan",
    "Start case" to "Mulai latihan",
    "Not started" to "Belum dimulai",
    "In progress" to "Sedang dikerjakan",
    "Finished" to "Selesai",
    "Start" to "Mulai",
    "Restart" to "Ulangi",
    "New attempt" to "Latihan baru",
    "Check" to "Periksa",
    "Check answer" to "Periksa jawaban",
    "Next" to "Berikutnya",
    "AI chat" to "Chat AI",
    "General Chat" to "Chat umum",
    "Activity" to "Aktivitas",
    "Clear" to "Bersihkan",
    "Send" to "Kirim",
    "Message" to "Pesan",
    "AI credits" to "Kredit AI",
    "Refresh balance" to "Perbarui saldo",
    "What this chat sends" to "Yang dikirim oleh chat",
    "Allow AI data processing" to "Izinkan pemrosesan data AI",
    "Revoke saved AI consent" to "Cabut persetujuan AI",
    "Check saved AI data-use consent" to "Periksa persetujuan penggunaan data AI",
    "Account-level AI consent is active. You approve each message separately." to "Persetujuan AI untuk akun aktif. Anda menyetujui setiap pesan secara terpisah.",
    "Up to 4,000 characters · composer text only; no original files" to "Maksimal 4.000 karakter · hanya teks pesan; tanpa berkas asli",
    "Project map" to "Peta proyek",
    "List" to "Daftar",
    "Canvas" to "Kanvas",
    "Reading this map" to "Cara membaca peta",
    "Student-recorded relationships" to "Hubungan yang Anda catat",
    "Close record" to "Tutup catatan",
    "No explicit links recorded." to "Belum ada tautan eksplisit.",
    "Your map starts with your material." to "Peta dimulai dari materi Anda.",
    "Record a source, then add notes and explicit links. Nothing is filled in for you." to "Catat sumber, lalu tambahkan catatan dan hubungan eksplisit. Tidak ada isian otomatis.",
    "Continue with Google" to "Lanjutkan dengan Google",
    "Email" to "Email",
    "Password" to "Kata sandi",
    "Create account" to "Buat akun",
    "Sign out" to "Keluar",
    "Reset password" to "Atur ulang kata sandi",
    "Forgot password?" to "Lupa kata sandi?",
    "Continue with email" to "Lanjutkan dengan email",
    "Keep learning locally" to "Lanjutkan secara lokal",
    "Connect your account" to "Hubungkan akun Anda",
    "Your work stays local." to "Pekerjaan Anda tetap lokal.",
    "Monthly" to "Bulanan",
    "Annually" to "Tahunan",
    "Free" to "Gratis",
    "Continue with Free" to "Lanjutkan secara gratis",
    "Continue Monthly" to "Lanjutkan bulanan",
    "Continue Annually" to "Lanjutkan tahunan",
    "Explore Pro" to "Jelajahi Pro",
    "More room for your ideas." to "Ruang lebih luas untuk gagasan Anda.",
    "Explore Evidrilo Pro plans and available access" to "Jelajahi paket dan akses Evidrilo Pro",
    "Compare Free and Pro" to "Bandingkan Free dan Pro",
    "Compare plans" to "Bandingkan paket",
    "Restore purchases" to "Pulihkan pembelian",
    "Manage subscription" to "Kelola langganan",
    "See what Pro includes" to "Lihat manfaat Pro",
    "One-time Free credit grant" to "Kredit Free satu kali",
    "Monthly earned Pro credits" to "Kredit Pro setiap bulan",
    "5 active projects" to "5 proyek total",
    "50 active projects" to "50 proyek total",
    "5 projects" to "5 proyek",
    "50 projects" to "50 proyek",
    "Local projects" to "Proyek lokal",
    "AI assistance" to "Bantuan AI",
    "Start a blank project" to "Mulai tanpa template",
    "Record a source" to "Catat sumber",
    "Open next task" to "Buka tugas berikutnya",
    "Your own project material" to "Materi proyek Anda sendiri",
    "About this project step" to "Tentang langkah proyek ini",
    "Keep your sources connected to the question." to "Hubungkan sumber dengan pertanyaan Anda.",
    "Guide" to "Panduan",
    "Progress" to "Progres",
    "History" to "Riwayat",
    "Save" to "Simpan",
    "Save changes" to "Simpan perubahan",
    "Apply" to "Terapkan",
    "Dismiss" to "Tutup",
    "Fullscreen" to "Layar penuh",
    "Close review" to "Tutup tinjauan",
    "Confirm export" to "Konfirmasi ekspor",
    "Save file" to "Simpan berkas",
    "Choose format" to "Pilih format",
    "Review before sharing" to "Tinjau sebelum membagikan",
    "Keep your ideas moving." to "Terus kembangkan idemu.",
    "Create a project" to "Buat proyek",
    "New project" to "Proyek baru",
    "Start with your own question" to "Mulai dari pertanyaanmu",
    "Inactive" to "Tidak aktif",
    "The project was removed. Attachment cleanup is pending; Evidrilo will retry it when the project list opens." to "Proyek sudah dihapus. Pembersihan lampiran masih tertunda dan akan dicoba lagi saat daftar proyek dibuka.",
)
