package dev.nextgen.mobile

// App-owned presentation copy. Record IDs and learner content are never changed.
internal fun indonesianCopy4(): Map<String, String> = mapOf(
    "Case" to "Kasus",
    "Relation" to "Hubungan",
    "Evidence facts" to "Fakta bukti",
    "Claim text" to "Teks klaim",
    "Limitation facts" to "Fakta batasan",
    "Limitation note" to "Catatan batasan",
    "Next-action reason" to "Alasan langkah berikutnya",
    "Aim" to "Tujuan",
    "Boundary" to "Batasan",
    "Offline-ready bundled case" to "Kasus bawaan siap luring",
    "AI credits require an available verified account and API session." to "Kredit AI memerlukan akun terverifikasi dan sesi API tersedia.",
    "The current AI credit balance could not be confirmed. Try refreshing before another request." to "Saldo kredit AI belum dapat dipastikan. Muat ulang sebelum meminta lagi.",
    "AI credits could not be loaded; deterministic feedback remains available." to "Kredit AI gagal dimuat; umpan balik pemeriksaan tetap tersedia.",
    "The latest AI credit balance could not be confirmed. It may be out of date." to "Saldo AI terbaru belum terkonfirmasi dan mungkin kedaluwarsa.",
    "AI credits are temporarily unavailable. Your manual project workflow remains available." to "Kredit AI sementara tidak tersedia. Alur proyek manual tetap tersedia.",
    "AI credits are temporarily unavailable; deterministic feedback remains available." to "Kredit AI sementara tidak tersedia; umpan balik pemeriksaan tetap tersedia.",
    "The API returned an unexpected response for AI credits." to "API memberi jawaban kredit AI yang tidak sesuai.",
    "Cloud sync is not configured in this build; local progress remains safe." to "Sinkronisasi awan belum dikonfigurasi; progres lokal tetap aman.",
    "Sign in again before syncing progress." to "Masuk kembali sebelum menyinkronkan progres.",
    "Your session expired; sign in again before syncing progress." to "Sesi berakhir; masuk kembali sebelum menyinkronkan progres.",
    "Secure session storage is unavailable; no progress was sent." to "Penyimpanan sesi aman tidak tersedia; progres belum dikirim.",
    "Progress sync completed." to "Sinkronisasi progres selesai.",
    "Progress cursor checked. Remote draft text is never downloaded; drafts stay local." to "Penanda progres diperiksa. Teks draf jarak jauh tidak diunduh; draf tetap lokal.",
    "Progress sync checked. Draft text remains on this device." to "Sinkronisasi progres diperiksa. Teks draf tetap di perangkat ini.",
    "Sign in before syncing progress." to "Masuk sebelum menyinkronkan progres.",
    "Enable cloud progress sync explicitly before syncing." to "Aktifkan sinkronisasi progres awan secara eksplisit sebelum menyinkronkan.",
    "Local sync storage is unavailable; no progress was sent." to "Penyimpanan sinkronisasi lokal tidak tersedia; progres belum dikirim.",
    "Progress sync is temporarily unavailable; local data was kept." to "Sinkronisasi sementara tidak tersedia; data lokal dipertahankan.",
    "A conflicting local progress event was kept for review." to "Peristiwa progres lokal yang berkonflik dipertahankan untuk ditinjau.",
    "The local sync queue is full; the local workflow remains available." to "Antrean sinkronisasi lokal penuh; alur lokal tetap tersedia.",
    "The queued progress belongs to another account and was not sent." to "Progres antrean milik akun lain dan tidak dikirim.",
    "A verified account session is required to view server activity metadata." to "Sesi akun terverifikasi diperlukan untuk melihat metadata aktivitas server.",
    "Sign in again with a verified account to view activity metadata." to "Masuk kembali dengan akun terverifikasi untuk melihat metadata aktivitas.",
    "Your project change is already saved locally." to "Perubahan proyek sudah tersimpan secara lokal.",
    "The suggestion remains unapplied." to "Saran belum diterapkan.",
    "Your project change is already saved locally; retry to reconcile the outcome before requesting more AI." to "Perubahan proyek sudah tersimpan lokal; coba lagi untuk menyelaraskan hasil sebelum meminta AI berikutnya.",
    "The suggestion remains unapplied; retry to reconcile the outcome." to "Saran belum diterapkan; coba lagi untuk menyelaraskan hasil.",
    "Your project change remains saved locally." to "Perubahan proyek tetap tersimpan lokal.",
    "An abandoned AI preview outcome could not be recorded. Its valid-preview charge was already settled; retry to reconcile the outcome before another request." to "Hasil pratinjau AI yang ditinggalkan gagal dicatat. Biaya pratinjau valid sudah ditagihkan; coba selaraskan hasil sebelum meminta lagi.",
    "New research project" to "Proyek penelitian baru",
    "Provide an assignment brief and explicitly agree to send the selected context before requesting AI. Nothing was sent." to "Isi instruksi tugas dan setujui pengiriman konteks terpilih sebelum meminta AI. Data belum dikirim.",
    "The selected project identity and revision did not match. No AI request was sent." to "Identitas dan revisi proyek terpilih tidak sesuai. Permintaan AI belum dikirim.",
    "Check and grant revocable account-level consent before requesting assistance. No project context was sent." to "Periksa dan berikan persetujuan akun yang dapat dicabut sebelum meminta bantuan. Konteks belum dikirim.",
    "A project-AI request is still being reconciled. Wait for it to finish before starting another." to "Permintaan AI proyek masih diselaraskan. Tunggu selesai sebelum memulai permintaan lain.",
    "Apply or discard the current AI suggestion and resolve its credit action before requesting another." to "Terapkan atau buang saran AI saat ini dan selesaikan tindakan kredit sebelum meminta lagi.",
    "Saved project AI consent is not current. Review and grant it before requesting assistance. No project context was sent." to "Persetujuan AI proyek tersimpan kedaluwarsa. Tinjau dan berikan persetujuan sebelum meminta bantuan. Konteks belum dikirim.",
    "The project AI consent policy changed. Review and grant it again before requesting assistance. No project context was sent." to "Kebijakan persetujuan AI proyek berubah. Tinjau dan setujui kembali sebelum meminta bantuan. Konteks belum dikirim.",
    "Saved project AI consent could not be verified. No project context was sent; check your connection and consent status." to "Persetujuan tersimpan gagal diverifikasi. Konteks belum dikirim; periksa koneksi dan persetujuan.",
    "The server response did not match the selected project revision. It was not applied." to "Jawaban server tidak sesuai revisi terpilih dan tidak diterapkan.",
    "The verified account session is unavailable. No suggestion was applied; manual work remains available." to "Sesi akun terverifikasi tidak tersedia. Saran belum diterapkan; pekerjaan manual tetap tersedia.",
    "Project AI is not configured for this request." to "AI proyek belum dikonfigurasi untuk permintaan ini.",
    "Project AI could not confirm the credit settlement. Check your shared balance before retrying; the project was not changed." to "Penagihan kredit AI proyek belum terkonfirmasi. Periksa saldo bersama sebelum mencoba lagi; proyek tidak berubah.",
    "Review, apply, or dismiss the previous Project AI result before requesting another one." to "Tinjau, terapkan, atau tutup hasil AI proyek sebelumnya sebelum meminta lagi.",
    "A prior Project AI result is private to another signed-in account. Sign in to that account to reconcile it before starting another Project AI request." to "Hasil AI proyek sebelumnya milik akun lain. Masuk ke akun tersebut untuk menyelaraskan hasil sebelum meminta lagi.",
    "Sign in with a verified account before using Project AI. Your project remains local and manual editing is still available." to "Masuk dengan akun terverifikasi untuk memakai AI proyek. Proyek tetap lokal dan dapat diedit manual.",
    "Save a project created from a published method before requesting stage assistance. No context was sent." to "Simpan proyek yang dibuat dari metode terbit sebelum meminta bantuan tahap. Konteks belum dikirim.",
    "The selected project context does not match this stage. Review the selections and try again." to "Konteks proyek terpilih tidak sesuai tahap ini. Tinjau pilihan lalu coba lagi.",
    "Current account consent could not be verified. No project content was sent; review consent and retry." to "Persetujuan akun saat ini gagal diverifikasi. Isi proyek belum dikirim; tinjau persetujuan lalu coba lagi.",
    "Secure installation storage is unavailable. No project content was sent." to "Penyimpanan instalasi aman tidak tersedia. Isi proyek belum dikirim.",
    "A verified account session is required to register this project revision. No AI request was sent." to "Sesi akun terverifikasi diperlukan untuk mendaftarkan revisi. Permintaan AI belum dikirim.",
    "The server could not securely register the selected project context. No AI request was sent." to "Server gagal mendaftarkan konteks proyek dengan aman. Permintaan AI belum dikirim.",
    "The registered project revision did not match the current revision. No AI request was sent." to "Revisi terdaftar tidak sesuai revisi saat ini. Permintaan AI belum dikirim.",
    "Recording this AI suggestion outcome…" to "Mencatat hasil saran AI…",
    "The original account must be active to reconcile this AI activity." to "Akun asal harus aktif untuk menyelaraskan aktivitas AI ini.",
    "The applied revision is no longer the current local project revision." to "Revisi yang diterapkan bukan lagi revisi lokal terbaru.",
    "The suggestion is saved locally, but the server could not register its new revision. Retry to reconcile activity; the token-based preview charge is already settled." to "Saran tersimpan lokal, tetapi revisinya gagal didaftarkan ke server. Coba selaraskan aktivitas; biaya pratinjau berdasarkan token sudah ditagihkan.",
    "The original account must be active to reconcile this AI activity outcome." to "Akun asal harus aktif untuk menyelaraskan hasil aktivitas AI ini.",
    "A verified account session is required to record the AI activity. The preview charge is already settled." to "Sesi terverifikasi diperlukan untuk mencatat aktivitas AI. Biaya pratinjau sudah ditagihkan.",
    "The saved project changed. The AI suggestions are stale and will not be applied." to "Proyek tersimpan berubah. Saran AI kedaluwarsa dan tidak akan diterapkan.",
    "The preview no longer matches the selected saved fields. Nothing was applied." to "Pratinjau tidak lagi sesuai isian tersimpan terpilih. Tidak ada saran diterapkan.",
    "Rechecking consent and saving only the selected fields…" to "Memeriksa ulang persetujuan dan menyimpan hanya isian terpilih…",
    "Consent or the saved project changed. No AI suggestion was applied." to "Persetujuan atau proyek tersimpan berubah. Saran AI belum diterapkan.",
    "The project reducer rejected a stale or unsupported proposal; nothing was applied." to "Usulan kedaluwarsa atau tidak didukung ditolak; tidak ada saran diterapkan.",
    "The selected suggestion is saved locally; recording its activity and revision…" to "Saran terpilih tersimpan lokal; mencatat aktivitas dan revisinya…",
    "Recording dismissal…" to "Mencatat penolakan saran…",
    "Retrying the same activity settlement…" to "Mencoba penyelarasan aktivitas yang sama…",
    "This AI suggestion no longer matches the active account or project. No suggestion was applied." to "Saran AI tidak lagi sesuai akun atau proyek aktif. Saran belum diterapkan.",
    "Project and attachments were imported, but temporary attachment cleanup did not finish. The saved project remains available." to "Proyek dan lampiran diimpor, tetapi pembersihan lampiran sementara belum selesai. Proyek tersimpan tetap tersedia.",
    "Project imported as a separate copy with remapped IDs, relationships, and attachments." to "Proyek diimpor sebagai salinan terpisah dengan ID, hubungan, dan lampiran dipetakan ulang.",
    "Project imported as archived so it does not use an active project slot." to "Proyek diimpor sebagai arsip agar tidak memakai ruang proyek aktif.",
    "Project imported to this device. It has not been uploaded or academically evaluated." to "Proyek diimpor ke perangkat ini. Belum diunggah atau dinilai akademis.",
    "Archive content was restored as a new local revision. Earlier project history remains available." to "Isi cadangan dipulihkan sebagai revisi lokal baru. Riwayat terdahulu tetap tersedia.",
    "Choose a project to use this move with your own material. Practice answers remain separate." to "Pilih proyek untuk memakai langkah ini dengan materi sendiri. Jawaban latihan tetap terpisah.",
    "Using the case already loaded for this active review" to "Memakai kasus yang sudah dimuat untuk tinjauan aktif ini",
    "Bundled case kept: published content did not match the local evaluator contract" to "Kasus bawaan dipertahankan: konten terbit tidak sesuai aturan pemeriksaan lokal",
    "Bundled case kept until a verified account is available" to "Kasus bawaan dipertahankan hingga akun terverifikasi tersedia",
    "Bundled case kept · published content is unavailable" to "Kasus bawaan dipertahankan · konten terbit tidak tersedia",
    "Refreshing verified platform projections…" to "Memuat ulang status platform terverifikasi…",
    "Progress and entitlement projections are up to date" to "Status progres dan akses sudah terbaru",
    "Platform projections need a verified session; local data remains available" to "Status platform membutuhkan sesi terverifikasi; data lokal tetap tersedia",
    "Platform projections are temporarily unavailable; local data remains available" to "Status platform sementara tidak tersedia; data lokal tetap tersedia",
    "No eligible reminder is scheduled yet." to "Belum ada pengingat yang memenuhi syarat terjadwal.",
    "Reminders are scheduled on this device." to "Pengingat dijadwalkan di perangkat ini.",
    "Local reminders are unavailable in this build; the free core remains usable." to "Pengingat lokal tidak tersedia; fitur inti gratis tetap dapat dipakai.",
    "Reminder preferences restored for this account." to "Preferensi pengingat dipulihkan untuk akun ini.",
    "Local reminder preferences backed up to your account." to "Preferensi pengingat lokal dicadangkan ke akun.",
    "Reminder preferences changed elsewhere; local settings were kept." to "Preferensi berubah di tempat lain; pengaturan lokal dipertahankan.",
    "Reminder preferences changed elsewhere; local settings remain available." to "Preferensi berubah di tempat lain; pengaturan lokal tetap tersedia.",
    "Reminder preferences saved on this device and account." to "Preferensi pengingat disimpan di perangkat dan akun.",
    "Local reminders enabled." to "Pengingat lokal aktif.",
    "Local reminders are unavailable in this build." to "Pengingat lokal tidak tersedia dalam versi ini.",
    "Permission was not completed. You can try again later." to "Izin belum diberikan. Anda dapat mencoba nanti.",
    "Local reminders turned off." to "Pengingat lokal dinonaktifkan.",
    "The case changed while AI was responding. Open the current verification to try again." to "Kasus berubah saat AI menjawab. Buka pemeriksaan saat ini untuk mencoba lagi.",
    "Complete a deterministic verification first; there is no feedback to explain yet." to "Selesaikan pemeriksaan kasus terlebih dahulu; belum ada umpan balik untuk dijelaskan.",
    "AI assistance is available only when this reviewed case has a verified published context. Your deterministic feedback remains available." to "Bantuan AI hanya tersedia untuk kasus ditinjau dengan konteks terbit terverifikasi. Umpan balik pemeriksaan tetap tersedia.",
    "AI assistance needs a verified account and an active session." to "Bantuan AI membutuhkan akun terverifikasi dan sesi aktif.",
    "A grounded AI conversation could not be started. Your deterministic feedback is unchanged." to "Percakapan AI berbasis kasus gagal dimulai. Umpan balik pemeriksaan tidak berubah.",
    "AI assistance is temporarily unavailable; your local feedback was kept." to "Bantuan AI sementara tidak tersedia; umpan balik lokal dipertahankan.",
    "AI could not answer this turn. No draft change was made; deterministic feedback remains authoritative." to "AI gagal menjawab. Draf tidak berubah; hasil pemeriksaan tetap menjadi acuan.",
    "The server may have received this turn, so it was not retried automatically. Check credits before continuing." to "Server mungkin menerima pesan ini sehingga tidak dicoba ulang otomatis. Periksa kredit sebelum melanjutkan.",
    "AI returned an unexpected conversation response." to "AI memberikan jawaban percakapan tidak sesuai.",
    "The local chat was cleared, but credits could not be refreshed." to "Chat lokal dibersihkan, tetapi kredit gagal dimuat ulang.",
    "AI credits are still unavailable; deterministic feedback remains available." to "Kredit AI masih tidak tersedia; umpan balik pemeriksaan tetap tersedia.",
    "Previous-account progress was cleared from the local sync queue." to "Progres akun sebelumnya dihapus dari antrean sinkronisasi lokal.",
    "Signed-out progress was cleared from the local sync queue." to "Progres tanpa akun dihapus dari antrean sinkronisasi lokal.",
    "Cloud sync enabled for this verified account." to "Sinkronisasi awan aktif untuk akun terverifikasi ini.",
    "Checking the secure account session…" to "Memeriksa sesi akun aman…",
    "Sign in with a verified account to use Project AI. Manual project work remains available." to "Masuk dengan akun terverifikasi untuk memakai AI proyek. Pekerjaan manual tetap tersedia.",
    "Verify your email before sending selected project context to AI." to "Verifikasi email sebelum mengirim konteks proyek terpilih ke AI.",
    "Checking your secure account session…" to "Memeriksa sesi akun aman Anda…",
    "Sign in with a verified account to use AI. The rest of Evidrilo remains available without sign-in." to "Masuk dengan akun terverifikasi untuk memakai AI. Fitur Evidrilo lainnya tetap tersedia tanpa masuk.",
    "Verify your email before sending a question to AI." to "Verifikasi email sebelum mengirim pertanyaan ke AI.",
    "Close purchase options" to "Tutup pilihan pembelian",
    "Close subscription management" to "Tutup pengelolaan langganan",
    "The selected project is no longer available." to "Proyek terpilih tidak lagi tersedia.",
    "Checking account…" to "Memeriksa akun…",
    "Build a bounded conclusion" to "Susun kesimpulan terbatas",
    "Complete the conclusion" to "Lengkapi kesimpulan",
    "Revise once with the feedback" to "Revisi sekali dengan umpan balik",
    "Rebuild the conclusion after the evidence change" to "Susun ulang kesimpulan setelah bukti berubah",
    "Complete the premium conclusion" to "Lengkapi kesimpulan Pro",
    "Revise the premium conclusion once" to "Revisi kesimpulan Pro sekali",
    "Rebuild the premium conclusion after the evidence change" to "Susun ulang kesimpulan Pro setelah bukti berubah",
    "Choose a focused case" to "Pilih kasus terarah",
    "Each case keeps the same bounded conclusion method: supplied facts, limitations, one revision, and learner-authored text." to "Setiap kasus memakai cara menyusun kesimpulan yang sama: fakta tersedia, batasan, satu revisi, dan tulisan pelajar sendiri.",
    "Start selected case" to "Mulai kasus terpilih",
    "Free workflow" to "Alur gratis",
    "Packs" to "Paket",
    "Compare the premium evidence case" to "Bandingkan kasus bukti Pro",
    "The initial draft and one revision remain learner-authored. This premium session is not added to free-core local comparison history." to "Draf awal dan satu revisi tetap tulisan pelajar sendiri. Sesi Pro ini tidak ditambahkan ke riwayat perbandingan fitur inti gratis.",
    "Before feedback" to "Sebelum umpan balik",
    "After one revision" to "Setelah satu revisi",
    "The premium conclusion passes the bounded checks" to "Kesimpulan Pro memenuhi pemeriksaan terbatas",
    "The selected evidence, scope, limitations, and next action remain connected." to "Bukti terpilih, cakupan, batasan, dan langkah berikutnya tetap terhubung.",
    "Explore cases" to "Jelajahi kasus",
    "HYP" to "HIP",
    "Case question" to "Pertanyaan kasus",
    "Supplied hypothesis · context" to "Hipotesis tersedia · konteks",
    "This is a prediction to compare with the results, not an observation to select as evidence." to "Ini prediksi untuk dibandingkan dengan hasil, bukan pengamatan yang dipilih sebagai bukti.",
    "An initial draft step is defined only for revision and evidence-change drafts." to "Tahap draf awal hanya ditentukan untuk draf revisi dan perubahan bukti.",
    "Compare your reasoning" to "Bandingkan penalaran Anda",
    "The first draft remains stored beside the single revision. Evidrilo does not replace either draft with a generated answer." to "Draf pertama disimpan bersama satu revisi. Evidrilo tidak mengganti keduanya dengan jawaban buatan.",
    "Revision evidence and field changes" to "Perubahan bukti dan isian revisi",
    "The revised conclusion passes the bounded checks" to "Kesimpulan revisi memenuhi pemeriksaan terbatas",
    "You connected the selected evidence, scope, limitations, and next action." to "Anda menghubungkan bukti terpilih, cakupan, batasan, dan langkah berikutnya.",
    "Try the evidence-change challenge" to "Coba tantangan perubahan bukti",
    "Start a new review" to "Mulai tinjauan baru",
    "Not written" to "Belum ditulis",
    "Action reason" to "Alasan langkah",
    "The observations show a difference" to "Pengamatan menunjukkan perbedaan",
    "This is a limited observation" to "Ini pengamatan terbatas",
    "The case cannot establish a broader claim" to "Kasus belum membuktikan klaim lebih luas",
    "Unsupported relation" to "Hubungan tidak didukung",
    "Repeat the trials" to "Ulangi percobaan",
    "Control stirring" to "Kendalikan pengadukan",
    "Limit the claim" to "Batasi klaim",
    "No further action applies" to "Tidak ada langkah lanjutan yang berlaku",
    "Unsupported action" to "Langkah tidak didukung",
    "Hide details" to "Sembunyikan rincian",
    "Show details" to "Tampilkan rincian",
    "Expanded" to "Terbuka",
    "Collapsed" to "Tertutup",
    "Make your reasoning visible" to "Perlihatkan penalaran Anda",
    "Write your revised claim in 20–320 characters." to "Tulis klaim revisi dalam 20–320 karakter.",
    "Choose the scope." to "Pilih cakupan.",
    "Explain the selected limit in 10–240 characters." to "Jelaskan batasan terpilih dalam 10–240 karakter.",
    "What might matter?" to "Apa yang mungkin berpengaruh?",
    "Look closely at the sources." to "Perhatikan sumbernya.",
    "Look at the submissions." to "Perhatikan jawaban survei.",
)
